; Expand M1 definitions and lay out bytes/relocations without emitting output.
; Operation = #(kind payload file-offset byte-count).
(define (%m1-hex-digit c)
  (let ((n (char->integer c)))
    (cond ((<= 48 n 57) (- n 48)) ((<= 65 n 70) (- n 55))
          ((<= 97 n 102) (- n 87)) (else #f))))
(define (%m1-hex-bytes text)
  (let loop ((i 0) (high #f) (bytes '()))
    (if (= i (string-length text))
        (if high (error 'm1 "odd hexadecimal digit count" text) (list->string (reverse bytes)))
        (let* ((c (string-ref text i)) (digit (%m1-hex-digit c)))
          (cond ((%m1-space? c) (loop (+ i 1) high bytes))
                ((not digit) (error 'm1 "invalid hexadecimal bytes" text))
                (high (loop (+ i 1) #f (cons (integer->char (+ (* high 16) digit)) bytes)))
                (else (loop (+ i 1) digit bytes)))))))
(define (%m1-number text)
  (let ((length (string-length text)))
    (if (and (> length 2) (char=? (string-ref text 0) #\0)
             (memv (string-ref text 1) '(#\x #\X)))
        (string->number (substring text 2 length) 16)
        (if (and (> length 3) (char=? (string-ref text 0) #\-)
                 (char=? (string-ref text 1) #\0) (memv (string-ref text 2) '(#\x #\X)))
            (let ((n (string->number (substring text 3 length) 16))) (and n (- n)))
            (string->number text)))))
(define (%m1-expand token macros trail)
  (let ((entry (and (eq? (car token) 'word) (%m1-find macros (cdr token)))))
    (if (not entry) token
        (if (member (cdr token) trail) (error 'm1 "recursive macro" (cdr token))
            (%m1-expand (cdr entry) macros (cons (cdr token) trail))))))
(define (%m1-reference text offset)
  (let* ((prefix (string-ref text 0)) (name (substring text 1 (string-length text)))
         (width (cond ((eqv? prefix #\!) 1) ((memv prefix '(#\@ #\$)) 2) (else 4)))
         (number (%m1-number name)))
    (if (= (string-length name) 0) (error 'm1 "empty reference" text) #f)
    (cond (number (vector 'integer number offset width))
          ((memv prefix '(#\& #\$)) (vector 'absolute name offset width))
          (else (vector 'relative name offset width)))))
(define (%m1-layout-token token offset base labels)
  (let ((kind (car token)) (text (cdr token)))
    (cond ((eq? kind 'string)
           (let ((bytes (string-append text (string (integer->char 0)))))
             (vector 'bytes bytes offset (string-length bytes))))
          ((eq? kind 'hex)
           (let ((bytes (%m1-hex-bytes text))) (vector 'bytes bytes offset (string-length bytes))))
          ((char=? (string-ref text 0) #\:)
           (let ((name (substring text 1 (string-length text))))
             (if (= (string-length name) 0) (error 'm1 "empty label") #f)
             (%m1-put! labels name (+ base offset) #f)
             (vector 'padding #f offset 0)))
          ((string=? text "<") (vector 'padding #f offset (modulo (- (+ base offset)) 4)))
          ((memv (string-ref text 0) '(#\! #\@ #\$ #\% #\&)) (%m1-reference text offset))
          (else (let ((bytes (%m1-hex-bytes text)))
                  (vector 'bytes bytes offset (string-length bytes)))))))
(define (%m1-layout tokens macros labels base)
  (let loop ((tokens tokens) (offset 0) (operations '()))
    (if (null? tokens) (cons offset (reverse operations))
        (let* ((token (%m1-expand (car tokens) macros '()))
               (operation (%m1-layout-token token offset base labels)))
          (loop (cdr tokens) (+ offset (vector-ref operation 3)) (cons operation operations))))))
