; Tokenizer for the i386 M1/hex2 source subset emitted by MesCC.
; Quotes are raw M1 strings, not Scheme/C escapes. Double quotes append NUL;
; single quotes contain hexadecimal bytes. Comments do not occur inside quotes.
(define (%m1-space? c)
  (and (char? c) (memv (char->integer c) '(9 10 11 12 13 32))))
(define (%m1-comment p)
  (let ((c (read-char p)))
    (if (or (eof-object? c) (eqv? c #\newline)) #t (%m1-comment p))))
(define (%m1-skip p)
  (let ((c (peek-char p)))
    (cond ((%m1-space? c) (read-char p) (%m1-skip p))
          ((or (eqv? c #\#) (eqv? c #\;)) (%m1-comment p) (%m1-skip p))
          (else c))))
(define (%m1-quoted p delimiter chars)
  (let ((c (read-char p)))
    (cond ((eof-object? c) (error 'm1 "unterminated quote" (port-filename p)))
          ((eqv? c delimiter) (list->string (reverse chars)))
          (else (%m1-quoted p delimiter (cons c chars))))))
(define (%m1-word p chars)
  (let ((c (peek-char p)))
    (if (or (eof-object? c) (%m1-space? c) (memv c '(#\# #\;)))
        (list->string (reverse chars))
        (begin (read-char p) (%m1-word p (cons c chars))))))
(define (%m1-token p)
  (let ((c (%m1-skip p)))
    (cond ((eof-object? c) #f)
          ((memv c '(#\" #\'))
           (read-char p)
           (cons (if (eqv? c #\") 'string 'hex) (%m1-quoted p c '())))
          (else (cons 'word (%m1-word p '()))))))

; Fixed buckets suffice for the compiler's labels and macro names. Keys remain
; strings; no quadratic interning of thousands of assembler-generated labels.
(define (%m1-table) (make-vector 4093 '()))
(define (%m1-hash key)
  (let loop ((i 0) (hash 0))
    (if (= i (string-length key)) hash
        (loop (+ i 1) (modulo (+ (* hash 33) (char->integer (string-ref key i))) 4093)))))
(define (%m1-assoc key entries)
  (cond ((null? entries) #f) ((string=? key (caar entries)) (car entries))
        (else (%m1-assoc key (cdr entries)))))
(define (%m1-find table key) (%m1-assoc key (vector-ref table (%m1-hash key))))
(define (%m1-put! table key value replace?)
  (let* ((index (%m1-hash key)) (entry (%m1-assoc key (vector-ref table index))))
    (if entry
        (if replace? (set-cdr! entry value)
            (if (equal? (cdr entry) value) #t (error 'm1 "duplicate definition" key)))
        (vector-set! table index (cons (cons key value) (vector-ref table index))))))
(define (%m1-read-source port macros tokens)
  (let ((token (%m1-token port)))
    (cond ((not token) tokens)
          ((and (eq? (car token) 'word) (string=? (cdr token) "DEFINE"))
           (let ((name (%m1-token port)) (value (%m1-token port)))
             (if (and name value (eq? (car name) 'word))
                 (%m1-put! macros (cdr name) value #t)
                 (error 'm1 "incomplete DEFINE" (port-filename port)))
             (%m1-read-source port macros tokens)))
          (else (%m1-read-source port macros (cons token tokens))))))
