; Resolve every relocation into an in-memory image before opening its output.
(define (%m1-index text char)
  (let loop ((i 0))
    (cond ((= i (string-length text)) #f) ((char=? (string-ref text i) char) i)
          (else (loop (+ i 1))))))
(define (%m1-address labels name)
  (let ((number (%m1-number name)) (entry (%m1-find labels name)))
    (cond (number number) (entry (cdr entry)) (else (error 'm1 "undefined label" name)))))
(define (%m1-relocation operation labels base)
  (let* ((kind (vector-ref operation 0)) (name (vector-ref operation 1))
         (offset (vector-ref operation 2)) (width (vector-ref operation 3))
         (split (%m1-index name #\>))
         (target (%m1-address labels (if split (substring name 0 split) name))))
    (cond (split (- target (%m1-address labels (substring name (+ split 1) (string-length name)))))
          ((eq? kind 'absolute) target)
          (else (- target (+ base offset width))))))
(define (%m1-check-relocation value kind width)
  (let* ((bits (* width 8)) (limit (ash 1 bits)) (half (quotient limit 2)))
    (if (if (eq? kind 'relative) (and (>= value (- half)) (< value half))
            (and (>= value 0) (< value limit)))
        #t (error 'm1 "relocation out of range" value width))))
(define (%m1-store-integer! output offset width value)
  ; M1 numeric immediates retain the low bits, including negative immediates.
  (let loop ((index offset) (left width) (value value))
    (if (= left 0) #t
        (let ((byte (modulo value 256)))
          (string-set! output index (integer->char byte))
          (loop (+ index 1) (- left 1) (quotient (- value byte) 256))))))
(define (%m1-link-operation! output operation labels base)
  (let ((kind (vector-ref operation 0)) (payload (vector-ref operation 1))
        (offset (vector-ref operation 2)) (width (vector-ref operation 3)))
    (cond ((eq? kind 'bytes) (%copy-string! payload 0 width output offset))
          ((eq? kind 'padding) #t)
          ((eq? kind 'integer) (%m1-store-integer! output offset width payload))
          (else (let ((value (%m1-relocation operation labels base)))
                  (%m1-check-relocation value kind width)
                  (%m1-store-integer! output offset width value))))))
(define (%m1-link layout labels base)
  (let ((output (make-string (car layout) (integer->char 0))))
    (for-each (lambda (operation) (%m1-link-operation! output operation labels base)) (cdr layout))
    output))
(define (%m1-assemble files base)
  (let ((macros (%m1-table)) (labels (%m1-table)))
    (let loop ((files files) (tokens '()))
      (if (null? files)
          (%m1-link (%m1-layout (reverse tokens) macros labels base) labels base)
          (loop (cdr files)
                (call-with-input-file (car files)
                  (lambda (port) (%m1-read-source port macros tokens))))))))
