; Combined M1/hex2 assembler: i386, little endian, deterministic two-pass link.
(define (%m1-option-argument args)
  (if (null? (cdr args)) (error 'm1 "missing option argument" (car args)) (cadr args)))
(define (%m1-run files base output)
  (if (null? files) (error 'm1 "no input files") #f)
  (let ((image (%m1-assemble files base)))
    (if output (call-with-output-file output (lambda (port) (%write-string image port)))
        (%write-string image (current-output-port)))))
(define (%m1-main args)
  (let loop ((args args) (files '()) (base 16777216) (output #f))
    (cond ((null? args) (%m1-run (reverse files) base output))
          ((string=? (car args) "--") (%m1-run (append (reverse files) (cdr args)) base output))
          ((string=? (car args) "--little-endian") (loop (cdr args) files base output))
          ((string=? (car args) "--architecture")
           (if (not (string=? (%m1-option-argument args) "x86")) (error 'm1 "only x86 is supported") #f)
           (loop (cddr args) files base output))
          ((string=? (car args) "--base-address")
           (let ((value (%m1-number (%m1-option-argument args))))
             (if (and value (<= 0 value) (< value (ash 1 32)))
                 (loop (cddr args) files value output)
                 (error 'm1 "invalid base address" (%m1-option-argument args)))))
          ((string=? (car args) "-o")
           (let ((path (%m1-option-argument args))) (loop (cddr args) files base path)))
          ((string=? (car args) "-f")
           (let ((path (%m1-option-argument args))) (loop (cddr args) (cons path files) base output)))
          ((and (> (string-length (car args)) 0) (char=? (string-ref (car args) 0) #\-))
           (error 'm1 "unknown option" (car args)))
          (else (loop (cdr args) (cons (car args) files) base output)))))
(%m1-main (cdr (command-line)))
