; gen-sc1-runtime.scm --- emit the Stage-3 fixed runtime (two spellings).
;
; A dev-time generator in the rsc dialect for the assembly library that
; sits under every program compiled by sc1.scm.  It replaced the retired
; tools/generate_sc1_runtime.py; its outputs stay byte-identical to the
; committed artifacts (the artifacts are frozen; only this generator may
; be edited for readability).
;
; Two output modes, ONE pair of instruction lists, so they cannot drift:
;   (no args)  bootstrap/sc1-runtime.qf1 -- qfasm rule text: the
;              (RuntimeCode rest)/(RuntimeData rest) macros that the tail
;              of every compiled program expands, plus Size/Pass2 rules
;              teaching qfasm the DObj/MovRIObj directives (object-pointer
;              constants: label address + 2) used for compiled literals;
;   --flat     bootstrap/sc1-asm-runtime.flat -- the SAME code and data
;              instruction lists as a flat "<code...> RTSPLIT <data...>"
;              file, which the native assembler asm.elf takes as argv[1]
;              and splices at the (RuntimeCode (RuntimeData End)) tail
;              (asm.elf implements DObj/MovRIObj natively, hence no rules).
;
; Why a generator: the primitive table appears in several guises -- the
; InitPrims closure-shell loop, the code entry points, the (GV name) data
; cells -- and sc1.scm's own prim-name list must agree with all of them;
; one PRIMS table here keeps the runtime's copies in step.
;
; The routines are scheme0's runtime core -- allocator, character input,
; intern, printer, primitives; see gen-scheme0.scm for the annotated
; versions and the tagged object model -- WITHOUT the reader/evaluator:
; sc1 compiles to machine code, so only the support library remains.
; Primitives receive the evaluated argument list in EAX.
;
; Regenerate:  tools/regen.sh gen sc1-runtime        > bootstrap/sc1-runtime.qf1
;              tools/regen.sh gen sc1-runtime --flat > bootstrap/sc1-asm-runtime.flat
; Verify:      make regen-verify
;              -> "all committed generated artifacts reproduced byte-identically"

; ---------------------------------------------------------------------------
; Number formatting: x8 (big-endian 8 hex digits) and imm (Small or X8).
; ---------------------------------------------------------------------------
(define (k n) (w32-from-fixnum n))
(define wm1 (w32-not (k 0)))
(define w16 (k 16))
(define hexdigits "0123456789ABCDEF")
(define (hexU n) (string (string-ref hexdigits n)))
(define (nib w sh) (hexU (w32->fixnum (w32-and (w32-shr w sh) (k 15)))))
(define (x8-str w)
  (string-append "(X8 "
    (nib w 28) " " (nib w 24) " " (nib w 20) " " (nib w 16) " "
    (nib w 12) " " (nib w 8) " " (nib w 4) " " (nib w 0) ")"))
(define (imm-str w)
  (if (w32-ult? w w16)
      (string-append "(Small " (hexU (w32->fixnum w)) ")")
      (x8-str w)))

; ---------------------------------------------------------------------------
; Value constants.
; ---------------------------------------------------------------------------
; The scheme0/sc1 immediates (tag 11): (), #t, #f, eof, unspecified.
; See gen-scheme0.scm for the full tag scheme.
(define NIL 3)      (define TRUE 19)   (define FALSE 35)
(define EOFV 51)    (define UNSPEC 67)

; ---------------------------------------------------------------------------
; C / D accumulators.  cur selects which list I appends to.
; ---------------------------------------------------------------------------
; Code and data are collected separately because the qf1 output wraps them
; in two different macros (RuntimeCode / RuntimeData) and the flat output
; splits them at the RTSPLIT marker.  PL = label behind (Align8): prim
; entry addresses get tag bits or'd in and must be 8-byte aligned.
(define c-rev '())
(define d-rev '())
(define cur 'c)
(define (set-cur! x) (set! cur x))
(define (I s)
  (if (eq? cur 'c) (set! c-rev (cons s c-rev)) (set! d-rev (cons s d-rev))))
(define (L name) (I (string-append "(Label " name ")")))
(define (PL name) (begin (I "(Align8)") (L name)))
(define (MOVRI r w) (I (string-append "(MovRI " r " " (imm-str w) ")")))
(define (CMPEAX w) (I (string-append "(CmpEaxI32 " (imm-str w) ")")))
(define (call t) (I (string-append "(Call " t ")")))
(define (gv name) (string-append "(GV " name ")"))
(define (ret-bool p)
  (begin
    (L (string-append "(" p " T)")) (MOVRI "EAX" (k TRUE)) (I "(Ret)")
    (L (string-append "(" p " F)")) (MOVRI "EAX" (k FALSE)) (I "(Ret)")))
(define (cmp-prim label p jcc)
  (begin
    (PL label)
    (I "(MovRM ECX EAX)") (I "(MovRMD EAX EAX 04)") (I "(MovRM EAX EAX)")
    (I "(CmpRR ECX EAX)")
    (I (string-append "(" jcc " (" p " T))"))
    (I (string-append "(JmpS (" p " F))"))
    (ret-bool p)))

; PRIMS: (scheme-name . code-label).  Defines the (GV name) data cells and
; the InitPrims loop; the names must match sc1.scm's prim-names list, which
; is how compiled code finds them (globals are looked up by name, not by
; index, so only the SET of names matters to the compiler).
(define PRIMS
  (list
    (cons "cons" "PrCons") (cons "car" "PrCar") (cons "cdr" "PrCdr")
    (cons "set-car!" "PrSetCar") (cons "set-cdr!" "PrSetCdr")
    (cons "pair?" "PrPairQ") (cons "null?" "PrNullQ")
    (cons "eq?" "PrEqQ") (cons "eqv?" "PrEqQ")
    (cons "symbol?" "PrSymQ") (cons "number?" "PrNumQ")
    (cons "string?" "PrStrQ") (cons "char?" "PrCharQ")
    (cons "procedure?" "PrProcQ") (cons "boolean?" "PrBoolQ")
    (cons "not" "PrNot")
    (cons "+" "PrAdd") (cons "-" "PrSub") (cons "*" "PrMul")
    (cons "quotient" "PrQuot") (cons "remainder" "PrRem")
    (cons "=" "PrNumEq") (cons "<" "PrLt") (cons ">" "PrGt")
    (cons "<=" "PrLe") (cons ">=" "PrGe")
    (cons "display" "PrDisplay") (cons "write" "PrWrite")
    (cons "newline" "PrNewline")
    (cons "read-char" "PrReadChar") (cons "peek-char" "PrPeekChar")
    (cons "eof-object?" "PrEofQ")
    (cons "char->integer" "PrCharInt") (cons "integer->char" "PrIntChar")
    (cons "string-length" "PrStrLen") (cons "string-ref" "PrStrRef")
    (cons "string->symbol" "PrStrSym") (cons "symbol->string" "PrSymStr")
    (cons "list->string" "PrListStr")
    (cons "error" "PrError") (cons "exit" "PrExit")))

; ---------------------------------------------------------------------------
; CODE
; ---------------------------------------------------------------------------
(define (build-code)
  (set-cur! 'c)
  ; HeapInit: carve bump arenas out of the flat bss after CodeEnd (no GC):
  ; cell arena at CodeEnd (8-aligned), byte arena +0x0C000000 (192 MiB in),
  ; 16 MiB stdin read buffer +0x02000000 further, token buffer +0x01000000
  ; beyond that.  Compiled code calls this first.
  (L "HeapInit")
  (I "(MovRILabel EAX CodeEnd)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GCellFree EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 12) 24)) ")"))   ; 0x0C000000
  (I "(MovMemLR GByteFree EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 2) 24)) ")"))    ; 0x02000000
  (I "(MovMemLR GReadBuf EAX)")
  (I "(MovMemLR GInPtr EAX)")
  (I "(MovMemLR GInEnd EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 1) 24)) ")"))    ; 0x01000000
  (I "(MovMemLR GTokBuf EAX)")
  (I "(Ret)")
  ; InitPrims: wrap every Pr* entry point as a CLOSURE object -- subtype-2
  ; payload (code . nil) -- and store it in the prim's (GV name) cell, so
  ; compiled code applies primitives exactly like user closures (sc1 has
  ; no separate primitive calling convention).
  (L "InitPrims")
  (for-each
    (lambda (p)
      (begin
        (I (string-append "(MovRILabel EAX " (cdr p) ")"))
        (MOVRI "ECX" (k NIL))
        (call "Cons")
        (I "(OrI8 EAX 02)")
        (MOVRI "ECX" (k 1))
        (call "Cons")
        (I "(OrI8 EAX 02)")
        (I (string-append "(MovMemLR " (gv (car p)) " EAX)"))))
    PRIMS)
  (I "(Ret)")
  ; Cons: bump an 8-byte cell off GCellFree; car=EAX, cdr=ECX.
  (L "Cons")
  (I "(PushR EDX)")
  (I "(MovRMemL EDX GCellFree)")
  (I "(MovMR EDX EAX)")
  (I "(MovMDR EDX 04 ECX)")
  (I "(MovRR EAX EDX)")
  (I "(AddI8 EDX 08)")
  (I "(MovMemLR GCellFree EDX)")
  (I "(PopR EDX)")
  (I "(Ret)")
  ; AllocObj: EAX = source bytes, ECX = length, EDX = subtype; copy into
  ; the byte arena and build the object cell [payload|subtype, len<<2|1].
  (L "AllocObj")
  (I "(PushR EDX)")
  (I "(MovRMemL EDI GByteFree)")
  (I "(PushR EDI)")
  (I "(MovRR ESI EAX)")
  (I "(PushR ECX)")
  (I "(RepMovsb)")
  (I "(PopR ECX)")
  (I "(MovRR EAX EDI)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GByteFree EAX)")
  (I "(PopR EAX)")
  (I "(PopR EDX)")
  (I "(OrRR EAX EDX)")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")
  ; ReadCh: one character in EAX, or -1 at eof; GPeek is the one-slot
  ; pushback (-1 = empty) behind peek-char.  PeekCh reads and re-arms it.
  (L "ReadCh")
  (I "(MovRMemL EAX GPeek)")
  (CMPEAX wm1)
  (I "(Jz (RC 1))")
  (I "(PushR ECX)")
  (MOVRI "ECX" wm1)
  (I "(MovMemLR GPeek ECX)")
  (I "(PopR ECX)")
  (I "(Ret)")
  (L "(RC 1)")
  (I "(PushR ECX)")
  (I "(MovRMemL EAX GInPtr)")
  (I "(MovRMemL ECX GInEnd)")
  (I "(CmpRR EAX ECX)")
  (I "(Jnz (RC 3))")
  (I "(PushR EBX)")
  (I "(PushR EDX)")
  (MOVRI "EAX" (k 3))
  (I "(XorRR EBX EBX)")
  (I "(MovRMemL ECX GReadBuf)")
  (MOVRI "EDX" (k 16777216))
  (I "(Int 80)")
  (I "(TestRR EAX EAX)")
  (I "(Jg (RC 2))")
  (I "(PopR EDX)")
  (I "(PopR EBX)")
  (I "(PopR ECX)")
  (MOVRI "EAX" wm1)
  (I "(Ret)")
  (L "(RC 2)")
  (I "(MovRMemL ECX GReadBuf)")
  (I "(MovMemLR GInPtr ECX)")
  (I "(AddRR ECX EAX)")
  (I "(MovMemLR GInEnd ECX)")
  (I "(PopR EDX)")
  (I "(PopR EBX)")
  (I "(MovRMemL EAX GInPtr)")
  (L "(RC 3)")
  (I "(MovRR ECX EAX)")
  (I "(MovzxRMb EAX ECX)")
  (I "(IncR ECX)")
  (I "(MovMemLR GInPtr ECX)")
  (I "(PopR ECX)")
  (I "(Ret)")
  ; PeekCh
  (L "PeekCh")
  (call "ReadCh")
  (I "(MovMemLR GPeek EAX)")
  (I "(Ret)")
  ; Emit: write(1, WriteChBuf, 1) with the byte from AL; PrintRaw:
  ; write(1, ECX, EDX).
  (L "Emit")
  (I "(PushR EBX)")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (I "(MovRILabel ECX WriteChBuf)")
  (I "(MovbMR ECX EAX)")
  (MOVRI "EAX" (k 4))
  (MOVRI "EBX" (k 1))
  (MOVRI "EDX" (k 1))
  (I "(Int 80)")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(PopR EBX)")
  (I "(Ret)")
  ; PrintRaw
  (L "PrintRaw")
  (MOVRI "EAX" (k 4))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")
  (I "(Ret)")
  ; ErrApply
  (L "ErrApply")
  (MOVRI "EAX" (k 33))
  (call "Emit")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")
  ; Intern: EAX = bytes, ECX = length; linear oblist scan (length, then
  ; RepeCmpsb), allocating a fresh subtype-0 symbol on a miss.  Kept in
  ; the runtime for string->symbol and for compiled symbol literals.
  (L "Intern")
  (I "(MovRMemL EDX GObList)")
  (L "(IN 1)")
  (I "(TestRI8 EDX 03)")
  (I "(Jz (IN 2))")
  (I "(XorRR EDX EDX)")
  (call "AllocObj")
  (I "(PushR EAX)")
  (I "(MovRMemL ECX GObList)")
  (call "Cons")
  (I "(MovMemLR GObList EAX)")
  (I "(PopR EAX)")
  (I "(Ret)")
  (L "(IN 2)")
  (I "(MovRM EBX EDX)")
  (I "(MovRR EDI EBX)")
  (I "(SubI8 EDI 02)")
  (I "(MovRMD ESI EDI 04)")
  (I "(SarI8 ESI 02)")
  (I "(CmpRR ESI ECX)")
  (I "(Jnz (IN 3))")
  (I "(MovRM ESI EDI)")
  (I "(MovRR EDI EAX)")
  (I "(PushR ECX)")
  (I "(RepeCmpsb)")
  (I "(PopR ECX)")
  (I "(Jnz (IN 3))")
  (I "(MovRR EAX EBX)")
  (I "(Ret)")
  (L "(IN 3)")
  (I "(MovRMD EDX EDX 04)")
  (I "(JmpS (IN 1))")
  ; --- Primitives ---
  ; Argument list in EAX, result in EAX; bodies as in gen-scheme0.scm
  ; (including the tagged-arithmetic re-tag tricks in PrAdd/PrSub).
  (PL "PrCons")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRM ECX ECX)")
  (I "(MovRM EAX EAX)")
  (I "(Jmp32 Cons)")

  (PL "PrCar")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (CAR 1))")
  (I "(Jmp32 ErrApply)")
  (L "(CAR 1)")
  (I "(MovRM EAX EAX)")
  (I "(Ret)")

  (PL "PrCdr")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (CDR 1))")
  (I "(Jmp32 ErrApply)")
  (L "(CDR 1)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")

  (PL "PrSetCar")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(MovMR ECX EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrSetCdr")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(MovMDR ECX 04 EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrPairQ")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (PQ T))")
  (I "(JmpS (PQ F))")
  (ret-bool "PQ")

  (PL "PrNullQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k NIL))
  (I "(Jz (NQ T))")
  (I "(JmpS (NQ F))")
  (ret-bool "NQ")

  (PL "PrEqQ")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(CmpRR EAX ECX)")
  (I "(Jz (EQ T))")
  (I "(JmpS (EQ F))")
  (ret-bool "EQ")

  (PL "PrSymQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (SYQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 07)")
  (I "(Jz (SYQ T))")
  (I "(JmpS (SYQ F))")
  (ret-bool "SYQ")

  (PL "PrNumQ")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 01)")
  (I "(Jz (NUQ F))")
  (I "(TestRI8 EAX 02)")
  (I "(Jz (NUQ T))")
  (I "(JmpS (NUQ F))")
  (ret-bool "NUQ")

  (PL "PrStrQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (STQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 01)")
  (I "(Jz (STQ T))")
  (I "(JmpS (STQ F))")
  (ret-bool "STQ")

  (PL "PrCharQ")
  (I "(MovRM EAX EAX)")
  (I (string-append "(AndI32 EAX " (x8-str (k 255)) ")"))
  (I "(CmpI8 EAX 53)")
  (I "(Jz (CHQ T))")
  (I "(JmpS (CHQ F))")
  (ret-bool "CHQ")

  (PL "PrProcQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (PCQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 02)")
  (I "(Jz (PCQ T))")
  (I "(CmpI8 EAX 03)")
  (I "(Jz (PCQ T))")
  (I "(JmpS (PCQ F))")
  (ret-bool "PCQ")

  (PL "PrBoolQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k TRUE))
  (I "(Jz (BQ T))")
  (CMPEAX (k FALSE))
  (I "(Jz (BQ T))")
  (I "(JmpS (BQ F))")
  (ret-bool "BQ")

  (PL "PrNot")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k FALSE))
  (I "(Jz (NO T))")
  (I "(JmpS (NO F))")
  (ret-bool "NO")

  (PL "PrAdd")
  (MOVRI "ECX" (k 1))
  (L "(AD 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (AD 2))")
  (I "(MovRM EDX EAX)")
  (I "(AddRR ECX EDX)")
  (I "(DecR ECX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (AD 1))")
  (L "(AD 2)")
  (I "(MovRR EAX ECX)")
  (I "(Ret)")

  (PL "PrSub")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (SB 1))")
  (MOVRI "EAX" (k 2))
  (I "(SubRR EAX ECX)")
  (I "(Ret)")
  (L "(SB 1)")
  (I "(MovRM EDX EAX)")
  (I "(SubRR ECX EDX)")
  (I "(IncR ECX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (SB 1))")
  (I "(MovRR EAX ECX)")
  (I "(Ret)")

  (PL "PrMul")
  (MOVRI "ECX" (k 1))
  (L "(MU 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (MU 2))")
  (I "(MovRM EDX EAX)")
  (I "(SarI8 EDX 02)")
  (I "(IMulRR ECX EDX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (MU 1))")
  (L "(MU 2)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrQuot")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EBX EAX)")
  (I "(MovRR EAX ECX)")
  (I "(SarI8 EAX 02)")
  (I "(SarI8 EBX 02)")
  (I "(Cdq)")
  (I "(IDivR EBX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrRem")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EBX EAX)")
  (I "(MovRR EAX ECX)")
  (I "(SarI8 EAX 02)")
  (I "(SarI8 EBX 02)")
  (I "(Cdq)")
  (I "(IDivR EBX)")
  (I "(MovRR EAX EDX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (cmp-prim "PrNumEq" "NE" "Jz")
  (cmp-prim "PrLt" "LTP" "Jl")
  (cmp-prim "PrGt" "GTP" "Jg")
  (cmp-prim "PrLe" "LEP" "Jle")
  (cmp-prim "PrGe" "GEP" "Jge")

  (PL "PrDisplay")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (DS 2))")
  (I "(MovRR EDX EAX)")
  (I "(SubI8 EDX 02)")
  (I "(MovRM ECX EDX)")
  (I "(MovRR EBX ECX)")
  (I "(AndI8 EBX 07)")
  (I "(CmpI8 EBX 01)")
  (I "(Jnz (DS 3))")
  (I "(AndI8 ECX F8)")
  (I "(MovRMD EDX EDX 04)")
  (I "(SarI8 EDX 02)")
  (call "PrintRaw")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(DS 2)")
  (I "(CmpI8 ECX 03)")
  (I "(Jnz (DS 3))")
  (I "(MovRR EDX EAX)")
  (I (string-append "(AndI32 EDX " (x8-str (k 255)) ")"))
  (I "(CmpI8 EDX 53)")
  (I "(Jnz (DS 3))")
  (I "(ShrI8 EAX 08)")
  (call "Emit")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(DS 3)")
  (call "Print")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrWrite")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrNewline")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrReadChar")
  (call "ReadCh")
  (CMPEAX wm1)
  (I "(Jz (RDC 1))")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")
  (L "(RDC 1)")
  (MOVRI "EAX" (k EOFV))
  (I "(Ret)")

  (PL "PrPeekChar")
  (call "PeekCh")
  (CMPEAX wm1)
  (I "(Jz (PKC 1))")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")
  (L "(PKC 1)")
  (MOVRI "EAX" (k EOFV))
  (I "(Ret)")

  (PL "PrEofQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k EOFV))
  (I "(Jz (EFQ T))")
  (I "(JmpS (EFQ F))")
  (ret-bool "EFQ")

  (PL "PrCharInt")
  (I "(MovRM EAX EAX)")
  (I "(ShrI8 EAX 08)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrIntChar")
  (I "(MovRM EAX EAX)")
  (I "(SarI8 EAX 02)")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")

  (PL "PrStrLen")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")

  (PL "PrStrRef")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EDX EAX)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM EBX ECX)")
  (I "(AndI8 EBX F8)")
  (I "(SarI8 EDX 02)")
  (I "(AddRR EBX EDX)")
  (I "(MovzxRMb EAX EBX)")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")

  (PL "PrStrSym")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRR EDX EAX)")
  (I "(MovRM EAX EDX)")
  (I "(AndI8 EAX F8)")
  (I "(MovRMD ECX EDX 04)")
  (I "(SarI8 ECX 02)")
  (I "(Jmp32 Intern)")

  (PL "PrSymStr")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EDX EAX)")
  (I "(OrI8 EDX 01)")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRR EAX EDX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (PL "PrListStr")
  (I "(MovRM EDX EAX)")
  (I "(MovRMemL EDI GTokBuf)")
  (L "(LS 1)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (LS 2))")
  (I "(MovRM EAX EDX)")
  (I "(ShrI8 EAX 08)")
  (I "(MovbMR EDI EAX)")
  (I "(IncR EDI)")
  (I "(MovRMD EDX EDX 04)")
  (I "(JmpS (LS 1))")
  (L "(LS 2)")
  (I "(MovRMemL EAX GTokBuf)")
  (I "(MovRR ECX EDI)")
  (I "(SubRR ECX EAX)")
  (MOVRI "EDX" (k 1))
  (I "(Jmp32 AllocObj)")

  (PL "PrError")
  (L "(ER 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (ER 2))")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (ER 1))")
  (L "(ER 2)")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")

  (PL "PrExit")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (EX 1))")
  (I "(MovRM EBX EAX)")
  (I "(SarI8 EBX 02)")
  (MOVRI "EAX" (k 1))
  (I "(Int 80)")
  (L "(EX 1)")
  (MOVRI "EAX" (k 1))
  (I "(XorRR EBX EBX)")
  (I "(Int 80)")

  ; --- Printer ---
  ; write notation, dispatched on the tag; see gen-scheme0.scm.
  (L "Print")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 01)")
  (I "(Jnz (PR 1))")
  (I "(Jmp32 PrintNum)")
  (L "(PR 1)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (PR 2))")
  (I "(Jmp32 PrintObj)")
  (L "(PR 2)")
  (I "(CmpI8 ECX 03)")
  (I "(Jnz (PR 3))")
  (I "(Jmp32 PrintImm)")
  (L "(PR 3)")
  (I "(Jmp32 PrintPair)")

  (L "PrintNum")
  (I "(SarI8 EAX 02)")
  (I "(TestRR EAX EAX)")
  (I "(Jns (PN 1))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 45))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(NegR EAX)")
  (L "(PN 1)")
  (I "(XorRR EBX EBX)")
  (MOVRI "ECX" (k 10))
  (L "(PN 2)")
  (I "(XorRR EDX EDX)")
  (I "(DivR ECX)")
  (I "(AddI8 EDX 30)")
  (I "(PushR EDX)")
  (I "(IncR EBX)")
  (I "(TestRR EAX EAX)")
  (I "(Jnz (PN 2))")
  (L "(PN 3)")
  (I "(PopR EAX)")
  (call "Emit")
  (I "(DecR EBX)")
  (I "(Jnz (PN 3))")
  (I "(Ret)")

  (L "PrintPair")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 40))
  (call "Emit")
  (I "(PopR EAX)")
  (L "(PP 1)")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (I "(PopR EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (PP 2))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(Jmp32 (PP 1))")
  (L "(PP 2)")
  (CMPEAX (k NIL))
  (I "(Jnz (PP 3))")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")
  (L "(PP 3)")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (MOVRI "EAX" (k 46))
  (call "Emit")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (call "Print")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")

  (L "PrintObj")
  (I "(SubI8 EAX 02)")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EDX EAX 04)")
  (I "(SarI8 EDX 02)")
  (I "(MovRR EBX ECX)")
  (I "(AndI8 EBX 07)")
  (I "(TestRR EBX EBX)")
  (I "(Jnz (PO 1))")
  (I "(Jmp32 PrintRaw)")
  (L "(PO 1)")
  (I "(CmpI8 EBX 01)")
  (I "(Jz (PO 2))")
  (MOVRI "EAX" (k 63))
  (I "(Jmp32 Emit)")
  (L "(PO 2)")
  (MOVRI "EAX" (k 34))
  (call "Emit")
  (I "(AndI8 ECX F8)")
  (call "PrintRaw")
  (MOVRI "EAX" (k 34))
  (I "(Jmp32 Emit)")

  (L "PrintImm")
  (CMPEAX (k NIL))
  (I "(Jnz (PI 1))")
  (MOVRI "EAX" (k 40))
  (call "Emit")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")
  (L "(PI 1)")
  (CMPEAX (k TRUE))
  (I "(Jnz (PI 2))")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 116))
  (I "(Jmp32 Emit)")
  (L "(PI 2)")
  (CMPEAX (k FALSE))
  (I "(Jnz (PI 3))")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 102))
  (I "(Jmp32 Emit)")
  (L "(PI 3)")
  (I "(MovRR ECX EAX)")
  (I (string-append "(AndI32 ECX " (x8-str (k 255)) ")"))
  (I "(CmpI8 ECX 53)")
  (I "(Jnz (PI 4))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 92))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(ShrI8 EAX 08)")
  (I "(Jmp32 Emit)")
  (L "(PI 4)")
  (MOVRI "EAX" (k 63))
  (I "(Jmp32 Emit)"))

; ---------------------------------------------------------------------------
; DATA
; ---------------------------------------------------------------------------
; Global cells (GObList starts as nil = 0x03, GPeek as -1 = pushback
; empty), the one-byte write buffer, and one (GV name) cell per primitive
; for InitPrims to fill.  CodeEnd marks where HeapInit's arenas begin.
(define (build-data)
  (set-cur! 'd)
  (I "(Align4)")
  (for-each
    (lambda (g)
      (begin
        (L g)
        (I (string-append "(Dd "
             (x8-str (if (string=? g "GObList") (k NIL) (k 0))) ")"))))
    (list "GCellFree" "GByteFree" "GInPtr" "GInEnd" "GObList"
          "GTokBuf" "GReadBuf"))
  (L "GPeek")
  (I (string-append "(Dd " (x8-str wm1) ")"))
  (L "WriteChBuf")
  (I "(Db 00)")
  (I "(Align4)")
  (for-each
    (lambda (p)
      (begin
        (L (gv (car p)))
        (I (string-append "(Dd " (x8-str (k 0)) ")"))))
    PRIMS)
  (I "(Align8)")
  (L "CodeEnd"))

; ---------------------------------------------------------------------------
; Emission.
; ---------------------------------------------------------------------------
; Block chaining, the same trick as gen-scheme0's (Z n) rules but with the
; compiler's continuation threaded through: the macro head (RuntimeCode
; rest) expands to 24 (Ins ...) wrappers ending in (RTC 1 rest), and so on
; down the chain until the last block tails into `rest` itself.  Compiled
; programs therefore just end "... (RuntimeCode (RuntimeData End))" and
; the whole runtime unfolds in place.  In --flat mode the same lists are
; printed one instruction per line around an RTSPLIT marker for asm.elf.
(define (repeat-str s n) (if (= n 0) "" (string-append s (repeat-str s (- n 1)))))
(define (take-n lst n) (if (or (= n 0) (null? lst)) '() (cons (car lst) (take-n (cdr lst) (- n 1)))))
(define (drop-n lst n) (if (or (= n 0) (null? lst)) lst (drop-n (cdr lst) (- n 1))))
(define (pl s) (begin (display s) (newline)))

(define (emit-blocks top chain items bi)
  (if (null? items)
      #t
      (let ((blk (take-n items 24))
            (rest (drop-n items 24)))
        (begin
          (if (= bi 0)
              (pl (string-append "(Rule (" top " rest)"))
              (pl (string-append "(Rule (" chain " " (number->string bi) " rest)")))
          (for-each (lambda (ins) (pl (string-append "  (Ins " ins))) blk)
          (if (null? rest)
              (pl (string-append "  rest" (repeat-str ")" (length blk)) ")"))
              (pl (string-append "  (" chain " " (number->string (+ bi 1)) " rest)"
                    (repeat-str ")" (length blk)) ")")))
          (emit-blocks top chain rest (+ bi 1))))))

(define (emit-macro top chain items) (emit-blocks top chain items 0))

(define (emit-flat cc dd)
  (begin
    (for-each pl cc)
    (pl "RTSPLIT")
    (for-each pl dd)))

(define (has-flat)
  (let ((a (command-line)))
    (and (pair? a) (pair? (cdr a)) (string=? (cadr a) "--flat"))))

(define (main)
  (begin
    (build-code)
    (build-data)
    (let ((cc (reverse c-rev)) (dd (reverse d-rev)))
      (if (has-flat)
          (emit-flat cc dd)
          (begin
            (pl "; sc1-runtime: fixed assembly runtime for Stage 3 (sc1.scm).")
            (pl "; GENERATED by bootstrap/gen-sc1-runtime.scm -- edit the generator.")
            (pl "; Provides (RuntimeCode rest)/(RuntimeData rest) macros plus the")
            (pl "; DObj/MovRIObj directives, all consumed by compiled sc1 output.")
            (pl "")
            (pl "; Extra directives: object-pointer constants (label address + 2).")
            (pl "(Size (DObj l)) (Small 4)")
            (pl "(Pass2 (Ins (DObj l) rest) pc sym) (Bytes (LEB (Add32 (VAddr (Lookup l sym)) (Small 2))) (Pass2 rest (Add32 pc (Small 4)) sym))")
            (pl "(Size (MovRIObj r l)) (Small 5)")
            (pl "(Pass2 (Ins (MovRIObj r l) rest) pc sym) (Bytes (MovIB r) (LEB (Add32 (VAddr (Lookup l sym)) (Small 2))) (Pass2 rest (Add32 pc (Small 5)) sym))")
            (pl "")
            (emit-macro "RuntimeCode" "RTC" cc)
            (pl "")
            (emit-macro "RuntimeData" "RTD" dd))))))

(main)
