; gen-rsc-runtime.scm -- dialect (rsc) reimplementation of
; tools/generate_rsc_runtime.py.  Emits bootstrap/rsc-runtime.qf1 (default) or
; bootstrap/asm-runtime.flat (with --flat), BYTE-IDENTICAL to the Python.
;
; Build/run like any rsc program:
;   cat rsc-prelude.scm gen-rsc-runtime.scm | rscA.elf > g.qfasm
;   asm.elf asm-runtime.flat < g.qfasm > g.elf
;   ./g.elf           > rsc-runtime.qf1
;   ./g.elf --flat    > asm-runtime.flat

; ---------------------------------------------------------------------------
; Number formatting: x8 (big-endian 8 hex digits) and imm (Small or X8).
; ---------------------------------------------------------------------------
(define (k n) (w32-from-fixnum n))
(define wm1 (w32-not (k 0)))
(define w16 (k 16))
(define hexdigits "0123456789ABCDEF")
(define (hexU n) (string (string-ref hexdigits n)))
(define (nib w sh) (hexU (w32->fixnum (w32-and (w32-shr w sh) (k 15)))))
(define (x8-str w)
  (string-append "(X8 "
    (nib w 28) " " (nib w 24) " " (nib w 20) " " (nib w 16) " "
    (nib w 12) " " (nib w 8) " " (nib w 4) " " (nib w 0) ")"))
(define (imm-str w)
  (if (w32-ult? w w16)
      (string-append "(Small " (hexU (w32->fixnum w)) ")")
      (x8-str w)))

; ---------------------------------------------------------------------------
; Value constants.
; ---------------------------------------------------------------------------
(define NIL 3)      (define TRUE 19)   (define FALSE 35)
(define EOFV 51)    (define UNSPEC 67)

; ---------------------------------------------------------------------------
; C / D accumulators.  cur selects which list I appends to.
; ---------------------------------------------------------------------------
(define c-rev '())
(define d-rev '())
(define cur 'c)
(define (set-cur! x) (set! cur x))
(define (I s)
  (if (eq? cur 'c) (set! c-rev (cons s c-rev)) (set! d-rev (cons s d-rev))))
(define (L name) (I (string-append "(Label " name ")")))
(define (PL name) (begin (I "(Align8)") (L name)))
(define (MOVRI r w) (I (string-append "(MovRI " r " " (imm-str w) ")")))
(define (CMPEAX w) (I (string-append "(CmpEaxI32 " (imm-str w) ")")))
(define (call t) (I (string-append "(Call " t ")")))
(define (gv name) (string-append "(GV " name ")"))
(define (ret-bool p)
  (begin
    (L (string-append "(" p " T)")) (MOVRI "EAX" (k TRUE)) (I "(Ret)")
    (L (string-append "(" p " F)")) (MOVRI "EAX" (k FALSE)) (I "(Ret)")))
(define (cmp-prim label p jcc)
  (begin
    (PL label)
    (I "(MovRM ECX EAX)") (I "(MovRMD EAX EAX 04)") (I "(MovRM EAX EAX)")
    (I "(CmpRR ECX EAX)")
    (I (string-append "(" jcc " (" p " T))"))
    (I (string-append "(JmpS (" p " F))"))
    (ret-bool p)))

; w32 helper emitters (P1 Part A).
(define (w32-load2)
  (begin
    (I "(MovRMD ECX EAX 04)")
    (I "(MovRM ECX ECX)")
    (I "(MovRM EAX EAX)")
    (I "(MovRMD EAX EAX 02)")
    (I "(MovRMD ECX ECX 02)")))
(define (w32-binop label opins)
  (begin
    (PL label)
    (w32-load2)
    (I opins)
    (I "(MovRR ECX EAX)")
    (I "(Jmp32 MakeW32)")))
(define (w32-shift label shins prefix)
  (begin
    (PL label)
    (I "(MovRMD ECX EAX 04)")
    (I "(MovRM ECX ECX)")
    (I "(MovRM EAX EAX)")
    (I "(MovRMD EAX EAX 02)")
    (I "(SarI8 ECX 02)")
    (L (string-append "(" prefix " 1)"))
    (I "(TestRR ECX ECX)")
    (I (string-append "(Jz (" prefix " 2))"))
    (I shins)
    (I "(DecR ECX)")
    (I (string-append "(JmpS (" prefix " 1))"))
    (L (string-append "(" prefix " 2)"))
    (I "(MovRR ECX EAX)")
    (I "(Jmp32 MakeW32)")))
(define (w32-cmp label jcc prefix)
  (begin
    (PL label)
    (w32-load2)
    (I "(CmpRR EAX ECX)")
    (I (string-append "(" jcc " (" prefix " T))"))
    (I (string-append "(JmpS (" prefix " F))"))
    (ret-bool prefix)))

; PRIMS: (scheme-name . code-label)
(define PRIMS
  (list
    (cons "cons" "PrCons") (cons "car" "PrCar") (cons "cdr" "PrCdr")
    (cons "set-car!" "PrSetCar") (cons "set-cdr!" "PrSetCdr")
    (cons "pair?" "PrPairQ") (cons "null?" "PrNullQ")
    (cons "eq?" "PrEqQ") (cons "eqv?" "PrEqQ")
    (cons "symbol?" "PrSymQ") (cons "number?" "PrNumQ")
    (cons "string?" "PrStrQ") (cons "char?" "PrCharQ")
    (cons "procedure?" "PrProcQ") (cons "boolean?" "PrBoolQ")
    (cons "not" "PrNot")
    (cons "+" "PrAdd") (cons "-" "PrSub") (cons "*" "PrMul")
    (cons "quotient" "PrQuot") (cons "remainder" "PrRem")
    (cons "=" "PrNumEq") (cons "<" "PrLt") (cons ">" "PrGt")
    (cons "<=" "PrLe") (cons ">=" "PrGe")
    (cons "display" "PrDisplay") (cons "write" "PrWrite")
    (cons "newline" "PrNewline")
    (cons "read-char" "PrReadChar") (cons "peek-char" "PrPeekChar")
    (cons "eof-object?" "PrEofQ")
    (cons "char->integer" "PrCharInt") (cons "integer->char" "PrIntChar")
    (cons "string-length" "PrStrLen") (cons "string-ref" "PrStrRef")
    (cons "string->symbol" "PrStrSym") (cons "symbol->string" "PrSymStr")
    (cons "list->string" "PrListStr")
    (cons "make-string" "PrMakeStr") (cons "string-set!" "PrStrSet")
    (cons "apply" "PrApply")
    (cons "make-vector" "PrMakeVec") (cons "vector" "PrVector")
    (cons "vector-ref" "PrVecRef") (cons "vector-set!" "PrVecSet")
    (cons "vector-length" "PrVecLen") (cons "vector?" "PrVecQ")
    (cons "vector->list" "PrVecList") (cons "list->vector" "PrListVec")
    (cons "error" "PrError") (cons "exit" "PrExit")
    ; P1 Part A: w32 values + raw vector words.
    (cons "w32-from-fixnum" "PrW32FromFix") (cons "w32->fixnum" "PrW32ToFix")
    (cons "w32?" "PrW32Q")
    (cons "w32-add" "PrW32Add") (cons "w32-sub" "PrW32Sub")
    (cons "w32-mul" "PrW32Mul")
    (cons "w32-quot" "PrW32Quot") (cons "w32-rem" "PrW32Rem")
    (cons "w32-uquot" "PrW32UQuot") (cons "w32-urem" "PrW32URem")
    (cons "w32-and" "PrW32And") (cons "w32-or" "PrW32Or")
    (cons "w32-xor" "PrW32Xor") (cons "w32-not" "PrW32Not")
    (cons "w32-shl" "PrW32Shl") (cons "w32-shr" "PrW32Shr")
    (cons "w32-sar" "PrW32Sar")
    (cons "w32-eq?" "PrW32EqQ") (cons "w32-lt?" "PrW32LtQ")
    (cons "w32-ult?" "PrW32UltQ")
    (cons "vec-raw-ref" "PrVecRawRef") (cons "vec-raw-set!" "PrVecRawSet")
    ; P1 Part B: syscalls + process environment.
    (cons "getenv" "PrGetenv") (cons "command-line" "PrCommandLine")
    (cons "sys-open" "PrSysOpen") (cons "sys-close" "PrSysClose")
    (cons "sys-read" "PrSysRead") (cons "sys-write" "PrSysWrite")
    ; P1 Part C: host-heap reclamation.
    (cons "host-heap-mark" "PrHostHeapMark")
    (cons "host-heap-reset!" "PrHostHeapReset")))

; ---------------------------------------------------------------------------
; CODE
; ---------------------------------------------------------------------------
(define (build-code)
  (set-cur! 'c)
  ; HeapInit
  (L "HeapInit")
  (I "(MovRR EAX ESP)")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovMemLR GArgc ECX)")
  (I "(AddI8 EAX 08)")
  (I "(MovMemLR GArgv EAX)")
  (I "(IncR ECX)")
  (I "(ShlI8 ECX 02)")
  (I "(AddRR EAX ECX)")
  (I "(MovMemLR GEnvp EAX)")
  (I "(MovRILabel EAX CodeEnd)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GCellFree EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 1) 29)) ")"))   ; 0x20000000
  (I "(MovMemLR GByteFree EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 1) 30)) ")"))   ; 0x40000000
  (I "(MovMemLR GReadBuf EAX)")
  (I "(MovMemLR GInPtr EAX)")
  (I "(MovMemLR GInEnd EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 1) 24)) ")"))   ; 0x01000000
  (I "(MovMemLR GTokBuf EAX)")
  (I "(MovRR EBX EAX)")
  (I (string-append "(AddI32 EBX " (x8-str (w32-shl (k 1) 24)) ")"))   ; 0x01000000
  (MOVRI "EAX" (k 45))
  (I "(Int 80)")
  (I "(Ret)")
  ; InitPrims
  (L "InitPrims")
  (for-each
    (lambda (p)
      (begin
        (I (string-append "(MovRILabel EAX " (cdr p) ")"))
        (MOVRI "ECX" (k NIL))
        (call "Cons")
        (I "(OrI8 EAX 02)")
        (MOVRI "ECX" (k 1))
        (call "Cons")
        (I "(OrI8 EAX 02)")
        (I (string-append "(MovMemLR " (gv (car p)) " EAX)"))))
    PRIMS)
  (I "(Ret)")
  ; Cons
  (L "Cons")
  (I "(PushR EDX)")
  (I "(MovRMemL EDX GCellFree)")
  (I "(MovMR EDX EAX)")
  (I "(MovMDR EDX 04 ECX)")
  (I "(MovRR EAX EDX)")
  (I "(AddI8 EDX 08)")
  (I "(MovMemLR GCellFree EDX)")
  (I "(PopR EDX)")
  (I "(Ret)")
  ; AllocObj
  (L "AllocObj")
  (I "(PushR EDX)")
  (I "(MovRMemL EDI GByteFree)")
  (I "(PushR EDI)")
  (I "(MovRR ESI EAX)")
  (I "(PushR ECX)")
  (I "(RepMovsb)")
  (I "(PopR ECX)")
  (I "(MovRR EAX EDI)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GByteFree EAX)")
  (I "(PopR EAX)")
  (I "(PopR EDX)")
  (I "(OrRR EAX EDX)")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")
  ; ReadCh
  (L "ReadCh")
  (I "(MovRMemL EAX GPeek)")
  (CMPEAX wm1)
  (I "(Jz (RC 1))")
  (I "(PushR ECX)")
  (MOVRI "ECX" wm1)
  (I "(MovMemLR GPeek ECX)")
  (I "(PopR ECX)")
  (I "(Ret)")
  (L "(RC 1)")
  (I "(PushR ECX)")
  (I "(MovRMemL EAX GInPtr)")
  (I "(MovRMemL ECX GInEnd)")
  (I "(CmpRR EAX ECX)")
  (I "(Jnz (RC 3))")
  (I "(PushR EBX)")
  (I "(PushR EDX)")
  (MOVRI "EAX" (k 3))
  (I "(XorRR EBX EBX)")
  (I "(MovRMemL ECX GReadBuf)")
  (MOVRI "EDX" (k 16777216))
  (I "(Int 80)")
  (I "(TestRR EAX EAX)")
  (I "(Jg (RC 2))")
  (I "(PopR EDX)")
  (I "(PopR EBX)")
  (I "(PopR ECX)")
  (MOVRI "EAX" wm1)
  (I "(Ret)")
  (L "(RC 2)")
  (I "(MovRMemL ECX GReadBuf)")
  (I "(MovMemLR GInPtr ECX)")
  (I "(AddRR ECX EAX)")
  (I "(MovMemLR GInEnd ECX)")
  (I "(PopR EDX)")
  (I "(PopR EBX)")
  (I "(MovRMemL EAX GInPtr)")
  (L "(RC 3)")
  (I "(MovRR ECX EAX)")
  (I "(MovzxRMb EAX ECX)")
  (I "(IncR ECX)")
  (I "(MovMemLR GInPtr ECX)")
  (I "(PopR ECX)")
  (I "(Ret)")
  ; PeekCh
  (L "PeekCh")
  (call "ReadCh")
  (I "(MovMemLR GPeek EAX)")
  (I "(Ret)")
  ; Emit
  (L "Emit")
  (I "(PushR EBX)")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (I "(MovRILabel ECX WriteChBuf)")
  (I "(MovbMR ECX EAX)")
  (MOVRI "EAX" (k 4))
  (MOVRI "EBX" (k 1))
  (MOVRI "EDX" (k 1))
  (I "(Int 80)")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(PopR EBX)")
  (I "(Ret)")
  ; PrintRaw
  (L "PrintRaw")
  (MOVRI "EAX" (k 4))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")
  (I "(Ret)")
  ; ErrApply
  (L "ErrApply")
  (MOVRI "EAX" (k 33))
  (call "Emit")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")
  ; Intern
  (L "Intern")
  (I "(MovRMemL EDX GObList)")
  (L "(IN 1)")
  (I "(TestRI8 EDX 03)")
  (I "(Jz (IN 2))")
  (I "(XorRR EDX EDX)")
  (call "AllocObj")
  (I "(PushR EAX)")
  (I "(MovRMemL ECX GObList)")
  (call "Cons")
  (I "(MovMemLR GObList EAX)")
  (I "(PopR EAX)")
  (I "(Ret)")
  (L "(IN 2)")
  (I "(MovRM EBX EDX)")
  (I "(MovRR EDI EBX)")
  (I "(SubI8 EDI 02)")
  (I "(MovRMD ESI EDI 04)")
  (I "(SarI8 ESI 02)")
  (I "(CmpRR ESI ECX)")
  (I "(Jnz (IN 3))")
  (I "(MovRM ESI EDI)")
  (I "(MovRR EDI EAX)")
  (I "(PushR ECX)")
  (I "(RepeCmpsb)")
  (I "(PopR ECX)")
  (I "(Jnz (IN 3))")
  (I "(MovRR EAX EBX)")
  (I "(Ret)")
  (L "(IN 3)")
  (I "(MovRMD EDX EDX 04)")
  (I "(JmpS (IN 1))")
  ; --- Primitives ---
  (PL "PrCons")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRM ECX ECX)")
  (I "(MovRM EAX EAX)")
  (I "(Jmp32 Cons)")

  (PL "PrCar")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (CAR 1))")
  (I "(Jmp32 ErrApply)")
  (L "(CAR 1)")
  (I "(MovRM EAX EAX)")
  (I "(Ret)")

  (PL "PrCdr")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (CDR 1))")
  (I "(Jmp32 ErrApply)")
  (L "(CDR 1)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")

  (PL "PrSetCar")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(MovMR ECX EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrSetCdr")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(MovMDR ECX 04 EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrPairQ")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (PQ T))")
  (I "(JmpS (PQ F))")
  (ret-bool "PQ")

  (PL "PrNullQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k NIL))
  (I "(Jz (NQ T))")
  (I "(JmpS (NQ F))")
  (ret-bool "NQ")

  (PL "PrEqQ")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(CmpRR EAX ECX)")
  (I "(Jz (EQ T))")
  (I "(JmpS (EQ F))")
  (ret-bool "EQ")

  (PL "PrSymQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (SYQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 07)")
  (I "(Jz (SYQ T))")
  (I "(JmpS (SYQ F))")
  (ret-bool "SYQ")

  (PL "PrNumQ")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 01)")
  (I "(Jz (NUQ F))")
  (I "(TestRI8 EAX 02)")
  (I "(Jz (NUQ T))")
  (I "(JmpS (NUQ F))")
  (ret-bool "NUQ")

  (PL "PrStrQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (STQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 01)")
  (I "(Jz (STQ T))")
  (I "(JmpS (STQ F))")
  (ret-bool "STQ")

  (PL "PrCharQ")
  (I "(MovRM EAX EAX)")
  (I (string-append "(AndI32 EAX " (x8-str (k 255)) ")"))
  (I "(CmpI8 EAX 53)")
  (I "(Jz (CHQ T))")
  (I "(JmpS (CHQ F))")
  (ret-bool "CHQ")

  (PL "PrProcQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (PCQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 02)")
  (I "(Jz (PCQ T))")
  (I "(CmpI8 EAX 03)")
  (I "(Jz (PCQ T))")
  (I "(JmpS (PCQ F))")
  (ret-bool "PCQ")

  (PL "PrBoolQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k TRUE))
  (I "(Jz (BQ T))")
  (CMPEAX (k FALSE))
  (I "(Jz (BQ T))")
  (I "(JmpS (BQ F))")
  (ret-bool "BQ")

  (PL "PrNot")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k FALSE))
  (I "(Jz (NO T))")
  (I "(JmpS (NO F))")
  (ret-bool "NO")

  (PL "PrAdd")
  (MOVRI "ECX" (k 1))
  (L "(AD 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (AD 2))")
  (I "(MovRM EDX EAX)")
  (I "(AddRR ECX EDX)")
  (I "(DecR ECX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (AD 1))")
  (L "(AD 2)")
  (I "(MovRR EAX ECX)")
  (I "(Ret)")

  (PL "PrSub")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (SB 1))")
  (MOVRI "EAX" (k 2))
  (I "(SubRR EAX ECX)")
  (I "(Ret)")
  (L "(SB 1)")
  (I "(MovRM EDX EAX)")
  (I "(SubRR ECX EDX)")
  (I "(IncR ECX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (SB 1))")
  (I "(MovRR EAX ECX)")
  (I "(Ret)")

  (PL "PrMul")
  (MOVRI "ECX" (k 1))
  (L "(MU 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (MU 2))")
  (I "(MovRM EDX EAX)")
  (I "(SarI8 EDX 02)")
  (I "(IMulRR ECX EDX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (MU 1))")
  (L "(MU 2)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrQuot")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EBX EAX)")
  (I "(MovRR EAX ECX)")
  (I "(SarI8 EAX 02)")
  (I "(SarI8 EBX 02)")
  (I "(Cdq)")
  (I "(IDivR EBX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrRem")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EBX EAX)")
  (I "(MovRR EAX ECX)")
  (I "(SarI8 EAX 02)")
  (I "(SarI8 EBX 02)")
  (I "(Cdq)")
  (I "(IDivR EBX)")
  (I "(MovRR EAX EDX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (cmp-prim "PrNumEq" "NE" "Jz")
  (cmp-prim "PrLt" "LTP" "Jl")
  (cmp-prim "PrGt" "GTP" "Jg")
  (cmp-prim "PrLe" "LEP" "Jle")
  (cmp-prim "PrGe" "GEP" "Jge")

  (PL "PrDisplay")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (DS 2))")
  (I "(MovRR EDX EAX)")
  (I "(SubI8 EDX 02)")
  (I "(MovRM ECX EDX)")
  (I "(MovRR EBX ECX)")
  (I "(AndI8 EBX 07)")
  (I "(CmpI8 EBX 01)")
  (I "(Jnz (DS 3))")
  (I "(AndI8 ECX F8)")
  (I "(MovRMD EDX EDX 04)")
  (I "(SarI8 EDX 02)")
  (call "PrintRaw")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(DS 2)")
  (I "(CmpI8 ECX 03)")
  (I "(Jnz (DS 3))")
  (I "(MovRR EDX EAX)")
  (I (string-append "(AndI32 EDX " (x8-str (k 255)) ")"))
  (I "(CmpI8 EDX 53)")
  (I "(Jnz (DS 3))")
  (I "(ShrI8 EAX 08)")
  (call "Emit")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(DS 3)")
  (call "Print")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrWrite")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrNewline")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrReadChar")
  (call "ReadCh")
  (CMPEAX wm1)
  (I "(Jz (RDC 1))")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")
  (L "(RDC 1)")
  (MOVRI "EAX" (k EOFV))
  (I "(Ret)")

  (PL "PrPeekChar")
  (call "PeekCh")
  (CMPEAX wm1)
  (I "(Jz (PKC 1))")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")
  (L "(PKC 1)")
  (MOVRI "EAX" (k EOFV))
  (I "(Ret)")

  (PL "PrEofQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k EOFV))
  (I "(Jz (EFQ T))")
  (I "(JmpS (EFQ F))")
  (ret-bool "EFQ")

  (PL "PrCharInt")
  (I "(MovRM EAX EAX)")
  (I "(ShrI8 EAX 08)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrIntChar")
  (I "(MovRM EAX EAX)")
  (I "(SarI8 EAX 02)")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")

  (PL "PrStrLen")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")

  (PL "PrStrRef")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EDX EAX)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM EBX ECX)")
  (I "(AndI8 EBX F8)")
  (I "(SarI8 EDX 02)")
  (I "(AddRR EBX EDX)")
  (I "(MovzxRMb EAX EBX)")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")

  (PL "PrStrSym")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRR EDX EAX)")
  (I "(MovRM EAX EDX)")
  (I "(AndI8 EAX F8)")
  (I "(MovRMD ECX EDX 04)")
  (I "(SarI8 ECX 02)")
  (I "(Jmp32 Intern)")

  (PL "PrSymStr")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EDX EAX)")
  (I "(OrI8 EDX 01)")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRR EAX EDX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (PL "PrListStr")
  (I "(MovRM EDX EAX)")
  (I "(MovRMemL EDI GTokBuf)")
  (L "(LS 1)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (LS 2))")
  (I "(MovRM EAX EDX)")
  (I "(ShrI8 EAX 08)")
  (I "(MovbMR EDI EAX)")
  (I "(IncR EDI)")
  (I "(MovRMD EDX EDX 04)")
  (I "(JmpS (LS 1))")
  (L "(LS 2)")
  (I "(MovRMemL EAX GTokBuf)")
  (I "(MovRR ECX EDI)")
  (I "(SubRR ECX EAX)")
  (MOVRI "EDX" (k 1))
  (I "(Jmp32 AllocObj)")

  ; --- make-string / string-set! (mutable byte buffers) ---
  (PL "PrMakeStr")
  (I "(MovRM ECX EAX)")
  (I "(SarI8 ECX 02)")
  (I "(MovRMD EDX EAX 04)")
  (I "(TestRI8 EDX 03)")
  (I "(Jz (MS 0))")
  (MOVRI "EBX" (k 32))
  (I "(JmpS (MS 1))")
  (L "(MS 0)")
  (I "(MovRM EBX EDX)")
  (I "(ShrI8 EBX 08)")
  (L "(MS 1)")
  (I "(MovRMemL EDI GByteFree)")
  (I "(PushR EDI)")
  (I "(PushR ECX)")
  (L "(MS 2)")
  (I "(TestRR ECX ECX)")
  (I "(Jz (MS 3))")
  (I "(MovbMR EDI EBX)")
  (I "(IncR EDI)")
  (I "(DecR ECX)")
  (I "(JmpS (MS 2))")
  (L "(MS 3)")
  (I "(MovRR EAX EDI)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GByteFree EAX)")
  (I "(PopR ECX)")
  (I "(PopR EAX)")
  (I "(OrI8 EAX 01)")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (PL "PrStrSet")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EDX EAX)")
  (I "(SarI8 EDX 02)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(ShrI8 EAX 08)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM ECX ECX)")
  (I "(AndI8 ECX F8)")
  (I "(AddRR ECX EDX)")
  (I "(MovbMR ECX EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  ; --- apply ---
  (L "AppendArgs")
  (I "(MovRMD ECX EAX 04)")
  (I "(TestRI8 ECX 03)")
  (I "(Jnz (APA 1))")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (call "AppendArgs")
  (I "(PopR ECX)")
  (I "(MovRR EDX EAX)")
  (I "(MovRM EAX ECX)")
  (I "(MovRR ECX EDX)")
  (I "(Jmp32 Cons)")
  (L "(APA 1)")
  (I "(MovRM EAX EAX)")
  (I "(Ret)")

  (PL "PrApply")
  (I "(MovRM EBX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (APL 1))")
  (MOVRI "EAX" (k NIL))
  (I "(JmpS (APL 2))")
  (L "(APL 1)")
  (call "AppendArgs")
  (L "(APL 2)")
  (I "(MovRR ESI EBX)")
  (I "(SubI8 ESI 02)")
  (I "(MovRM ESI ESI)")
  (I "(AndI8 ESI F8)")
  (I "(MovRMD EDI ESI 04)")
  (I "(MovRM ESI ESI)")
  (I "(JmpR ESI)")

  ; --- vectors ---
  (PL "PrMakeVec")
  (I "(MovRM ECX EAX)")
  (I "(SarI8 ECX 02)")
  (I "(MovRMD EDX EAX 04)")
  (I "(TestRI8 EDX 03)")
  (I "(Jz (MV 0))")
  (MOVRI "EBX" (k FALSE))
  (I "(JmpS (MV 1))")
  (L "(MV 0)")
  (I "(MovRM EBX EDX)")
  (L "(MV 1)")
  (I "(MovRMemL EDI GByteFree)")
  (I "(PushR EDI)")
  (I "(PushR ECX)")
  (L "(MV 2)")
  (I "(TestRR ECX ECX)")
  (I "(Jz (MV 3))")
  (I "(MovMR EDI EBX)")
  (I "(AddI8 EDI 04)")
  (I "(DecR ECX)")
  (I "(JmpS (MV 2))")
  (L "(MV 3)")
  (I "(MovRR EAX EDI)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GByteFree EAX)")
  (I "(PopR ECX)")
  (I "(PopR EAX)")
  (I "(OrI8 EAX 04)")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (PL "PrVector")
  (I "(MovRR EDX EAX)")
  (I "(Jmp32 VecFromList)")

  (PL "PrListVec")
  (I "(MovRM EDX EAX)")
  (I "(Jmp32 VecFromList)")

  (L "VecFromList")
  (I "(XorRR ECX ECX)")
  (I "(MovRR EBX EDX)")
  (L "(LV 1)")
  (I "(TestRI8 EBX 03)")
  (I "(Jnz (LV 2))")
  (I "(IncR ECX)")
  (I "(MovRMD EBX EBX 04)")
  (I "(JmpS (LV 1))")
  (L "(LV 2)")
  (I "(MovRMemL EDI GByteFree)")
  (I "(PushR EDI)")
  (I "(PushR ECX)")
  (I "(MovRR EBX EDX)")
  (L "(LV 3)")
  (I "(TestRI8 EBX 03)")
  (I "(Jnz (LV 4))")
  (I "(MovRM EAX EBX)")
  (I "(MovMR EDI EAX)")
  (I "(AddI8 EDI 04)")
  (I "(MovRMD EBX EBX 04)")
  (I "(JmpS (LV 3))")
  (L "(LV 4)")
  (I "(MovRR EAX EDI)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GByteFree EAX)")
  (I "(PopR ECX)")
  (I "(PopR EAX)")
  (I "(OrI8 EAX 04)")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (PL "PrVecRef")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX FC)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM ECX ECX)")
  (I "(AndI8 ECX F8)")
  (I "(AddRR ECX EAX)")
  (I "(MovRM EAX ECX)")
  (I "(Ret)")

  (PL "PrVecSet")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EDX EAX)")
  (I "(AndI8 EDX FC)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM ECX ECX)")
  (I "(AndI8 ECX F8)")
  (I "(AddRR ECX EDX)")
  (I "(MovMR ECX EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrVecLen")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")

  (PL "PrVecQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (VQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 04)")
  (I "(Jz (VQ T))")
  (I "(JmpS (VQ F))")
  (ret-bool "VQ")

  (PL "PrVecList")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRMD EDX EAX 04)")
  (I "(SarI8 EDX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX F8)")
  (I "(MovRR EBX EAX)")
  (MOVRI "EAX" (k NIL))
  (L "(VL2 1)")
  (I "(TestRR EDX EDX)")
  (I "(Jz (VL2 2))")
  (I "(DecR EDX)")
  (I "(MovRR ECX EDX)")
  (I "(ShlI8 ECX 02)")
  (I "(AddRR ECX EBX)")
  (I "(MovRM ECX ECX)")
  (I "(XchgRR EAX ECX)")
  (call "Cons")
  (I "(JmpS (VL2 1))")
  (L "(VL2 2)")
  (I "(Ret)")

  (PL "PrError")
  (L "(ER 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (ER 2))")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (ER 1))")
  (L "(ER 2)")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")

  (PL "PrExit")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (EX 1))")
  (I "(MovRM EBX EAX)")
  (I "(SarI8 EBX 02)")
  (MOVRI "EAX" (k 1))
  (I "(Int 80)")
  (L "(EX 1)")
  (MOVRI "EAX" (k 1))
  (I "(XorRR EBX EBX)")
  (I "(Int 80)")

  ; --- Printer ---
  (L "Print")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 01)")
  (I "(Jnz (PR 1))")
  (I "(Jmp32 PrintNum)")
  (L "(PR 1)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (PR 2))")
  (I "(Jmp32 PrintObj)")
  (L "(PR 2)")
  (I "(CmpI8 ECX 03)")
  (I "(Jnz (PR 3))")
  (I "(Jmp32 PrintImm)")
  (L "(PR 3)")
  (I "(Jmp32 PrintPair)")

  (L "PrintNum")
  (I "(SarI8 EAX 02)")
  (I "(TestRR EAX EAX)")
  (I "(Jns (PN 1))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 45))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(NegR EAX)")
  (L "(PN 1)")
  (I "(XorRR EBX EBX)")
  (MOVRI "ECX" (k 10))
  (L "(PN 2)")
  (I "(XorRR EDX EDX)")
  (I "(DivR ECX)")
  (I "(AddI8 EDX 30)")
  (I "(PushR EDX)")
  (I "(IncR EBX)")
  (I "(TestRR EAX EAX)")
  (I "(Jnz (PN 2))")
  (L "(PN 3)")
  (I "(PopR EAX)")
  (call "Emit")
  (I "(DecR EBX)")
  (I "(Jnz (PN 3))")
  (I "(Ret)")

  (L "PrintPair")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 40))
  (call "Emit")
  (I "(PopR EAX)")
  (L "(PP 1)")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (I "(PopR EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (PP 2))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(Jmp32 (PP 1))")
  (L "(PP 2)")
  (CMPEAX (k NIL))
  (I "(Jnz (PP 3))")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")
  (L "(PP 3)")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (MOVRI "EAX" (k 46))
  (call "Emit")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (call "Print")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")

  (L "PrintObj")
  (I "(SubI8 EAX 02)")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EDX EAX 04)")
  (I "(SarI8 EDX 02)")
  (I "(MovRR EBX ECX)")
  (I "(AndI8 EBX 07)")
  (I "(TestRR EBX EBX)")
  (I "(Jnz (PO 1))")
  (I "(Jmp32 PrintRaw)")
  (L "(PO 1)")
  (I "(CmpI8 EBX 01)")
  (I "(Jz (PO 2))")
  (I "(CmpI8 EBX 04)")
  (I "(Jz (PO 3))")
  (MOVRI "EAX" (k 63))
  (I "(Jmp32 Emit)")
  (L "(PO 2)")
  (MOVRI "EAX" (k 34))
  (call "Emit")
  (I "(AndI8 ECX F8)")
  (call "PrintRaw")
  (MOVRI "EAX" (k 34))
  (I "(Jmp32 Emit)")
  ; Vector: #(elt elt ...). ECX = car (buffer|4), EDX = element count.
  (L "(PO 3)")
  (I "(AndI8 ECX F8)")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 40))
  (call "Emit")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(TestRR EDX EDX)")
  (I "(Jz32 (PO 6))")
  (L "(PO 4)")
  (I "(MovRM EAX ECX)")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (call "Print")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(AddI8 ECX 04)")
  (I "(DecR EDX)")
  (I "(Jz32 (PO 6))")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(Jmp32 (PO 4))")
  (L "(PO 6)")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")

  (L "PrintImm")
  (CMPEAX (k NIL))
  (I "(Jnz (PI 1))")
  (MOVRI "EAX" (k 40))
  (call "Emit")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")
  (L "(PI 1)")
  (CMPEAX (k TRUE))
  (I "(Jnz (PI 2))")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 116))
  (I "(Jmp32 Emit)")
  (L "(PI 2)")
  (CMPEAX (k FALSE))
  (I "(Jnz (PI 3))")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 102))
  (I "(Jmp32 Emit)")
  (L "(PI 3)")
  (I "(MovRR ECX EAX)")
  (I (string-append "(AndI32 ECX " (x8-str (k 255)) ")"))
  (I "(CmpI8 ECX 53)")
  (I "(Jnz (PI 4))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 92))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(ShrI8 EAX 08)")
  (I "(Jmp32 Emit)")
  (L "(PI 4)")
  (MOVRI "EAX" (k 63))
  (I "(Jmp32 Emit)")

  ; --- P1 PART A: w32 values ---
  (L "MakeW32")
  (MOVRI "EAX" (k 5))
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (PL "PrW32FromFix")
  (I "(MovRM EAX EAX)")
  (I "(SarI8 EAX 02)")
  (I "(MovRR ECX EAX)")
  (I "(Jmp32 MakeW32)")

  (PL "PrW32ToFix")
  (I "(MovRM EAX EAX)")
  (I "(MovRMD EAX EAX 02)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrW32Q")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (WQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 05)")
  (I "(Jz (WQ T))")
  (I "(JmpS (WQ F))")
  (ret-bool "WQ")

  (w32-binop "PrW32Add" "(AddRR EAX ECX)")
  (w32-binop "PrW32Sub" "(SubRR EAX ECX)")
  (w32-binop "PrW32Mul" "(IMulRR EAX ECX)")
  (w32-binop "PrW32And" "(AndRR EAX ECX)")
  (w32-binop "PrW32Or" "(OrRR EAX ECX)")
  (w32-binop "PrW32Xor" "(XorRR EAX ECX)")

  (PL "PrW32Not")
  (I "(MovRM EAX EAX)")
  (I "(MovRMD EAX EAX 02)")
  (I "(NotR EAX)")
  (I "(MovRR ECX EAX)")
  (I "(Jmp32 MakeW32)")

  (PL "PrW32Quot")
  (w32-load2)
  (I "(Cdq)")
  (I "(IDivR ECX)")
  (I "(MovRR ECX EAX)")
  (I "(Jmp32 MakeW32)")

  (PL "PrW32Rem")
  (w32-load2)
  (I "(Cdq)")
  (I "(IDivR ECX)")
  (I "(MovRR ECX EDX)")
  (I "(Jmp32 MakeW32)")

  (PL "PrW32UQuot")
  (w32-load2)
  (I "(XorRR EDX EDX)")
  (I "(DivR ECX)")
  (I "(MovRR ECX EAX)")
  (I "(Jmp32 MakeW32)")

  (PL "PrW32URem")
  (w32-load2)
  (I "(XorRR EDX EDX)")
  (I "(DivR ECX)")
  (I "(MovRR ECX EDX)")
  (I "(Jmp32 MakeW32)")

  (w32-shift "PrW32Shl" "(ShlI8 EAX 01)" "WSHL")
  (w32-shift "PrW32Shr" "(ShrI8 EAX 01)" "WSHR")
  (w32-shift "PrW32Sar" "(SarI8 EAX 01)" "WSAR")

  (w32-cmp "PrW32EqQ" "Jz" "WEQ")
  (w32-cmp "PrW32LtQ" "Jl" "WLT")
  (w32-cmp "PrW32UltQ" "Jb" "WULT")

  (PL "PrVecRawRef")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRM ECX ECX)")
  (I "(AndI8 ECX FC)")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX F8)")
  (I "(AddRR EAX ECX)")
  (I "(MovRM ECX EAX)")
  (I "(Jmp32 MakeW32)")

  (PL "PrVecRawSet")
  (I "(MovRM ECX EAX)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM ECX ECX)")
  (I "(AndI8 ECX F8)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EDX EAX)")
  (I "(AndI8 EDX FC)")
  (I "(AddRR ECX EDX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(MovRMD EAX EAX 02)")
  (I "(MovMR ECX EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  ; --- P1 PART B: syscalls + process environment ---
  (L "CStrToStr")
  (I "(MovRR EDX EAX)")
  (L "(CS 1)")
  (I "(MovzxRMb ECX EDX)")
  (I "(TestRR ECX ECX)")
  (I "(Jz (CS 2))")
  (I "(IncR EDX)")
  (I "(JmpS (CS 1))")
  (L "(CS 2)")
  (I "(MovRR ECX EDX)")
  (I "(SubRR ECX EAX)")
  (MOVRI "EDX" (k 1))
  (I "(Jmp32 AllocObj)")

  (PL "PrGetenv")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRM ESI EAX)")
  (I "(AndI8 ESI F8)")
  (I "(MovRMD EDI EAX 04)")
  (I "(SarI8 EDI 02)")
  (I "(MovRMemL EBX GEnvp)")
  (L "(GE loop)")
  (I "(MovRM EAX EBX)")
  (I "(TestRR EAX EAX)")
  (I "(Jz32 (GE none))")
  (I "(XorRR ECX ECX)")
  (L "(GE cmp)")
  (I "(CmpRR ECX EDI)")
  (I "(Jz32 (GE checkeq))")
  (I "(MovRR EAX ESI)")
  (I "(AddRR EAX ECX)")
  (I "(MovzxRMb EAX EAX)")
  (I "(MovRM EDX EBX)")
  (I "(AddRR EDX ECX)")
  (I "(MovzxRMb EDX EDX)")
  (I "(CmpRR EAX EDX)")
  (I "(Jnz32 (GE next))")
  (I "(IncR ECX)")
  (I "(JmpS (GE cmp))")
  (L "(GE checkeq)")
  (I "(MovRM EDX EBX)")
  (I "(AddRR EDX EDI)")
  (I "(MovzxRMb EAX EDX)")
  (I "(CmpI8 EAX 3D)")
  (I "(Jnz32 (GE next))")
  (I "(MovRM EAX EBX)")
  (I "(AddRR EAX EDI)")
  (I "(IncR EAX)")
  (I "(Jmp32 CStrToStr)")
  (L "(GE next)")
  (I "(AddI8 EBX 04)")
  (I "(Jmp32 (GE loop))")
  (L "(GE none)")
  (MOVRI "EAX" (k FALSE))
  (I "(Ret)")

  (L "BuildArgv")
  (I "(MovRMemL ECX GArgc)")
  (I "(CmpRR EAX ECX)")
  (I "(Jge32 (BA nil))")
  (I "(PushR EAX)")
  (I "(MovRMemL EDX GArgv)")
  (I "(MovRR ECX EAX)")
  (I "(ShlI8 ECX 02)")
  (I "(AddRR EDX ECX)")
  (I "(MovRM EAX EDX)")
  (I "(Call CStrToStr)")
  (I "(PopR ECX)")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(IncR EAX)")
  (I "(Call BuildArgv)")
  (I "(PopR ECX)")
  (I "(XchgRR EAX ECX)")
  (I "(Jmp32 Cons)")
  (L "(BA nil)")
  (MOVRI "EAX" (k NIL))
  (I "(Ret)")

  (PL "PrCommandLine")
  (MOVRI "EAX" (k 0))
  (I "(Jmp32 BuildArgv)")

  (PL "PrSysOpen")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRM EBX ECX)")
  (I "(SarI8 EBX 02)")
  (I "(MovRMD ECX ECX 04)")
  (I "(MovRM ECX ECX)")
  (I "(SarI8 ECX 02)")
  (I "(PushR ECX)")
  (I "(PushR EBX)")
  (I "(MovRM ECX EAX)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM EDX ECX)")
  (I "(AndI8 EDX F8)")
  (I "(MovRMD ECX ECX 04)")
  (I "(SarI8 ECX 02)")
  (I "(MovRILabel EDI GPathBuf)")
  (I "(MovRR ESI EDX)")
  (I "(RepMovsb)")
  (I "(XorRR EAX EAX)")
  (I "(MovbMR EDI EAX)")
  (I "(PopR ECX)")
  (I "(PopR EDX)")
  (I "(MovRILabel EBX GPathBuf)")
  (MOVRI "EAX" (k 5))
  (I "(Int 80)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrSysClose")
  (I "(MovRM EBX EAX)")
  (I "(SarI8 EBX 02)")
  (MOVRI "EAX" (k 6))
  (I "(Int 80)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrSysRead")
  (I "(MovRM EBX EAX)")
  (I "(SarI8 EBX 02)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRM ECX EAX)")
  (I "(AndI8 ECX F8)")
  (I "(MovRMD EDX EAX 04)")
  (I "(SarI8 EDX 02)")
  (MOVRI "EAX" (k 3))
  (I "(Int 80)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrSysWrite")
  (I "(MovRM EBX EAX)")
  (I "(SarI8 EBX 02)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM ECX EAX)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM ECX ECX)")
  (I "(AndI8 ECX F8)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EDX EAX)")
  (I "(SarI8 EDX 02)")
  (MOVRI "EAX" (k 4))
  (I "(Int 80)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  ; --- P1 PART C: host-heap reclamation ---
  (PL "PrHostHeapMark")
  (I "(MovRMemL ECX GCellFree)")
  (I "(Jmp32 MakeW32)")

  (PL "PrHostHeapReset")
  (I "(MovRM EAX EAX)")
  (I "(MovRMD EAX EAX 02)")
  (I "(MovMemLR GCellFree EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)"))

; ---------------------------------------------------------------------------
; DATA
; ---------------------------------------------------------------------------
(define (n-times n thunk)
  (if (= n 0) #t (begin (thunk) (n-times (- n 1) thunk))))

(define (build-data)
  (set-cur! 'd)
  (I "(Align4)")
  (for-each
    (lambda (g)
      (begin
        (L g)
        (I (string-append "(Dd "
             (x8-str (if (string=? g "GObList") (k NIL) (k 0))) ")"))))
    (list "GCellFree" "GByteFree" "GInPtr" "GInEnd" "GObList"
          "GTokBuf" "GReadBuf"
          "GArgc" "GArgv" "GEnvp"))
  (L "GPeek")
  (I (string-append "(Dd " (x8-str wm1) ")"))
  (L "WriteChBuf")
  (I "(Db 00)")
  (I "(Align4)")
  (L "GPathBuf")
  (n-times 1024 (lambda () (I (string-append "(Dd " (x8-str (k 0)) ")"))))
  (for-each
    (lambda (p)
      (begin
        (L (gv (car p)))
        (I (string-append "(Dd " (x8-str (k 0)) ")"))))
    PRIMS)
  (I "(Align8)")
  (L "CodeEnd"))

; ---------------------------------------------------------------------------
; Emission.
; ---------------------------------------------------------------------------
(define (repeat-str s n) (if (= n 0) "" (string-append s (repeat-str s (- n 1)))))
(define (take-n lst n) (if (or (= n 0) (null? lst)) '() (cons (car lst) (take-n (cdr lst) (- n 1)))))
(define (drop-n lst n) (if (or (= n 0) (null? lst)) lst (drop-n (cdr lst) (- n 1))))
(define (pl s) (begin (display s) (newline)))

(define (emit-blocks top chain items bi)
  (if (null? items)
      #t
      (let ((blk (take-n items 24))
            (rest (drop-n items 24)))
        (begin
          (if (= bi 0)
              (pl (string-append "(Rule (" top " rest)"))
              (pl (string-append "(Rule (" chain " " (number->string bi) " rest)")))
          (for-each (lambda (ins) (pl (string-append "  (Ins " ins))) blk)
          (if (null? rest)
              (pl (string-append "  rest" (repeat-str ")" (length blk)) ")"))
              (pl (string-append "  (" chain " " (number->string (+ bi 1)) " rest)"
                    (repeat-str ")" (length blk)) ")")))
          (emit-blocks top chain rest (+ bi 1))))))

(define (emit-macro top chain items) (emit-blocks top chain items 0))

(define (emit-flat cc dd)
  (begin
    (for-each pl cc)
    (pl "RTSPLIT")
    (for-each pl dd)))

(define (has-flat)
  (let ((a (command-line)))
    (and (pair? a) (pair? (cdr a)) (string=? (cadr a) "--flat"))))

(define (main)
  (begin
    (build-code)
    (build-data)
    (let ((cc (reverse c-rev)) (dd (reverse d-rev)))
      (if (has-flat)
          (emit-flat cc dd)
          (begin
            (pl "; rsc-runtime: fixed assembly runtime for Stage 4 (rsc.scm).")
            (pl "; GENERATED by tools/generate_rsc_runtime.py -- edit the builder.")
            (pl "; Provides (RuntimeCode rest)/(RuntimeData rest) macros plus the")
            (pl "; DObj/MovRIObj directives, all consumed by compiled rsc output.")
            (pl "")
            (pl "; Extra directives: object-pointer constants (label address + 2).")
            (pl "(Size (DObj l)) (Small 4)")
            (pl "(Pass2 (Ins (DObj l) rest) pc sym) (Bytes (LEB (Add32 (VAddr (Lookup l sym)) (Small 2))) (Pass2 rest (Add32 pc (Small 4)) sym))")
            (pl "(Size (MovRIObj r l)) (Small 5)")
            (pl "(Pass2 (Ins (MovRIObj r l) rest) pc sym) (Bytes (MovIB r) (LEB (Add32 (VAddr (Lookup l sym)) (Small 2))) (Pass2 rest (Add32 pc (Small 5)) sym))")
            (pl "")
            (emit-macro "RuntimeCode" "RTC" cc)
            (pl "")
            (emit-macro "RuntimeData" "RTD" dd))))))

(main)
