; gen-scheme0.scm --- emit bootstrap/scheme0.qfasm, the Stage-2 interpreter.
;
; A dev-time generator in the rsc dialect.  scheme0 is a minimal Scheme
; interpreter -- reader, environment-passing evaluator with proper tail
; calls, printer, ~40 primitives -- written directly in qfasm macro
; assembly; this program prints that assembly.  It replaced the retired
; tools/build_scheme0.py and its output stays byte-identical to the
; committed artifact (the artifact is frozen; only this generator may be
; edited for readability).
;
; It is a FORMATTER, not a compiler: every instruction below appears in the
; artifact 1:1, in order.  What generating buys is (a) the SPECIALS/PRIMS
; tables are each walked from several places (startup interning, evaluator
; dispatch, name-string data), and one table keeps those in step, and
; (b) the (Z n) block chaining that keeps the emitted qfasm digestible by
; the seed (see emit-blocks at the bottom).
;
; Regenerate:  tools/regen.sh gen scheme0 > bootstrap/scheme0.qfasm
; Verify:      make regen-verify
;              -> "all committed generated artifacts reproduced byte-identically"
;
; Note scheme0.qfasm is the one program the native asm.elf can NOT
; assemble: it is (Z n) block macros, not a flat (Ins ...) chain.  It stays
; seed-assembled -- the bootstrap root below asm.elf.

; ---------------------------------------------------------------------------
; Number formatting: x8 (big-endian 8 hex digits) and imm (Small or X8).
; ---------------------------------------------------------------------------
; Immediates are printed as (Small d) when they fit one nybble, else as the
; full (X8 ...) spelling -- matching what qfasm's number sugar accepts.
; All 32-bit constants are built with the w32 prims: dialect fixnums stop
; at 2^30, so values like 0xFFFFFFFF need boxed words.
(define (k n) (w32-from-fixnum n))
(define wm1 (w32-not (k 0)))
(define w16 (k 16))
(define hexdigits "0123456789ABCDEF")
(define (hexU n) (string (string-ref hexdigits n)))
(define (nib w sh) (hexU (w32->fixnum (w32-and (w32-shr w sh) (k 15)))))
(define (x8-str w)
  (string-append "(X8 "
    (nib w 28) " " (nib w 24) " " (nib w 20) " " (nib w 16) " "
    (nib w 12) " " (nib w 8) " " (nib w 4) " " (nib w 0) ")"))
(define (imm-str w)
  (if (w32-ult? w w16)
      (string-append "(Small " (hexU (w32->fixnum w)) ")")
      (x8-str w)))
(define (byte-hex n) (string-append (hexU (quotient n 16)) (hexU (remainder n 16))))

; ---------------------------------------------------------------------------
; Value constants: the scheme0 object model.
; ---------------------------------------------------------------------------
; A value is a 32-bit word tagged in its low two bits:
;   00  pair pointer (8-byte cell: car at +0, cdr at +4);
;   01  fixnum, n << 2 | 1;
;   10  object pointer: a cell whose car is a payload pointer carrying a
;       SUBTYPE in its low 3 bits (0 symbol, 1 string, 2 closure, 3
;       primitive) and whose cdr is the payload length as a fixnum;
;   11  immediate: 0x03 (), 0x13 #t, 0x23 #f, 0x33 eof, 0x43 unspecified,
;       and characters as code << 8 | 0x53.
(define NIL 3)      (define TRUE 19)   (define FALSE 35)
(define EOFV 51)    (define UNSPEC 67)

; ---------------------------------------------------------------------------
; Single accumulator S.  (I s) conses onto s-rev; reverse at the end.
; ---------------------------------------------------------------------------
; Each helper pushes one qfasm instruction string.  PL is L behind an
; (Align8): a label whose ADDRESS gets tag bits or'd into it (every prim
; entry point) must be 8-byte aligned or the tag would corrupt the address.
(define s-rev '())
(define (I s) (set! s-rev (cons s s-rev)))
(define (L name) (I (string-append "(Label " name ")")))
(define (PL name) (begin (I "(Align8)") (L name)))
(define (MOVRI r w) (I (string-append "(MovRI " r " " (imm-str w) ")")))
(define (CMPEAX w) (I (string-append "(CmpEaxI32 " (imm-str w) ")")))
(define (call t) (I (string-append "(Call " t ")")))
; ret-bool: the shared (p T)/(p F) return tails every predicate jumps to.
; cmp-prim: a whole two-fixnum comparison primitive; they differ only in
; the conditional jump used (tagged fixnums compare like raw integers).
(define (ret-bool p)
  (begin
    (L (string-append "(" p " T)")) (MOVRI "EAX" (k TRUE)) (I "(Ret)")
    (L (string-append "(" p " F)")) (MOVRI "EAX" (k FALSE)) (I "(Ret)")))
(define (cmp-prim label p jcc)
  (begin
    (PL label)
    (I "(MovRM ECX EAX)") (I "(MovRMD EAX EAX 04)") (I "(MovRM EAX EAX)")
    (I "(CmpRR ECX EAX)")
    (I (string-append "(" jcc " (" p " T))"))
    (I (string-append "(JmpS (" p " F))"))
    (ret-bool p)))

; ---------------------------------------------------------------------------
; SPECIALS and PRIMS (order matters).
; ---------------------------------------------------------------------------
; SPECIALS: (global-cell name-bytes-label text).  Startup interns text and
; stores the symbol in the global cell; the evaluator compares form heads
; against those cells.  PRIMS: (scheme-name . code-label).  Order matters
; because the name-byte data labels pair with these lists by POSITION:
; (LPN i) is the i-th prim's name, so startup-prims and string-data-prims
; must walk the same list in the same order.
(define SPECIALS
  (list (list "GSymQuote" "LQuote" "quote") (list "GSymIf" "LIf" "if")
        (list "GSymDefine" "LDefine" "define") (list "GSymSet" "LSet" "set!")
        (list "GSymLambda" "LLambda" "lambda")
        (list "GSymBegin" "LBegin" "begin") (list "GSymLet" "LLet" "let")
        (list "GSymCond" "LCond" "cond") (list "GSymAnd" "LAnd" "and")
        (list "GSymOr" "LOr" "or") (list "GSymElse" "LElse" "else")))

(define PRIMS
  (list
    (cons "cons" "PrCons") (cons "car" "PrCar") (cons "cdr" "PrCdr")
    (cons "set-car!" "PrSetCar") (cons "set-cdr!" "PrSetCdr")
    (cons "pair?" "PrPairQ") (cons "null?" "PrNullQ")
    (cons "eq?" "PrEqQ") (cons "eqv?" "PrEqQ")
    (cons "symbol?" "PrSymQ") (cons "number?" "PrNumQ")
    (cons "string?" "PrStrQ") (cons "char?" "PrCharQ")
    (cons "procedure?" "PrProcQ") (cons "boolean?" "PrBoolQ")
    (cons "not" "PrNot")
    (cons "+" "PrAdd") (cons "-" "PrSub") (cons "*" "PrMul")
    (cons "quotient" "PrQuot") (cons "remainder" "PrRem")
    (cons "=" "PrNumEq") (cons "<" "PrLt") (cons ">" "PrGt")
    (cons "<=" "PrLe") (cons ">=" "PrGe")
    (cons "display" "PrDisplay") (cons "write" "PrWrite")
    (cons "newline" "PrNewline")
    (cons "read-char" "PrReadChar") (cons "peek-char" "PrPeekChar")
    (cons "eof-object?" "PrEofQ")
    (cons "char->integer" "PrCharInt") (cons "integer->char" "PrIntChar")
    (cons "string-length" "PrStrLen") (cons "string-ref" "PrStrRef")
    (cons "string->symbol" "PrStrSym") (cons "symbol->string" "PrSymStr")
    (cons "list->string" "PrListStr")
    (cons "error" "PrError") (cons "exit" "PrExit")))

; ---------------------------------------------------------------------------
; Startup loops.
; ---------------------------------------------------------------------------
; Intern each special form's name into its G-cell; then bind each primitive
; in the global environment (DefPrim wraps the code label as a subtype-3
; object and conses (sym . prim) onto GEnv).
(define (startup-specials lst)
  (if (null? lst) #t
      (begin
        (let ((e (car lst)))
          (begin
            (I (string-append "(MovRILabel EAX " (cadr e) ")"))
            (MOVRI "ECX" (k (string-length (caddr e))))
            (call "Intern")
            (I (string-append "(MovMemLR " (car e) " EAX)"))))
        (startup-specials (cdr lst)))))

(define (startup-prims lst pi)
  (if (null? lst) #t
      (begin
        (let ((p (car lst)))
          (begin
            (I (string-append "(MovRILabel EAX (LPN " (number->string pi) "))"))
            (MOVRI "ECX" (k (string-length (car p))))
            (call "Intern")
            (I (string-append "(MovRILabel ECX " (cdr p) ")"))
            (call "DefPrim")))
        (startup-prims (cdr lst) (+ pi 1)))))

; ---------------------------------------------------------------------------
; (EV 4) pair-dispatch loop.
; ---------------------------------------------------------------------------
; Combination dispatch: EDX holds the (already fetched) head of the form;
; compare it against each interned special-form symbol, falling through
; (EV 5 <sym>) labels to the next candidate.  quote (the #f entry) is
; handled inline -- return the cadr unevaluated; every other special form
; tail-jumps to its Ev* routine.  `else` is deliberately absent: it is only
; recognized inside cond.
(define EV-SPECIALS
  (list (cons "GSymQuote" #f) (cons "GSymIf" "EvIf")
        (cons "GSymDefine" "EvDefine") (cons "GSymSet" "EvSet")
        (cons "GSymLambda" "EvLambda") (cons "GSymBegin" "EvBegin")
        (cons "GSymLet" "EvLet") (cons "GSymCond" "EvCond")
        (cons "GSymAnd" "EvAnd") (cons "GSymOr" "EvOr")))

(define (ev-dispatch lst)
  (if (null? lst) #t
      (begin
        (let ((e (car lst)))
          (begin
            (I (string-append "(MovRMemL EBX " (car e) ")"))
            (I "(CmpRR EDX EBX)")
            (I (string-append "(Jnz (EV 5 " (car e) "))"))
            (if (eq? (cdr e) #f)
                (begin
                  (I "(MovRMD EAX EAX 04)")
                  (I "(MovRM EAX EAX)")
                  (I "(Ret)"))
                (I (string-append "(Jmp32 " (cdr e) ")")))
            (L (string-append "(EV 5 " (car e) ")"))))
        (ev-dispatch (cdr lst)))))

; ---------------------------------------------------------------------------
; DATA helpers: global cells and the interned name strings.
; ---------------------------------------------------------------------------
; Globals start zeroed except the two list heads (GObList, GEnv) which
; start as nil (0x03).  Name strings are raw (Db ..) bytes; startup code
; knows their lengths from the tables above.
(define (emit-str-bytes text i n)
  (if (< i n)
      (begin
        (I (string-append "(Db " (byte-hex (char->integer (string-ref text i))) ")"))
        (emit-str-bytes text (+ i 1) n))
      #t))

(define DATA-GNAMES
  (append (list "GCellFree" "GByteFree" "GInPtr" "GInEnd" "GObList" "GEnv"
                "GTokBuf" "GReadBuf")
          (map car SPECIALS)))

(define (data-gnames lst)
  (if (null? lst) #t
      (begin
        (let ((g (car lst)))
          (begin
            (L g)
            (I (string-append "(Dd "
                 (x8-str (if (or (string=? g "GObList") (string=? g "GEnv"))
                             (k NIL) (k 0))) ")"))))
        (data-gnames (cdr lst)))))

(define (string-data-specials lst)
  (if (null? lst) #t
      (begin
        (let ((e (car lst)))
          (begin (L (cadr e)) (emit-str-bytes (caddr e) 0 (string-length (caddr e)))))
        (string-data-specials (cdr lst)))))

(define (string-data-prims lst pi)
  (if (null? lst) #t
      (begin
        (let ((p (car lst)))
          (begin
            (L (string-append "(LPN " (number->string pi) ")"))
            (emit-str-bytes (car p) 0 (string-length (car p)))))
        (string-data-prims (cdr lst) (+ pi 1)))))

; ---------------------------------------------------------------------------
; Build S in order: the interpreter itself, one instruction per line.
; ---------------------------------------------------------------------------
; Register conventions:
;   EAX  value: first argument and result;
;   ECX  the environment -- an assoc list of (sym . val) pairs, locals in
;        front; LookupPair falls back to the global GEnv list;
;   EDX, EBX, EDI, ESI  scratch.
; Calls are plain Call/Ret on the machine stack; tail positions Jmp32 to
; EvalTop/SeqTail instead of calling, which is what gives scheme0 proper
; tail calls.  Memory is three bump arenas carved after CodeEnd (cells,
; object bytes, input buffer) -- there is no GC.
(define (build)
  ; --- Startup ---
  ; Arena layout: cell arena at CodeEnd (8-byte aligned), byte arena
  ; +0x0C000000, 16 MiB stdin buffer +0x02000000, token buffer +0x01000000
  ; further.  The (Program ... bss ...) request at the bottom reserves the
  ; whole span as ELF memsz.
  (L "Start")
  (I "(MovRILabel EAX CodeEnd)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GCellFree EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 12) 24)) ")"))
  (I "(MovMemLR GByteFree EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 2) 24)) ")"))
  (I "(MovMemLR GReadBuf EAX)")
  (I "(MovMemLR GInPtr EAX)")
  (I "(MovMemLR GInEnd EAX)")
  (I (string-append "(AddI32 EAX " (x8-str (w32-shl (k 1) 24)) ")"))
  (I "(MovMemLR GTokBuf EAX)")
  (startup-specials SPECIALS)
  (startup-prims PRIMS 0)

  ; Read-eval-print until eof (then exit 0); unspecified results are not
  ; printed, so definitions stay silent.
  (L "MainLoop")
  (call "ReadExpr")
  (CMPEAX (k EOFV))
  (I "(Jnz (M 1))")
  (MOVRI "EAX" (k 1))
  (I "(XorRR EBX EBX)")
  (I "(Int 80)")
  (L "(M 1)")
  (I "(MovRMemL ECX GEnv)")
  (call "Eval")
  (CMPEAX (k UNSPEC))
  (I "(Jz MainLoop2)")
  (call "Print")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (L "MainLoop2")
  (I "(Jmp32 MainLoop)")

  ; DefPrim: EAX = name symbol, ECX = code entry address.  Builds the
  ; subtype-3 object (address|3 payload, length 0) and conses the binding
  ; onto the global environment.
  (L "DefPrim")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(OrI8 EAX 03)")
  (MOVRI "ECX" (k 1))
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(MovRMemL ECX GEnv)")
  (call "Cons")
  (I "(MovMemLR GEnv EAX)")
  (I "(Ret)")

  ; --- Output ---
  ; Emit: write(1, WriteChBuf, 1) with the byte from AL; PrintRaw: write(1,
  ; ECX, EDX); ErrTok: print "!\n" and exit 1 (reader syntax error).
  (L "Emit")
  (I "(PushR EBX)")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (I "(MovRILabel ECX WriteChBuf)")
  (I "(MovbMR ECX EAX)")
  (MOVRI "EAX" (k 4))
  (MOVRI "EBX" (k 1))
  (MOVRI "EDX" (k 1))
  (I "(Int 80)")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(PopR EBX)")
  (I "(Ret)")

  (L "PrintRaw")
  (MOVRI "EAX" (k 4))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")
  (I "(Ret)")

  (L "ErrTok")
  (MOVRI "EAX" (k 33))
  (call "Emit")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")

  ; --- Allocation ---
  ; Cons: bump an 8-byte cell off GCellFree; car=EAX, cdr=ECX.
  (L "Cons")
  (I "(PushR EDX)")
  (I "(MovRMemL EDX GCellFree)")
  (I "(MovMR EDX EAX)")
  (I "(MovMDR EDX 04 ECX)")
  (I "(MovRR EAX EDX)")
  (I "(AddI8 EDX 08)")
  (I "(MovMemLR GCellFree EDX)")
  (I "(PopR EDX)")
  (I "(Ret)")

  ; AllocObj: EAX = source bytes, ECX = length, EDX = subtype.  Copies the
  ; bytes into the byte arena (8-aligned so the payload pointer has room
  ; for the subtype in its low bits), builds the object cell
  ; [payload|subtype, len<<2|1] and returns the tagged (|2) pointer.
  (L "AllocObj")
  (I "(PushR EDX)")
  (I "(MovRMemL EDI GByteFree)")
  (I "(PushR EDI)")
  (I "(MovRR ESI EAX)")
  (I "(PushR ECX)")
  (I "(RepMovsb)")
  (I "(PopR ECX)")
  (I "(MovRR EAX EDI)")
  (I "(AddI8 EAX 07)")
  (I "(AndI8 EAX F8)")
  (I "(MovMemLR GByteFree EAX)")
  (I "(PopR EAX)")
  (I "(PopR EDX)")
  (I "(OrRR EAX EDX)")
  (I "(PushR EAX)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  ; --- Input ---
  ; ReadCh: one character in EAX, or -1 at eof.  GPeek is a one-slot
  ; pushback (-1 = empty) serving peek-char and the reader's lookahead;
  ; when the buffer runs dry, one big read(0, GReadBuf, 16 MiB) refills it.
  (L "ReadCh")
  (I "(MovRMemL EAX GPeek)")
  (CMPEAX wm1)
  (I "(Jz (RC 1))")
  (I "(PushR ECX)")
  (MOVRI "ECX" wm1)
  (I "(MovMemLR GPeek ECX)")
  (I "(PopR ECX)")
  (I "(Ret)")
  (L "(RC 1)")
  (I "(PushR ECX)")
  (I "(MovRMemL EAX GInPtr)")
  (I "(MovRMemL ECX GInEnd)")
  (I "(CmpRR EAX ECX)")
  (I "(Jnz (RC 3))")
  (I "(PushR EBX)")
  (I "(PushR EDX)")
  (MOVRI "EAX" (k 3))
  (I "(XorRR EBX EBX)")
  (I "(MovRMemL ECX GReadBuf)")
  (MOVRI "EDX" (w32-shl (k 1) 24))
  (I "(Int 80)")
  (I "(TestRR EAX EAX)")
  (I "(Jg (RC 2))")
  (I "(PopR EDX)")
  (I "(PopR EBX)")
  (I "(PopR ECX)")
  (MOVRI "EAX" wm1)
  (I "(Ret)")
  (L "(RC 2)")
  (I "(MovRMemL ECX GReadBuf)")
  (I "(MovMemLR GInPtr ECX)")
  (I "(AddRR ECX EAX)")
  (I "(MovMemLR GInEnd ECX)")
  (I "(PopR EDX)")
  (I "(PopR EBX)")
  (I "(MovRMemL EAX GInPtr)")
  (L "(RC 3)")
  (I "(MovRR ECX EAX)")
  (I "(MovzxRMb EAX ECX)")
  (I "(IncR ECX)")
  (I "(MovMemLR GInPtr ECX)")
  (I "(PopR ECX)")
  (I "(Ret)")

  (L "PeekCh")
  (call "ReadCh")
  (I "(MovMemLR GPeek EAX)")
  (I "(Ret)")

  ; SkipWS: also swallows ;-comments to end of line; the terminating
  ; non-blank character is pushed back via GPeek at (SW 3).
  (L "SkipWS")
  (L "(SW 1)")
  (call "ReadCh")
  (I "(CmpALI8 20)")
  (I "(Jz (SW 1))")
  (I "(CmpALI8 09)")
  (I "(Jz (SW 1))")
  (I "(CmpALI8 0A)")
  (I "(Jz (SW 1))")
  (I "(CmpALI8 0D)")
  (I "(Jz (SW 1))")
  (I "(CmpALI8 3B)")
  (I "(Jnz (SW 3))")
  (L "(SW 2)")
  (call "ReadCh")
  (CMPEAX wm1)
  (I "(Jz (SW 4))")
  (I "(CmpALI8 0A)")
  (I "(Jz (SW 1))")
  (I "(JmpS (SW 2))")
  (L "(SW 3)")
  (I "(MovMemLR GPeek EAX)")
  (L "(SW 4)")
  (I "(Ret)")

  ; --- Reader ---
  ; Recursive descent on the first character: ( list, ' quote sugar,
  ; # hash syntax, " string, digits (or - digit) number, anything else a
  ; symbol.  A stray ) is a syntax error.
  (L "ReadExpr")
  (call "SkipWS")
  (call "ReadCh")
  (CMPEAX wm1)
  (I "(Jnz (RE 1))")
  (MOVRI "EAX" (k EOFV))
  (I "(Ret)")
  (L "(RE 1)")
  (I "(CmpALI8 28)")
  (I "(Jnz (RE 2))")
  (I "(Jmp32 ReadList)")
  (L "(RE 2)")
  (I "(CmpALI8 29)")
  (I "(Jnz (RE 3))")
  (I "(Jmp32 ErrTok)")
  (L "(RE 3)")
  (I "(CmpALI8 27)")
  (I "(Jnz (RE 4))")
  (call "ReadExpr")
  (MOVRI "ECX" (k NIL))
  (call "Cons")
  (I "(MovRR ECX EAX)")
  (I "(MovRMemL EAX GSymQuote)")
  (I "(Jmp32 Cons)")
  (L "(RE 4)")
  (I "(CmpALI8 23)")
  (I "(Jnz (RE 5))")
  (I "(Jmp32 ReadHash)")
  (L "(RE 5)")
  (I "(CmpALI8 22)")
  (I "(Jnz (RE 6))")
  (I "(Jmp32 ReadString)")
  (L "(RE 6)")
  (I "(CmpALI8 30)")
  (I "(Jb (RE 7))")
  (I "(CmpALI8 39)")
  (I "(Ja (RE 7))")
  (I "(XorRR ECX ECX)")
  (I "(Jmp32 ReadNum)")
  (L "(RE 7)")
  (I "(CmpALI8 2D)")
  (I "(Jnz (RE 9))")
  (I "(PushR EAX)")
  (call "PeekCh")
  (I "(CmpALI8 30)")
  (I "(Jb (RE 8))")
  (I "(CmpALI8 39)")
  (I "(Ja (RE 8))")
  (I "(PopR EAX)")
  (call "ReadCh")
  (MOVRI "ECX" (k 1))
  (I "(Jmp32 ReadNum)")
  (L "(RE 8)")
  (I "(PopR EAX)")
  (L "(RE 9)")
  (I "(Jmp32 ReadSym)")

  ; ReadNum: ECX on entry = negate flag.  acc*10 as (acc<<3)+(acc<<1);
  ; result returned as a tagged fixnum.
  (L "ReadNum")
  (I "(PushR ECX)")
  (I "(SubI8 EAX 30)")
  (I "(MovRR ECX EAX)")
  (L "(RN 1)")
  (call "PeekCh")
  (I "(CmpALI8 30)")
  (I "(Jb (RN 2))")
  (I "(CmpALI8 39)")
  (I "(Ja (RN 2))")
  (call "ReadCh")
  (I "(SubI8 EAX 30)")
  (I "(MovRR EDX ECX)")
  (I "(ShlI8 ECX 03)")
  (I "(ShlI8 EDX 01)")
  (I "(AddRR ECX EDX)")
  (I "(AddRR ECX EAX)")
  (I "(JmpS (RN 1))")
  (L "(RN 2)")
  (I "(MovRR EAX ECX)")
  (I "(PopR ECX)")
  (I "(TestRR ECX ECX)")
  (I "(Jz (RN 3))")
  (I "(NegR EAX)")
  (L "(RN 3)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  ; ReadList: builds the list by stack recursion.  A `.` counts as the
  ; dotted-pair dot only when FOLLOWED by a delimiter ((RL 2)..(RL 3)), so
  ; symbols starting with a dot still read; exactly one expr then `)` may
  ; follow it.
  (L "ReadList")
  (call "SkipWS")
  (call "PeekCh")
  (I "(CmpALI8 29)")
  (I "(Jnz (RL 1))")
  (call "ReadCh")
  (MOVRI "EAX" (k NIL))
  (I "(Ret)")
  (L "(RL 1)")
  (CMPEAX wm1)
  (I "(Jnz (RL 2))")
  (I "(Jmp32 ErrTok)")
  (L "(RL 2)")
  (I "(CmpALI8 2E)")
  (I "(Jnz (RL 4))")
  (call "ReadCh")
  (call "PeekCh")
  (I "(CmpALI8 20)")
  (I "(Jz (RL 3))")
  (I "(CmpALI8 09)")
  (I "(Jz (RL 3))")
  (I "(CmpALI8 0A)")
  (I "(Jz (RL 3))")
  (I "(CmpALI8 0D)")
  (I "(Jz (RL 3))")
  (I "(CmpALI8 28)")
  (I "(Jz (RL 3))")
  (I "(Jmp32 ErrTok)")
  (L "(RL 3)")
  (call "ReadExpr")
  (I "(PushR EAX)")
  (call "SkipWS")
  (call "ReadCh")
  (I "(CmpALI8 29)")
  (I "(Jz (RL 5))")
  (I "(Jmp32 ErrTok)")
  (L "(RL 5)")
  (I "(PopR EAX)")
  (I "(Ret)")
  (L "(RL 4)")
  (call "ReadExpr")
  (I "(PushR EAX)")
  (call "ReadList")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (I "(Jmp32 Cons)")

  ; ReadHash: #t, #f, and #\char.  For #\ a run of lowercase letters is
  ; consumed greedily and the FIRST letter decides: s(pace), n(ewline),
  ; t(ab); a single character stands for itself ((RH 5)).
  (L "ReadHash")
  (call "ReadCh")
  (I "(CmpALI8 74)")
  (I "(Jnz (RH 1))")
  (MOVRI "EAX" (k TRUE))
  (I "(Ret)")
  (L "(RH 1)")
  (I "(CmpALI8 66)")
  (I "(Jnz (RH 2))")
  (MOVRI "EAX" (k FALSE))
  (I "(Ret)")
  (L "(RH 2)")
  (I "(CmpALI8 5C)")
  (I "(Jz (RH 3))")
  (I "(Jmp32 ErrTok)")
  (L "(RH 3)")
  (call "ReadCh")
  (I "(PushR EAX)")
  (call "PeekCh")
  (I "(CmpALI8 61)")
  (I "(Jb (RH 5))")
  (I "(CmpALI8 7A)")
  (I "(Ja (RH 5))")
  (L "(RH 4)")
  (call "ReadCh")
  (call "PeekCh")
  (I "(CmpALI8 61)")
  (I "(Jb (RH 40))")
  (I "(CmpALI8 7A)")
  (I "(Jbe (RH 4))")
  (L "(RH 40)")
  (I "(PopR EAX)")
  (I "(CmpALI8 73)")
  (I "(Jnz (RH 41))")
  (MOVRI "EAX" (k 32))
  (I "(JmpS (RH 6))")
  (L "(RH 41)")
  (I "(CmpALI8 6E)")
  (I "(Jnz (RH 42))")
  (MOVRI "EAX" (k 10))
  (I "(JmpS (RH 6))")
  (L "(RH 42)")
  (I "(CmpALI8 74)")
  (I "(Jnz (RH 43))")
  (MOVRI "EAX" (k 9))
  (I "(JmpS (RH 6))")
  (L "(RH 43)")
  (I "(Jmp32 ErrTok)")
  (L "(RH 5)")
  (I "(PopR EAX)")
  (L "(RH 6)")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")

  ; ReadString: bytes into GTokBuf until the closing quote; only \n is a
  ; recognized escape (any other backslashed char is taken literally).
  (L "ReadString")
  (I "(MovRMemL EDX GTokBuf)")
  (L "(RS 1)")
  (call "ReadCh")
  (CMPEAX wm1)
  (I "(Jnz (RS 10))")
  (I "(Jmp32 ErrTok)")
  (L "(RS 10)")
  (I "(CmpALI8 22)")
  (I "(Jz (RS 3))")
  (I "(CmpALI8 5C)")
  (I "(Jnz (RS 2))")
  (call "ReadCh")
  (I "(CmpALI8 6E)")
  (I "(Jnz (RS 2))")
  (MOVRI "EAX" (k 10))
  (L "(RS 2)")
  (I "(MovbMR EDX EAX)")
  (I "(IncR EDX)")
  (I "(Jmp32 (RS 1))")
  (L "(RS 3)")
  (I "(MovRMemL EAX GTokBuf)")
  (I "(MovRR ECX EDX)")
  (I "(SubRR ECX EAX)")
  (MOVRI "EDX" (k 1))
  (I "(Jmp32 AllocObj)")

  ; ReadSym: collect to the next delimiter (pushed back via GPeek), then
  ; intern the token.
  (L "ReadSym")
  (I "(MovRMemL EDX GTokBuf)")
  (I "(MovbMR EDX EAX)")
  (I "(IncR EDX)")
  (L "(RY 1)")
  (call "ReadCh")
  (CMPEAX wm1)
  (I "(Jz (RY 2))")
  (I "(CmpALI8 20)")
  (I "(Jz (RY 2))")
  (I "(CmpALI8 09)")
  (I "(Jz (RY 2))")
  (I "(CmpALI8 0A)")
  (I "(Jz (RY 2))")
  (I "(CmpALI8 0D)")
  (I "(Jz (RY 2))")
  (I "(CmpALI8 28)")
  (I "(Jz (RY 2))")
  (I "(CmpALI8 29)")
  (I "(Jz (RY 2))")
  (I "(CmpALI8 22)")
  (I "(Jz (RY 2))")
  (I "(CmpALI8 3B)")
  (I "(Jz (RY 2))")
  (I "(MovbMR EDX EAX)")
  (I "(IncR EDX)")
  (I "(JmpS (RY 1))")
  (L "(RY 2)")
  (I "(MovMemLR GPeek EAX)")
  (I "(MovRMemL EAX GTokBuf)")
  (I "(MovRR ECX EDX)")
  (I "(SubRR ECX EAX)")
  (I "(Jmp32 Intern)")

  ; Intern: EAX = token bytes, ECX = length.  Linear scan of the GObList
  ; oblist comparing length first, bytes second (RepeCmpsb); on a miss,
  ; allocate a fresh subtype-0 (symbol) object and push it on.  Symbol
  ; identity is therefore pointer identity, which is what Eval and eq?
  ; compare.
  (L "Intern")
  (I "(MovRMemL EDX GObList)")
  (L "(IN 1)")
  (I "(TestRI8 EDX 03)")
  (I "(Jz (IN 2))")
  (I "(XorRR EDX EDX)")
  (call "AllocObj")
  (I "(PushR EAX)")
  (I "(MovRMemL ECX GObList)")
  (call "Cons")
  (I "(MovMemLR GObList EAX)")
  (I "(PopR EAX)")
  (I "(Ret)")
  (L "(IN 2)")
  (I "(MovRM EBX EDX)")
  (I "(MovRR EDI EBX)")
  (I "(SubI8 EDI 02)")
  (I "(MovRMD ESI EDI 04)")
  (I "(SarI8 ESI 02)")
  (I "(CmpRR ESI ECX)")
  (I "(Jnz (IN 3))")
  (I "(MovRM ESI EDI)")
  (I "(MovRR EDI EAX)")
  (I "(PushR ECX)")
  (I "(RepeCmpsb)")
  (I "(PopR ECX)")
  (I "(Jnz (IN 3))")
  (I "(MovRR EAX EBX)")
  (I "(Ret)")
  (L "(IN 3)")
  (I "(MovRMD EDX EDX 04)")
  (I "(JmpS (IN 1))")

  ; --- Evaluator ---
  ; Eval(EAX = expr, ECX = env), dispatch on the tag: fixnums and
  ; immediates self-evaluate; objects are looked up when they are symbols
  ; (payload subtype 0) and self-evaluate otherwise; pairs fall into the
  ; special-form dispatch at (EV 4), else head and arguments are evaluated
  ; and Apply is tail-jumped.  EvalTop is the tail-call re-entry point.
  (L "Eval")
  (L "EvalTop")
  (I "(MovRR EBX EAX)")
  (I "(AndI8 EBX 03)")
  (I "(CmpI8 EBX 01)")
  (I "(Jnz (EV 1))")
  (I "(Ret)")
  (L "(EV 1)")
  (I "(CmpI8 EBX 03)")
  (I "(Jnz (EV 2))")
  (I "(Ret)")
  (L "(EV 2)")
  (I "(CmpI8 EBX 02)")
  (I "(Jnz (EV 4))")
  (I "(MovRR EDX EAX)")
  (I "(SubI8 EDX 02)")
  (I "(MovRM EDX EDX)")
  (I "(TestRI8 EDX 07)")
  (I "(Jz (EV 3))")
  (I "(Ret)")
  (L "(EV 3)")
  (call "LookupPair")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")
  (L "(EV 4)")
  (I "(MovRM EDX EAX)")
  (ev-dispatch EV-SPECIALS)
  (I "(PushR ECX)")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Eval")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(PushR EAX)")
  (I "(MovRMD EAX EDX 04)")
  (call "EvList")
  (I "(MovRR EDX EAX)")
  (I "(PopR EAX)")
  (I "(Jmp32 Apply)")

  ; LookupPair: find the (sym . val) binding cell for EAX; two rounds
  ; (EBX = round flag): the local env in ECX, then the global GEnv.
  ; Unbound -> print the symbol, "?", exit 1.
  (L "LookupPair")
  (I "(XorRR EBX EBX)")
  (L "(LK 1)")
  (I "(TestRI8 ECX 03)")
  (I "(Jnz (LK 3))")
  (I "(MovRM EDX ECX)")
  (I "(MovRM EDI EDX)")
  (I "(CmpRR EDI EAX)")
  (I "(Jz (LK 2))")
  (I "(MovRMD ECX ECX 04)")
  (I "(JmpS (LK 1))")
  (L "(LK 2)")
  (I "(MovRR EAX EDX)")
  (I "(Ret)")
  (L "(LK 3)")
  (I "(TestRR EBX EBX)")
  (I "(Jnz (LK 4))")
  (I "(IncR EBX)")
  (I "(MovRMemL ECX GEnv)")
  (I "(JmpS (LK 1))")
  (L "(LK 4)")
  (call "Print")
  (MOVRI "EAX" (k 63))
  (call "Emit")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")

  ; EvList: evaluate an argument list left to right into a fresh list.
  (L "EvList")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (EL 1))")
  (MOVRI "EAX" (k NIL))
  (I "(Ret)")
  (L "(EL 1)")
  (I "(PushR ECX)")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Eval")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(PushR EAX)")
  (I "(MovRMD EAX EDX 04)")
  (call "EvList")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (I "(Jmp32 Cons)")

  ; EvIf: only #f is false; a missing else branch yields unspecified.
  ; Both branches are entered by Jmp32 EvalTop -- tail position.
  (L "EvIf")
  (I "(MovRMD EDX EAX 04)")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (I "(MovRM EAX EDX)")
  (call "Eval")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (CMPEAX (k FALSE))
  (I "(MovRMD EDX EDX 04)")
  (I "(Jz (IF 1))")
  (I "(MovRM EAX EDX)")
  (I "(Jmp32 EvalTop)")
  (L "(IF 1)")
  (I "(MovRMD EDX EDX 04)")
  (I "(TestRI8 EDX 03)")
  (I "(Jz (IF 2))")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(IF 2)")
  (I "(MovRM EAX EDX)")
  (I "(Jmp32 EvalTop)")

  ; EvDefine: (define x e) conses a global binding.  The (DF 1) branch is
  ; the (define (f . args) body...) sugar: it builds (lambda args body...)
  ; in place and evaluates that instead.
  (L "EvDefine")
  (I "(MovRMD EDX EAX 04)")
  (I "(MovRM EBX EDX)")
  (I "(TestRI8 EBX 03)")
  (I "(Jz (DF 1))")
  (I "(PushR EBX)")
  (I "(MovRMD EDX EDX 04)")
  (I "(MovRM EAX EDX)")
  (call "Eval")
  (I "(MovRR EDX EAX)")
  (I "(PopR EAX)")
  (I "(MovRR ECX EDX)")
  (call "Cons")
  (I "(MovRMemL ECX GEnv)")
  (call "Cons")
  (I "(MovMemLR GEnv EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(DF 1)")
  (I "(PushR ECX)")
  (I "(MovRMD EAX EDX 04)")
  (I "(MovRR ECX EAX)")
  (I "(MovRMD EAX EBX 04)")
  (call "Cons")
  (I "(MovRR ECX EAX)")
  (I "(MovRMemL EAX GSymLambda)")
  (call "Cons")
  (I "(MovRM EBX EBX)")
  (I "(PopR ECX)")
  (I "(PushR EBX)")
  (call "Eval")
  (I "(MovRR ECX EAX)")
  (I "(PopR EAX)")
  (call "Cons")
  (I "(MovRMemL ECX GEnv)")
  (call "Cons")
  (I "(MovMemLR GEnv EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  ; EvSet: find the binding cell, then overwrite its cdr in place.
  (L "EvSet")
  (I "(MovRMD EDX EAX 04)")
  (I "(PushR EDX)")
  (I "(PushR ECX)")
  (I "(MovRM EAX EDX)")
  (call "LookupPair")
  (I "(PopR ECX)")
  (I "(PopR EDX)")
  (I "(PushR EAX)")
  (I "(MovRMD EDX EDX 04)")
  (I "(MovRM EAX EDX)")
  (call "Eval")
  (I "(PopR ECX)")
  (I "(MovMDR ECX 04 EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  ; EvLambda: a closure is an object of subtype 2 whose payload is
  ; (params . (body... . env)) -- the defining environment captured by
  ; reference.
  (L "EvLambda")
  (I "(MovRMD EDX EAX 04)")
  (I "(MovRMD EAX EDX 04)")
  (call "Cons")
  (I "(MovRR ECX EAX)")
  (I "(MovRM EAX EDX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (MOVRI "ECX" (k 1))
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (L "EvBegin")
  (I "(MovRMD EAX EAX 04)")
  (I "(Jmp32 SeqTail)")

  ; SeqTail: evaluate a body sequence, Jmp32-ing into the LAST form --
  ; the single place that makes closure bodies, let, cond and begin all
  ; properly tail recursive.
  (L "SeqTail")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (SQ 1))")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(SQ 1)")
  (I "(MovRMD EDX EAX 04)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (SQ 2))")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (I "(MovRM EAX EAX)")
  (call "Eval")
  (I "(PopR EAX)")
  (I "(PopR ECX)")
  (I "(JmpS (SQ 1))")
  (L "(SQ 2)")
  (I "(MovRM EAX EAX)")
  (I "(Jmp32 EvalTop)")

  ; EvLet: evaluate each init in the ORIGINAL env (kept on the stack),
  ; consing (var . val) pairs onto the new env, then SeqTail the body.
  (L "EvLet")
  (I "(MovRMD EDX EAX 04)")
  (I "(MovRM EBX EDX)")
  (I "(PushR EDX)")
  (I "(PushR ECX)")
  (L "(LT 1)")
  (I "(TestRI8 EBX 03)")
  (I "(Jnz (LT 2))")
  (I "(MovRM EDX EBX)")
  (I "(PushR EBX)")
  (I "(PushR ECX)")
  (I "(MovRMD EAX EDX 04)")
  (I "(MovRM EAX EAX)")
  (I "(PushR EDX)")
  (call "Eval")
  (I "(PopR EDX)")
  (I "(MovRR ECX EAX)")
  (I "(MovRM EAX EDX)")
  (call "Cons")
  (I "(PopR ECX)")
  (I "(PopR EBX)")
  (I "(PopR EDX)")
  (I "(PushR ECX)")
  (I "(MovRR ECX EDX)")
  (call "Cons")
  (I "(PopR ECX)")
  (I "(PushR EAX)")
  (I "(MovRMD EBX EBX 04)")
  (I "(JmpS (LT 1))")
  (L "(LT 2)")
  (I "(PopR ECX)")
  (I "(PopR EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Jmp32 SeqTail)")

  ; EvCond: walk the clauses; `else` matches by symbol identity; a clause
  ; with no body ((CO 3)) returns the test's value; no clause -> unspec.
  (L "EvCond")
  (I "(MovRMD EBX EAX 04)")
  (L "(CO 1)")
  (I "(TestRI8 EBX 03)")
  (I "(Jnz (CO 5))")
  (I "(MovRM EDX EBX)")
  (I "(MovRM EAX EDX)")
  (I "(MovRMemL EDI GSymElse)")
  (I "(CmpRR EAX EDI)")
  (I "(Jz (CO 4))")
  (I "(PushR EBX)")
  (I "(PushR ECX)")
  (I "(PushR EDX)")
  (call "Eval")
  (I "(PopR EDX)")
  (I "(PopR ECX)")
  (I "(PopR EBX)")
  (CMPEAX (k FALSE))
  (I "(Jnz (CO 2))")
  (I "(MovRMD EBX EBX 04)")
  (I "(JmpS (CO 1))")
  (L "(CO 2)")
  (I "(MovRMD EDX EDX 04)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (CO 3))")
  (I "(MovRR EAX EDX)")
  (I "(Jmp32 SeqTail)")
  (L "(CO 3)")
  (I "(Ret)")
  (L "(CO 4)")
  (I "(MovRMD EAX EDX 04)")
  (I "(Jmp32 SeqTail)")
  (L "(CO 5)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  ; EvAnd / EvOr: short-circuit, last operand in tail position.
  (L "EvAnd")
  (I "(MovRMD EBX EAX 04)")
  (I "(TestRI8 EBX 03)")
  (I "(Jz (AN 1))")
  (MOVRI "EAX" (k TRUE))
  (I "(Ret)")
  (L "(AN 1)")
  (I "(MovRMD EDX EBX 04)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (AN 3))")
  (I "(PushR EBX)")
  (I "(PushR ECX)")
  (I "(MovRM EAX EBX)")
  (call "Eval")
  (I "(PopR ECX)")
  (I "(PopR EBX)")
  (CMPEAX (k FALSE))
  (I "(Jz (AN 2))")
  (I "(MovRMD EBX EBX 04)")
  (I "(JmpS (AN 1))")
  (L "(AN 2)")
  (I "(Ret)")
  (L "(AN 3)")
  (I "(MovRM EAX EBX)")
  (I "(Jmp32 EvalTop)")

  (L "EvOr")
  (I "(MovRMD EBX EAX 04)")
  (I "(TestRI8 EBX 03)")
  (I "(Jz (OR 1))")
  (MOVRI "EAX" (k FALSE))
  (I "(Ret)")
  (L "(OR 1)")
  (I "(MovRMD EDX EBX 04)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (OR 3))")
  (I "(PushR EBX)")
  (I "(PushR ECX)")
  (I "(MovRM EAX EBX)")
  (call "Eval")
  (I "(PopR ECX)")
  (I "(PopR EBX)")
  (CMPEAX (k FALSE))
  (I "(Jnz (OR 2))")
  (I "(MovRMD EBX EBX 04)")
  (I "(JmpS (OR 1))")
  (L "(OR 2)")
  (I "(Ret)")
  (L "(OR 3)")
  (I "(MovRM EAX EBX)")
  (I "(Jmp32 EvalTop)")

  ; Apply: EAX = procedure object, EDX = evaluated argument list.
  ; Subtype 3 (primitive): mask the tag off the payload and JmpR straight
  ; into the code with the arg list in EAX.  Subtype 2 (closure): bind
  ; params to args in the (AP 4) loop -- a SYMBOL in parameter position
  ; ((AP 5), including an improper tail) takes the whole remaining arg
  ; list, giving rest parameters -- then SeqTail the body in the extended
  ; environment.  Arity mismatch -> ErrApply.
  (L "Apply")
  (I "(MovRR EBX EAX)")
  (I "(AndI8 EBX 03)")
  (I "(CmpI8 EBX 02)")
  (I "(Jz (AP 1))")
  (I "(Jmp32 ErrApply)")
  (L "(AP 1)")
  (I "(MovRR ESI EAX)")
  (I "(SubI8 ESI 02)")
  (I "(MovRM EDI ESI)")
  (I "(MovRR EBX EDI)")
  (I "(AndI8 EBX 07)")
  (I "(CmpI8 EBX 03)")
  (I "(Jnz (AP 2))")
  (I "(AndI8 EDI F8)")
  (I "(MovRR EAX EDX)")
  (I "(JmpR EDI)")
  (L "(AP 2)")
  (I "(CmpI8 EBX 02)")
  (I "(Jz (AP 3))")
  (I "(Jmp32 ErrApply)")
  (L "(AP 3)")
  (I "(AndI8 EDI F8)")
  (I "(MovRM EBX EDI)")
  (I "(MovRMD ESI EDI 04)")
  (I "(MovRMD ECX ESI 04)")
  (L "(AP 4)")
  (I "(TestRI8 EBX 03)")
  (I "(Jz (AP 6))")
  (I "(MovRR EAX EBX)")
  (I "(AndI8 EAX 03)")
  (I "(CmpI8 EAX 02)")
  (I "(Jnz (AP 5))")
  (I "(MovRR EAX EBX)")
  (I "(PushR ECX)")
  (I "(MovRR ECX EDX)")
  (call "Cons")
  (I "(PopR ECX)")
  (call "Cons")
  (I "(MovRR ECX EAX)")
  (I "(JmpS (AP 7))")
  (L "(AP 5)")
  (I "(MovRR EAX EBX)")
  (CMPEAX (k NIL))
  (I "(Jnz (AP 9))")
  (I "(TestRI8 EDX 03)")
  (I "(Jz (AP 9))")
  (I "(JmpS (AP 7))")
  (L "(AP 6)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (AP 9))")
  (I "(PushR ECX)")
  (I "(MovRM EAX EBX)")
  (I "(MovRM ECX EDX)")
  (call "Cons")
  (I "(PopR ECX)")
  (call "Cons")
  (I "(MovRR ECX EAX)")
  (I "(MovRMD EBX EBX 04)")
  (I "(MovRMD EDX EDX 04)")
  (I "(JmpS (AP 4))")
  (L "(AP 7)")
  (I "(MovRM EAX ESI)")
  (I "(Jmp32 SeqTail)")
  (L "(AP 9)")
  (I "(Jmp32 ErrApply)")

  (L "ErrApply")
  (MOVRI "EAX" (k 33))
  (call "Emit")
  (MOVRI "EAX" (k 97))
  (call "Emit")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")

  ; --- Primitives ---
  ; Every primitive receives the evaluated ARGUMENT LIST in EAX and returns
  ; its result in EAX.  All entry points are PL (8-byte aligned): DefPrim
  ; ors subtype bits into their addresses.  The type predicates all funnel
  ; through ret-bool's shared #t/#f tails.
  (PL "PrCons")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRM ECX ECX)")
  (I "(MovRM EAX EAX)")
  (I "(Jmp32 Cons)")

  (PL "PrCar")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (CAR 1))")
  (I "(Jmp32 ErrApply)")
  (L "(CAR 1)")
  (I "(MovRM EAX EAX)")
  (I "(Ret)")

  (PL "PrCdr")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (CDR 1))")
  (I "(Jmp32 ErrApply)")
  (L "(CDR 1)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")

  (PL "PrSetCar")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(MovMR ECX EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrSetCdr")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(MovMDR ECX 04 EAX)")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrPairQ")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (PQ T))")
  (I "(JmpS (PQ F))")
  (ret-bool "PQ")

  (PL "PrNullQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k NIL))
  (I "(Jz (NQ T))")
  (I "(JmpS (NQ F))")
  (ret-bool "NQ")

  (PL "PrEqQ")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EAX EAX)")
  (I "(CmpRR EAX ECX)")
  (I "(Jz (EQ T))")
  (I "(JmpS (EQ F))")
  (ret-bool "EQ")

  (PL "PrSymQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (SYQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 07)")
  (I "(Jz (SYQ T))")
  (I "(JmpS (SYQ F))")
  (ret-bool "SYQ")

  (PL "PrNumQ")
  (I "(MovRM EAX EAX)")
  (I "(TestRI8 EAX 01)")
  (I "(Jz (NUQ F))")
  (I "(TestRI8 EAX 02)")
  (I "(Jz (NUQ T))")
  (I "(JmpS (NUQ F))")
  (ret-bool "NUQ")

  (PL "PrStrQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (STQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 01)")
  (I "(Jz (STQ T))")
  (I "(JmpS (STQ F))")
  (ret-bool "STQ")

  (PL "PrCharQ")
  (I "(MovRM EAX EAX)")
  (I (string-append "(AndI32 EAX " (x8-str (k 255)) ")"))
  (I "(CmpI8 EAX 53)")
  (I "(Jz (CHQ T))")
  (I "(JmpS (CHQ F))")
  (ret-bool "CHQ")

  (PL "PrProcQ")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (PCQ F))")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EAX EAX)")
  (I "(AndI8 EAX 07)")
  (I "(CmpI8 EAX 02)")
  (I "(Jz (PCQ T))")
  (I "(CmpI8 EAX 03)")
  (I "(Jz (PCQ T))")
  (I "(JmpS (PCQ F))")
  (ret-bool "PCQ")

  (PL "PrBoolQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k TRUE))
  (I "(Jz (BQ T))")
  (CMPEAX (k FALSE))
  (I "(Jz (BQ T))")
  (I "(JmpS (BQ F))")
  (ret-bool "BQ")

  (PL "PrNot")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k FALSE))
  (I "(Jz (NO T))")
  (I "(JmpS (NO F))")
  (ret-bool "NO")

  ; PrAdd: n-ary, on TAGGED fixnums.  ECX starts at 1 (tagged 0); adding a
  ; tagged value gives 4(a+b)+2, so a DecR after each add restores the |1
  ; tag -- no untagging needed.
  (PL "PrAdd")
  (MOVRI "ECX" (k 1))
  (L "(AD 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (AD 2))")
  (I "(MovRM EDX EAX)")
  (I "(AddRR ECX EDX)")
  (I "(DecR ECX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (AD 1))")
  (L "(AD 2)")
  (I "(MovRR EAX ECX)")
  (I "(Ret)")

  ; PrSub: one argument negates: 2 - (4n+1) = 4(-n)+1, so tagged negation
  ; is a subtraction from 2.  More arguments fold with the IncR re-tag
  ; trick (mirror image of PrAdd's DecR).
  (PL "PrSub")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (SB 1))")
  (MOVRI "EAX" (k 2))
  (I "(SubRR EAX ECX)")
  (I "(Ret)")
  (L "(SB 1)")
  (I "(MovRM EDX EAX)")
  (I "(SubRR ECX EDX)")
  (I "(IncR ECX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jz (SB 1))")
  (I "(MovRR EAX ECX)")
  (I "(Ret)")

  (PL "PrMul")
  (MOVRI "ECX" (k 1))
  (L "(MU 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (MU 2))")
  (I "(MovRM EDX EAX)")
  (I "(SarI8 EDX 02)")
  (I "(IMulRR ECX EDX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (MU 1))")
  (L "(MU 2)")
  (I "(MovRR EAX ECX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrQuot")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EBX EAX)")
  (I "(MovRR EAX ECX)")
  (I "(SarI8 EAX 02)")
  (I "(SarI8 EBX 02)")
  (I "(Cdq)")
  (I "(IDivR EBX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrRem")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EBX EAX)")
  (I "(MovRR EAX ECX)")
  (I "(SarI8 EAX 02)")
  (I "(SarI8 EBX 02)")
  (I "(Cdq)")
  (I "(IDivR EBX)")
  (I "(MovRR EAX EDX)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (cmp-prim "PrNumEq" "NE" "Jz")
  (cmp-prim "PrLt" "LTP" "Jl")
  (cmp-prim "PrGt" "GTP" "Jg")
  (cmp-prim "PrLe" "LEP" "Jle")
  (cmp-prim "PrGe" "GEP" "Jge")

  ; PrDisplay: strings print raw (no quotes) and characters raw (no #\
  ; prefix); everything else shares Print, i.e. write's notation.
  (PL "PrDisplay")
  (I "(MovRM EAX EAX)")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (DS 2))")
  (I "(MovRR EDX EAX)")
  (I "(SubI8 EDX 02)")
  (I "(MovRM ECX EDX)")
  (I "(MovRR EBX ECX)")
  (I "(AndI8 EBX 07)")
  (I "(CmpI8 EBX 01)")
  (I "(Jnz (DS 3))")
  (I "(AndI8 ECX F8)")
  (I "(MovRMD EDX EDX 04)")
  (I "(SarI8 EDX 02)")
  (call "PrintRaw")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(DS 2)")
  (I "(CmpI8 ECX 03)")
  (I "(Jnz (DS 3))")
  (I "(MovRR EDX EAX)")
  (I (string-append "(AndI32 EDX " (x8-str (k 255)) ")"))
  (I "(CmpI8 EDX 53)")
  (I "(Jnz (DS 3))")
  (I "(ShrI8 EAX 08)")
  (call "Emit")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")
  (L "(DS 3)")
  (call "Print")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrWrite")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrNewline")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k UNSPEC))
  (I "(Ret)")

  (PL "PrReadChar")
  (call "ReadCh")
  (CMPEAX wm1)
  (I "(Jz (RDC 1))")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")
  (L "(RDC 1)")
  (MOVRI "EAX" (k EOFV))
  (I "(Ret)")

  (PL "PrPeekChar")
  (call "PeekCh")
  (CMPEAX wm1)
  (I "(Jz (PKC 1))")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")
  (L "(PKC 1)")
  (MOVRI "EAX" (k EOFV))
  (I "(Ret)")

  (PL "PrEofQ")
  (I "(MovRM EAX EAX)")
  (CMPEAX (k EOFV))
  (I "(Jz (EFQ T))")
  (I "(JmpS (EFQ F))")
  (ret-bool "EFQ")

  (PL "PrCharInt")
  (I "(MovRM EAX EAX)")
  (I "(ShrI8 EAX 08)")
  (I "(ShlI8 EAX 02)")
  (I "(OrI8 EAX 01)")
  (I "(Ret)")

  (PL "PrIntChar")
  (I "(MovRM EAX EAX)")
  (I "(SarI8 EAX 02)")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")

  (PL "PrStrLen")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRMD EAX EAX 04)")
  (I "(Ret)")

  (PL "PrStrRef")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(MovRM EDX EAX)")
  (I "(SubI8 ECX 02)")
  (I "(MovRM EBX ECX)")
  (I "(AndI8 EBX F8)")
  (I "(SarI8 EDX 02)")
  (I "(AddRR EBX EDX)")
  (I "(MovzxRMb EAX EBX)")
  (I "(ShlI8 EAX 08)")
  (I "(OrI8 EAX 53)")
  (I "(Ret)")

  (PL "PrStrSym")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRR EDX EAX)")
  (I "(MovRM EAX EDX)")
  (I "(AndI8 EAX F8)")
  (I "(MovRMD ECX EDX 04)")
  (I "(SarI8 ECX 02)")
  (I "(Jmp32 Intern)")

  (PL "PrSymStr")
  (I "(MovRM EAX EAX)")
  (I "(SubI8 EAX 02)")
  (I "(MovRM EDX EAX)")
  (I "(OrI8 EDX 01)")
  (I "(MovRMD ECX EAX 04)")
  (I "(MovRR EAX EDX)")
  (call "Cons")
  (I "(OrI8 EAX 02)")
  (I "(Ret)")

  (PL "PrListStr")
  (I "(MovRM EDX EAX)")
  (I "(MovRMemL EDI GTokBuf)")
  (L "(LS 1)")
  (I "(TestRI8 EDX 03)")
  (I "(Jnz (LS 2))")
  (I "(MovRM EAX EDX)")
  (I "(ShrI8 EAX 08)")
  (I "(MovbMR EDI EAX)")
  (I "(IncR EDI)")
  (I "(MovRMD EDX EDX 04)")
  (I "(JmpS (LS 1))")
  (L "(LS 2)")
  (I "(MovRMemL EAX GTokBuf)")
  (I "(MovRR ECX EDI)")
  (I "(SubRR ECX EAX)")
  (MOVRI "EDX" (k 1))
  (I "(Jmp32 AllocObj)")

  (PL "PrError")
  (L "(ER 1)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (ER 2))")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(JmpS (ER 1))")
  (L "(ER 2)")
  (MOVRI "EAX" (k 10))
  (call "Emit")
  (MOVRI "EAX" (k 1))
  (MOVRI "EBX" (k 1))
  (I "(Int 80)")

  (PL "PrExit")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (EX 1))")
  (I "(MovRM EBX EAX)")
  (I "(SarI8 EBX 02)")
  (MOVRI "EAX" (k 1))
  (I "(Int 80)")
  (L "(EX 1)")
  (MOVRI "EAX" (k 1))
  (I "(XorRR EBX EBX)")
  (I "(Int 80)")

  ; --- Printer ---
  ; Print: write notation, dispatched on the tag.  Symbols print their
  ; bytes raw, strings quoted, chars as #\c, unknown subtypes as `?`;
  ; PrintPair renders improper tails as " . x".
  (L "Print")
  (I "(MovRR ECX EAX)")
  (I "(AndI8 ECX 03)")
  (I "(CmpI8 ECX 01)")
  (I "(Jnz (PR 1))")
  (I "(Jmp32 PrintNum)")
  (L "(PR 1)")
  (I "(CmpI8 ECX 02)")
  (I "(Jnz (PR 2))")
  (I "(Jmp32 PrintObj)")
  (L "(PR 2)")
  (I "(CmpI8 ECX 03)")
  (I "(Jnz (PR 3))")
  (I "(Jmp32 PrintImm)")
  (L "(PR 3)")
  (I "(Jmp32 PrintPair)")

  ; PrintNum: decimal via repeated div-by-10, digits pushed on the machine
  ; stack and popped back out (EBX counts them).
  (L "PrintNum")
  (I "(SarI8 EAX 02)")
  (I "(TestRR EAX EAX)")
  (I "(Jns (PN 1))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 45))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(NegR EAX)")
  (L "(PN 1)")
  (I "(XorRR EBX EBX)")
  (MOVRI "ECX" (k 10))
  (L "(PN 2)")
  (I "(XorRR EDX EDX)")
  (I "(DivR ECX)")
  (I "(AddI8 EDX 30)")
  (I "(PushR EDX)")
  (I "(IncR EBX)")
  (I "(TestRR EAX EAX)")
  (I "(Jnz (PN 2))")
  (L "(PN 3)")
  (I "(PopR EAX)")
  (call "Emit")
  (I "(DecR EBX)")
  (I "(Jnz (PN 3))")
  (I "(Ret)")

  (L "PrintPair")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 40))
  (call "Emit")
  (I "(PopR EAX)")
  (L "(PP 1)")
  (I "(PushR EAX)")
  (I "(MovRM EAX EAX)")
  (call "Print")
  (I "(PopR EAX)")
  (I "(MovRMD EAX EAX 04)")
  (I "(TestRI8 EAX 03)")
  (I "(Jnz (PP 2))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(Jmp32 (PP 1))")
  (L "(PP 2)")
  (CMPEAX (k NIL))
  (I "(Jnz (PP 3))")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")
  (L "(PP 3)")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (MOVRI "EAX" (k 46))
  (call "Emit")
  (MOVRI "EAX" (k 32))
  (call "Emit")
  (I "(PopR EAX)")
  (call "Print")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")

  (L "PrintObj")
  (I "(SubI8 EAX 02)")
  (I "(MovRM ECX EAX)")
  (I "(MovRMD EDX EAX 04)")
  (I "(SarI8 EDX 02)")
  (I "(MovRR EBX ECX)")
  (I "(AndI8 EBX 07)")
  (I "(TestRR EBX EBX)")
  (I "(Jnz (PO 1))")
  (I "(Jmp32 PrintRaw)")
  (L "(PO 1)")
  (I "(CmpI8 EBX 01)")
  (I "(Jz (PO 2))")
  (MOVRI "EAX" (k 63))
  (I "(Jmp32 Emit)")
  (L "(PO 2)")
  (MOVRI "EAX" (k 34))
  (call "Emit")
  (I "(AndI8 ECX F8)")
  (call "PrintRaw")
  (MOVRI "EAX" (k 34))
  (I "(Jmp32 Emit)")

  (L "PrintImm")
  (CMPEAX (k NIL))
  (I "(Jnz (PI 1))")
  (MOVRI "EAX" (k 40))
  (call "Emit")
  (MOVRI "EAX" (k 41))
  (I "(Jmp32 Emit)")
  (L "(PI 1)")
  (CMPEAX (k TRUE))
  (I "(Jnz (PI 2))")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 116))
  (I "(Jmp32 Emit)")
  (L "(PI 2)")
  (CMPEAX (k FALSE))
  (I "(Jnz (PI 3))")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 102))
  (I "(Jmp32 Emit)")
  (L "(PI 3)")
  (I "(MovRR ECX EAX)")
  (I (string-append "(AndI32 ECX " (x8-str (k 255)) ")"))
  (I "(CmpI8 ECX 53)")
  (I "(Jnz (PI 4))")
  (I "(PushR EAX)")
  (MOVRI "EAX" (k 35))
  (call "Emit")
  (MOVRI "EAX" (k 92))
  (call "Emit")
  (I "(PopR EAX)")
  (I "(ShrI8 EAX 08)")
  (I "(Jmp32 Emit)")
  (L "(PI 4)")
  (MOVRI "EAX" (k 63))
  (I "(Jmp32 Emit)")

  ; --- Data ---
  ; Global cells, the one-byte write buffer, and the special/prim name
  ; strings.  GPeek starts at -1 (pushback empty); CodeEnd marks where the
  ; bump arenas begin.
  (I "(Align4)")
  (data-gnames DATA-GNAMES)
  (L "GPeek")
  (I (string-append "(Dd " (x8-str wm1) ")"))
  (L "WriteChBuf")
  (I "(Db 00)")
  (string-data-specials SPECIALS)
  (string-data-prims PRIMS 0)
  (I "(Align8)")
  (L "CodeEnd"))

; ---------------------------------------------------------------------------
; Emission: the (Z n) block chain.
; ---------------------------------------------------------------------------
; A single right-nested (Ins ... (Ins ... End)) source term would nest
; thousands of parens deep -- unreadable and hostile to the seed reader.
; Instead the program is cut into 24-instruction blocks: block n becomes a
; rewrite rule (Rule (Z n) (Ins ... (Z n+1))), the last block ends in End,
; and the trailing (Assemble (Program Start bss (Z 0))) names only the
; head.  The seed's CBV evaluator expands the chain into the full
; instruction list before Assemble runs.  repeat-str closes each block's
; stack of open (Ins parens.
(define (repeat-str s n) (if (= n 0) "" (string-append s (repeat-str s (- n 1)))))
(define (take-n lst n) (if (or (= n 0) (null? lst)) '() (cons (car lst) (take-n (cdr lst) (- n 1)))))
(define (drop-n lst n) (if (or (= n 0) (null? lst)) lst (drop-n (cdr lst) (- n 1))))
(define (pl s) (begin (display s) (newline)))

(define (emit-blocks items bi)
  (if (null? items)
      #t
      (let ((blk (take-n items 24))
            (rest (drop-n items 24)))
        (begin
          (pl (string-append "(Rule (Z " (number->string bi) ")"))
          (for-each (lambda (ins) (pl (string-append "  (Ins " ins))) blk)
          (if (null? rest)
              (pl (string-append "  End" (repeat-str ")" (length blk)) ")"))
              (pl (string-append "  (Z " (number->string (+ bi 1)) ")"
                    (repeat-str ")" (length blk)) ")")))
          (emit-blocks rest (+ bi 1))))))

; Artifact header, the block chain, then the Assemble driver (bss = 256 MiB
; covering all three arenas).
(define (main)
  (begin
    (build)
    (let ((s (reverse s-rev)))
      (begin
        (pl "; scheme0: Stage 2 minimal Scheme interpreter (reader/printer).")
        (pl "; GENERATED by bootstrap/gen-scheme0.scm -- edit the generator, then")
        (pl "; regenerate. The builder is a formatter: instructions appear")
        (pl "; there 1:1, in order.")
        (emit-blocks s 0)
        (pl "")
        (pl (string-append "(Assemble (Program Start "
              (x8-str (w32-shl (k 1) 28)) " (Z 0)))"))))))

(main)
