; Opt-in, stderr-only observation of the original MesCC procedures. Shared
; module cells preserve their callers; arguments and results are unchanged.
(define (mescc-trace-event name event)
  (let ((port (current-error-port)))
    (display "mescc: " port) (display name port)
    (display " " port) (display event port)
    (if (getenv "QFITZAH_MESCC_HEAP_TRACE")
        (begin (display "; retained-8-byte-units=" port)
               (write (%gc-live-units) port)) #f)
    (display "; gc=" port) (write (gc-count) port) (newline port)))
(define (mescc-save-ast ast path)
  ; Only a completed source-built frontend may create this checkpoint. A
  ; separate completion marker prevents interrupted writes from being reused.
  (let ((marker (string-append path ".complete")))
    (if (or (file-exists? path) (file-exists? marker))
        (error 'mescc "AST checkpoint destination already exists" path) #f)
    (with-output-to-file path (lambda () (write ast) (newline)))
    (with-output-to-file marker (lambda () (display "qfitzah-mescc-ast-v1\n")))
    (mescc-trace-event 'ast-checkpoint path)))
(define (mescc-trace-procedure module-name name)
  (let* ((module (resolve-module module-name))
         (original (module-ref module name)))
    (module-define! module name
      (lambda args
        (mescc-trace-event name "begin")
        (let ((result (apply original args)))
          (mescc-trace-event name "done")
          (if (and (eq? name 'c99-input->ast) (getenv "QFITZAH_MESCC_AST_OUTPUT"))
              (mescc-save-ast result (getenv "QFITZAH_MESCC_AST_OUTPUT")) #f)
          result)))))
(for-each (lambda (name) (mescc-trace-procedure '(mescc preprocess) name))
          '(c99-input->ast c99-input->full-ast))
(mescc-trace-procedure '(mescc compile) 'c99-ast->info)
(mescc-trace-procedure '(mescc M1) 'infos->M1)
(let* ((module (resolve-module '(mescc compile)))
       (original (module-ref module 'fctn-defn->info))
       (get-name (module-ref module 'fctn-defn:get-name)))
  (module-define! module 'fctn-defn->info
    (lambda (ast info)
      (let ((name (get-name ast)))
        (mescc-trace-event name "begin")
        (let ((result (original ast info)))
          (mescc-trace-event name "done")
          result)))))
