; Port-aware Scheme reader for the Mes host. Requires the base, control,
; ports and exact-integer libraries. Deliberately separate from sc1's tiny
; bootstrap reader: the early self-hosting chain retains its small subset.
; Enabled only by the Mes host's --mes entry point. Mes accepts (. datum)
; as datum; Nyacc's make-arg-list uses this spelling for a dotted rest name.
(define %mes-source-mode #f)
(define (%reader-error message) (error 'read message))
(define (%reader-space? c)
  (and (char? c) (memv (char->integer c) '(9 10 11 12 13 32))))
(define (%reader-delimiter? c)
  (or (eof-object? c) (%reader-space? c)
      (memv c '(#\( #\) #\[ #\] #\" #\; #\' #\` #\,))))
(define (%reader-line p)
  (let ((c (read-char p)))
    (if (or (eof-object? c) (eqv? c #\newline)) #t (%reader-line p))))
(define (%reader-block p depth)
  (let ((c (read-char p)))
    (cond ((eof-object? c) (%reader-error "EOF in block comment"))
          ((and (eqv? c #\#) (eqv? (peek-char p) #\|))
           (read-char p) (%reader-block p (+ depth 1)))
          ((and (eqv? c #\|) (eqv? (peek-char p) #\#))
           (read-char p) (if (= depth 1) #t (%reader-block p (- depth 1))))
          (else (%reader-block p depth)))))
(define (%reader-script p)
  (let ((c (read-char p)))
    (cond ((eof-object? c) (%reader-error "EOF in #! comment"))
          ((and (eqv? c #\!) (eqv? (peek-char p) #\#)) (read-char p))
          (else (%reader-script p)))))
(define (%reader-skip p)
  (let ((c (peek-char p)))
    (cond ((%reader-space? c) (read-char p) (%reader-skip p))
          ((eqv? c #\;) (%reader-line p) (%reader-skip p))
          ((eqv? c #\#)
           (read-char p)
           (let ((next (peek-char p)))
             (cond ((eqv? next #\|)
                    (read-char p) (%reader-block p 1) (%reader-skip p))
                   ((eqv? next #\!)
                    (read-char p) (%reader-script p) (%reader-skip p))
                   ((eqv? next #\;)
                    (read-char p) (%reader-required p) (%reader-skip p))
                   (else (unread-char c p)))))
          (else #t))))
(define (%reader-token p acc)
  (if (%reader-delimiter? (peek-char p)) (list->string (reverse acc))
      (%reader-token p (cons (read-char p) acc))))
(define (%reader-bar-symbol p acc)
  (let ((c (read-char p)))
    (cond ((eof-object? c) (%reader-error "EOF in escaped symbol"))
          ((eqv? c #\|) (string->symbol (list->string (reverse acc))))
          ((eqv? c (integer->char 92))
           (let ((next (read-char p)))
             (if (eof-object? next) (%reader-error "EOF after symbol escape")
                 (%reader-bar-symbol p (cons next acc)))))
          (else (%reader-bar-symbol p (cons c acc))))))
(define (%reader-byte n)
  (if (and n (<= 0 n 255)) (integer->char n)
      (%reader-error "character outside byte range")))
(define (%reader-hex-digit? c)
  (and (char? c)
       (or (and (char<=? #\0 c) (char<=? c #\9))
           (and (char<=? #\a (char-downcase c)) (char<=? (char-downcase c) #\f)))))
(define (%reader-mes-hex-escape p chars)
  (let ((c (peek-char p)))
    (if (%reader-hex-digit? c)
        (begin (read-char p) (%reader-mes-hex-escape p (cons c chars)))
        (begin
          ; Accept both Mes's delimiter-terminated spelling and writer output.
          (if (eqv? c #\;) (read-char p) #f)
          (%reader-byte (string->number (list->string (reverse chars)) 16))))))
(define (%reader-hex-escape p chars)
  (if %mes-source-mode (%reader-mes-hex-escape p chars)
      (%reader-terminated-hex-escape p chars)))
(define (%reader-terminated-hex-escape p chars)
  (let ((c (read-char p)))
    (cond ((eof-object? c) (%reader-error "EOF in hex escape"))
          ((eqv? c #\;)
           (%reader-byte (string->number (list->string (reverse chars)) 16)))
          (else (%reader-hex-escape p (cons c chars))))))
(define (%reader-escape p)
  (let ((c (read-char p)))
    (cond ((eof-object? c) (%reader-error "EOF after string escape"))
          ((eqv? c #\x) (%reader-hex-escape p '()))
          (else
            (let ((code (assv c '((#\n . 10) (#\t . 9) (#\r . 13) (#\a . 7)
                                  (#\b . 8) (#\v . 11) (#\f . 12) (#\e . 27) (#\0 . 0)))))
              (if code (integer->char (cdr code)) c))))))
(define (%reader-string p acc)
  (let ((c (read-char p)))
    (cond ((eof-object? c) (%reader-error "EOF in string"))
          ((eqv? c #\") (list->string (reverse acc)))
          ((eqv? c (integer->char 92)) (%reader-string p (cons (%reader-escape p) acc)))
          (else (%reader-string p (cons c acc))))))
(define (%reader-character p)
  (let ((first (read-char p)))
    (if (eof-object? first) (%reader-error "EOF in character")
        (if (%reader-delimiter? (peek-char p)) first
            (let* ((name (%reader-token p (list first)))
                   (entry (assoc name '(("space" . 32) ("newline" . 10) ("linefeed" . 10) ("tab" . 9)
                                       ("return" . 13) ("alarm" . 7) ("backspace" . 8)
                                       ("vtab" . 11) ("page" . 12) ("escape" . 27)
                                       ("delete" . 127) ("nul" . 0) ("null" . 0)
                                       ("soh" . 1) ("stx" . 2) ("etx" . 3) ("eot" . 4)
                                       ("enq" . 5) ("ack" . 6) ("bel" . 7) ("bs" . 8)
                                       ("ht" . 9) ("lf" . 10) ("nl" . 10) ("vt" . 11) ("ff" . 12) ("np" . 12)
                                       ("cr" . 13) ("so" . 14) ("si" . 15) ("dle" . 16)
                                       ("dc1" . 17) ("dc2" . 18) ("dc3" . 19) ("dc4" . 20)
                                       ("nak" . 21) ("syn" . 22) ("etb" . 23) ("can" . 24)
                                       ("em" . 25) ("sub" . 26) ("esc" . 27) ("fs" . 28)
                                       ("gs" . 29) ("rs" . 30) ("us" . 31) ("del" . 127)))))
              (cond (entry (integer->char (cdr entry)))
                    ((eqv? first #\x)
                     (%reader-byte (string->number (substring name 1 (string-length name)) 16)))
                    (else (error 'read "unknown character name" name))))))))
(define (%reader-list p closer acc)
  (%reader-skip p)
  (let ((c (peek-char p)))
    (cond ((eof-object? c) (%reader-error "EOF in list"))
          ((eqv? c closer) (read-char p) (reverse acc))
          (else
            (let ((x (%reader-read p)))
              (if (eq? x (string->symbol "."))
                  (%reader-dotted p closer acc)
                  (%reader-list p closer (cons x acc))))))))
(define (%reader-dotted p closer acc)
  (if (and (null? acc) (not %mes-source-mode)) (%reader-error "dot before list head")
      (let ((tail (%reader-required p)))
        (%reader-skip p)
        (if (eqv? (read-char p) closer) (reverse-onto acc tail)
            (%reader-error "expected close after dotted tail")))))
(define (%reader-proper? xs)
  (cond ((null? xs) #t) ((pair? xs) (%reader-proper? (cdr xs))) (else #f)))
(define (%reader-vector p)
  (let ((xs (%reader-list p #\) '())))
    (if (%reader-proper? xs) (list->vector xs) (%reader-error "dotted vector"))))
(define (%reader-abbreviation name p)
  (list name (%reader-required p)))
(define (%reader-comma p plain splicing)
  (if (eqv? (peek-char p) #\@)
      (begin (read-char p) (%reader-abbreviation splicing p))
      (%reader-abbreviation plain p)))
(define (%reader-hash-token p c)
  (let ((token (%reader-token p (list c))))
    (cond ((or (string=? token "t") (string=? token "true")) #t)
          ((or (string=? token "f") (string=? token "false")) #f)
          (else
            (let ((n (if (eqv? c #\e)
                         (string->number (substring token 1 (string-length token)))
                         (string->number (string-append "#" token)))))
              (if n n (%reader-error "unknown # syntax")))))))
(define (%reader-hash p)
  (let ((c (read-char p)))
    (cond ((eqv? c #\() (%reader-vector p))
          ((eqv? c (integer->char 92)) (%reader-character p))
          ((eqv? c #\:)
           (let ((name (%reader-token p '())))
             (if (= (string-length name) 0) (%reader-error "empty keyword")
                 (string->symbol (string-append "#:" name)))))
          ((eqv? c #\') (%reader-abbreviation 'syntax p))
          ((eqv? c #\`) (%reader-abbreviation 'quasisyntax p))
          ((eqv? c #\,) (%reader-comma p 'unsyntax 'unsyntax-splicing))
          ((eof-object? c) (%reader-error "EOF after #"))
          (else (%reader-hash-token p c)))))
(define (%reader-atom p first)
  (let* ((token (%reader-token p (list first))) (number (string->number token)))
    (if number number (string->symbol token))))
(define (%reader-read p)
  (%reader-skip p)
  (let ((c (read-char p)))
    (cond ((eof-object? c) c)
          ((eqv? c #\() (%reader-list p #\) '()))
          ((eqv? c #\[) (%reader-list p #\] '()))
          ((or (eqv? c #\)) (eqv? c #\])) (%reader-error "unexpected closing delimiter"))
          ((eqv? c #\") (%reader-string p '()))
          ((eqv? c #\|) (%reader-bar-symbol p '()))
          ((eqv? c #\') (%reader-abbreviation 'quote p))
          ((eqv? c #\`) (%reader-abbreviation 'quasiquote p))
          ((eqv? c #\,) (%reader-comma p 'unquote 'unquote-splicing))
          ((eqv? c #\#) (%reader-hash p))
          (else (%reader-atom p c)))))
(define (%reader-required p)
  (let ((x (%reader-read p)))
    (if (eof-object? x) (%reader-error "expected datum before EOF") x)))
(define (read . rest) (%reader-read (%input-port rest)))
(define (keyword? x)
  (and (symbol? x)
       (let ((s (symbol->string x)))
         (and (> (string-length s) 2) (eqv? (string-ref s 0) #\#)
              (eqv? (string-ref s 1) #\:)))))
(define (keyword->symbol x)
  (let ((s (symbol->string x))) (string->symbol (substring s 2 (string-length s)))))
(define (symbol->keyword x) (string->symbol (string-append "#:" (symbol->string x))))
