; Scheme port layer over io.qf1. Prepend rsc-prelude.scm and rsc-control.scm.
; Port vector: tag direction kind fd buffer position limit pushback name closed.
; All mutable state is managed Scheme data and therefore visible to GC.
; File input is buffered. Output retries short writes/EINTR; no hidden output
; buffer needs flushing when a compiled program reaches its implicit exit.
(define %port-tag (list 'port))
(define (%make-port direction kind fd buffer limit name)
  (vector %port-tag direction kind fd buffer 0 limit '() name #f))
(define (port? p)
  (and (vector? p) (= (vector-length p) 10) (eq? (vector-ref p 0) %port-tag)))
(define (input-port? p) (and (port? p) (eq? (vector-ref p 1) 'input)))
(define (output-port? p) (and (port? p) (eq? (vector-ref p 1) 'output)))
(define (%check-port p direction)
  (if (and (port? p) (eq? (vector-ref p 1) direction) (not (vector-ref p 9)))
      p (error 'port "wrong direction or closed port")))
(define %stdin (%make-port 'input 'file 0 (make-string 4096) 0 "<stdin>"))
(define %stdout (%make-port 'output 'file 1 #f 0 "<stdout>"))
(define %stderr (%make-port 'output 'file 2 #f 0 "<stderr>"))
(define (current-input-port) %stdin)
(define (current-output-port) %stdout)
(define (current-error-port) %stderr)
(define (set-current-input-port p)
  (%check-port p 'input)
  (let ((old %stdin)) (set! %stdin p) old))
(define (set-current-output-port p)
  (%check-port p 'output)
  (let ((old %stdout)) (set! %stdout p) old))
(define (set-current-error-port p)
  (%check-port p 'output)
  (let ((old %stderr)) (set! %stderr p) old))
(define (%input-port rest)
  (%check-port (if (null? rest) %stdin (car rest)) 'input))
(define (%output-port rest)
  (%check-port (if (null? rest) %stdout (car rest)) 'output))
(define (port-filename p) (vector-ref p 8))
(define (set-port-filename! p name) (vector-set! p 8 name))
(define (port-closed? p) (vector-ref p 9))
(define (fileno p) (vector-ref p 3))

(define (%check-path path i)
  (if (= i (string-length path)) #t
      (if (= (char->integer (string-ref path i)) 0)
          (error 'open-file "NUL in filename")
          (%check-path path (+ i 1)))))
(define (%open-file path direction flags)
  (%check-path path 0)
  (let ((fd (%file-open path flags 438))) ; 0666, subject to process umask
    (if (< fd 0) (error 'open-file path fd)
        (%make-port direction 'file fd
                    (if (eq? direction 'input) (make-string 4096) #f) 0 path))))
(define (open-input-file path) (%open-file path 'input 0))
(define (open-output-file path) (%open-file path 'output 577)) ; WRONLY|CREAT|TRUNC
(define (open-file path mode)
  (cond ((string=? mode "r") (open-input-file path))
        ((string=? mode "w") (open-output-file path))
        ((string=? mode "a") (%open-file path 'output 1089))
        (else (error 'open-file "unsupported mode" mode))))
(define (close-port p)
  (if (not (port? p)) (error 'close-port "not a port")
      (if (vector-ref p 9) #f
          (begin
            ; Mark closed even on failure: retrying close after EINTR can
            ; accidentally close a different descriptor on some systems.
            (vector-set! p 9 #t)
            (if (eq? (vector-ref p 2) 'file)
                (let ((r (%file-close (vector-ref p 3))))
                  (if (< r 0) (error 'close-port r) #t))
                #t)))))
(define close-input-port close-port)
(define close-output-port close-port)
(define (open-input-string s)
  (%make-port 'input 'string -1 s (string-length s) "<string>"))
(define (open-output-string)
  (%make-port 'output 'string -1 (make-string 128) 0 "<string>"))
(define (get-output-string p)
  (if (and (output-port? p) (eq? (vector-ref p 2) 'string))
      (substring (vector-ref p 4) 0 (vector-ref p 5))
      (error 'get-output-string "not a string output port")))

(define (%refill p)
  (if (eq? (vector-ref p 2) 'string) 0
      (let ((n (%file-read (vector-ref p 3) (vector-ref p 4) 0 4096)))
        (cond ((= n -4) (%refill p))
              ((< n 0) (error 'read-char (port-filename p) n))
              (else (vector-set! p 5 0) (vector-set! p 6 n) n)))))
(define (%read-buffered p)
  (let ((i (vector-ref p 5)))
    (if (< i (vector-ref p 6))
        (begin (vector-set! p 5 (+ i 1)) (string-ref (vector-ref p 4) i))
        (if (= (%refill p) 0) (%eof-object) (%read-buffered p)))))
(define (read-char . rest)
  (let ((p (%input-port rest)))
    (let ((pending (vector-ref p 7)))
      (if (null? pending) (%read-buffered p)
          (begin (vector-set! p 7 (cdr pending)) (car pending))))))
(define (unread-char c . rest)
  (let ((p (%input-port rest)))
    (if (char? c) (vector-set! p 7 (cons c (vector-ref p 7)))
        (error 'unread-char "not a character"))))
(define (peek-char . rest)
  (let ((p (%input-port rest)))
    (let ((c (read-char p)))
      (if (eof-object? c) c (begin (unread-char c p) c)))))

; Copy loops avoid conversion through character lists and bounded token space.
(define (%copy-string! source start end target offset)
  (if (= start end) #t
      (begin (string-set! target offset (string-ref source start))
             (%copy-string! source (+ start 1) end target (+ offset 1)))))
(define (%grow-output p required)
  (let ((old (vector-ref p 4)))
    (if (> required (string-length old))
        (let ((new (make-string (max required (* 2 (string-length old))))))
          (%copy-string! old 0 (vector-ref p 5) new 0)
          (vector-set! p 4 new))
        #f)))
(define (%write-file fd s start count)
  (if (= count 0) #t
      (let ((n (%file-write fd s start count)))
        (cond ((= n -4) (%write-file fd s start count))
              ((<= n 0) (error 'write "failed write" n))
              (else (%write-file fd s (+ start n) (- count n)))))))
(define (%write-string s p)
  (if (eq? (vector-ref p 2) 'file)
      (%write-file (vector-ref p 3) s 0 (string-length s))
      (let ((i (vector-ref p 5)) (n (string-length s)))
        (%grow-output p (+ i n))
        (%copy-string! s 0 n (vector-ref p 4) i)
        (vector-set! p 5 (+ i n)))))
(define (write-char c . rest)
  (%write-string (string c) (%output-port rest)))
(define (newline . rest) (%write-string "\n" (%output-port rest)))
(define (force-output . rest) (%output-port rest) #t)

; Reader-compatible printing. Keep dispatch separate from sequence traversal.
(define (%write-escaped s p i)
  (if (= i (string-length s)) #t
      (let ((c (string-ref s i)))
        (%write-string
          (cond ((eq? c #\") "\\\"")
                ((eq? c (integer->char 92)) "\\\\")
                ((eq? c #\newline) "\\n")
                ((eq? c #\tab) "\\t")
                ((eq? c (integer->char 13)) "\\r")
                ((or (< (char->integer c) 32) (>= (char->integer c) 127))
                 (string-append "\\x" (number->string (char->integer c) 16) ";"))
                (else (string c))) p)
        (%write-escaped s p (+ i 1)))))
(define (%write-list tail p quoted?)
  (cond ((null? tail) (%write-string ")" p))
        ((pair? tail)
         (%write-string " " p)
         (%print (car tail) p quoted?)
         (%write-list (cdr tail) p quoted?))
        (else (%write-string " . " p) (%print tail p quoted?) (%write-string ")" p))))
(define (%write-vector v p quoted? i)
  (if (= i (vector-length v)) (%write-string ")" p)
      (begin (if (= i 0) #f (%write-string " " p))
             (%print (vector-ref v i) p quoted?)
             (%write-vector v p quoted? (+ i 1)))))
(define (%write-character c p)
  (%write-string "#\\" p)
  (%write-string (cond ((eq? c #\space) "space")
                       ((eq? c #\newline) "newline")
                       ((eq? c #\tab) "tab")
                       ((eq? c (integer->char 13)) "return")
                       ((or (< (char->integer c) 32) (>= (char->integer c) 127))
                        (string-append "x" (number->string (char->integer c) 16)))
                       (else (string c))) p))
(define (%symbol-special-char? c)
  (or (char-whitespace? c)
      (memv c '(#\( #\) #\[ #\] #\" #\; #\' #\` #\, #\|))
      (= (char->integer c) 92)))
(define (%symbol-special? s i)
  (if (= i (string-length s)) #f
      (or (%symbol-special-char? (string-ref s i)) (%symbol-special? s (+ i 1)))))
(define (%symbol-escape? s)
  (or (= (string-length s) 0) (string=? s ".") (%symbol-special? s 0)
      (and (> (string-length s) 0)
           (let ((c (string-ref s 0)))
             (or (char-numeric? c)
                 (and (memv c '(#\+ #\-)) (> (string-length s) 1)
                      (char-numeric? (string-ref s 1)))
                 (and (eqv? c #\#)
                      (not (and (> (string-length s) 2) (eqv? (string-ref s 1) #\:)))))))))
(define (%write-symbol-chars s p i)
  (if (= i (string-length s)) #t
      (let ((c (string-ref s i)))
        (if (or (eqv? c #\|) (= (char->integer c) 92)) (%write-string "\\" p) #f)
        (%write-string (string c) p)
        (%write-symbol-chars s p (+ i 1)))))
(define (%write-symbol x p quoted?)
  (let ((s (symbol->string x)))
    (if (and quoted? (%symbol-escape? s))
        (begin (%write-string "|" p) (%write-symbol-chars s p 0) (%write-string "|" p))
        (%write-string s p))))
(define (%print x p quoted?)
  (cond ((string? x)
         (if quoted?
             (begin (%write-string "\"" p) (%write-escaped x p 0) (%write-string "\"" p))
             (%write-string x p)))
        ((char? x) (if quoted? (%write-character x p) (%write-string (string x) p)))
        ((number? x) (%write-string (number->string x) p))
        ((symbol? x) (%write-symbol x p quoted?))
        ((null? x) (%write-string "()" p))
        ((pair? x)
         (%write-string "(" p) (%print (car x) p quoted?) (%write-list (cdr x) p quoted?))
        ((boolean? x) (%write-string (if x "#t" "#f") p))
        ((port? x) (%write-string "#<port>" p))
        ((vector? x) (%write-string "#(" p) (%write-vector x p quoted? 0))
        ((eof-object? x) (%write-string "#<eof>" p))
        ((procedure? x) (%write-string "#<procedure>" p))
        (else (%write-string "#<unspecified>" p))))
(define (write x . rest) (%print x (%output-port rest) #t))
(define (display x . rest) (%print x (%output-port rest) #f))

(define (%call-with-port p proc)
  (dynamic-wind (lambda () #t) (lambda () (proc p)) (lambda () (close-port p))))
(define (call-with-input-file path proc)
  (%call-with-port (open-input-file path) proc))
(define (call-with-output-file path proc)
  (%call-with-port (open-output-file path) proc))
(define (call-with-input-string s proc)
  (let ((p (open-input-string s)))
    (let ((r (proc p))) (close-port p) r)))
(define (call-with-output-string proc)
  (let ((p (open-output-string)))
    (proc p)
    (get-output-string p)))
(define (with-input-from-port p thunk)
  (let ((old (current-input-port)))
    (dynamic-wind (lambda () (set-current-input-port p)) thunk
                  (lambda () (set-current-input-port old)))))
(define (with-output-to-port p thunk)
  (let ((old (current-output-port)))
    (dynamic-wind (lambda () (set-current-output-port p)) thunk
                  (lambda () (set-current-output-port old)))))
(define (with-input-from-file path thunk)
  (call-with-input-file path (lambda (p) (with-input-from-port p thunk))))
(define (with-output-to-file path thunk)
  (call-with-output-file path (lambda (p) (with-output-to-port p thunk))))
(define (with-output-to-string thunk)
  (call-with-output-string (lambda (p) (with-output-to-port p thunk))))

; Fatal errors belong on stderr; a failed stderr write falls back once to the
; native fatal handler rather than recursively trying to report itself.
(set! %unhandled-exception
  (lambda (key args)
    (set! %unhandled-exception (lambda (k xs) (apply %fatal-error (cons k xs))))
    (display "rsc: " (current-error-port))
    (write (cons key args) (current-error-port))
    (newline (current-error-port))
    (exit 1)))
