; Exact integers implemented in Scheme rather than opaque host code.
; Compile with rsc after the base prelude. Small results stay native fixnums;
; larger ones are sign/magnitude records with little-endian base-2^14 limbs.
; A limb product plus carry fits safely in a signed 30-bit fixnum.
(define %fx+ +) (define %fx- -) (define %fx* *)
(define %fxquot quotient) (define %fxrem remainder)
(define %fx< <) (define %fx= =) (define %fx? number?)
(define %raw-eqv? eqv?)
(define %integer-tag (list 'exact-integer))
(define (%big? n)
  (and (vector? n) (%fx= (vector-length n) 3)
       (eq? (vector-ref n 0) %integer-tag)))
(define (number? n) (or (%fx? n) (%big? n)))
(define integer? number?)
(define exact? number?)
(define rational? number?)
(define real? number?)
(define complex? number?)
(define (%integer-check n)
  (if (number? n) n (error 'arithmetic "expected exact integer" n)))
(define (%negative? n) (if (%fx? n) (%fx< n 0) (vector-ref n 1)))
(define (%fx-abs n) (if (%fx< n 0) (%fx- 0 n) n))
(define (%fx-limbs n)
  (if (%fx= n 0) '()
      (cons (%fx-abs (%fxrem n 16384)) (%fx-limbs (%fxquot n 16384)))))
(define (%limbs n) (if (%fx? n) (%fx-limbs n) (vector-ref n 2)))
(define (%trim-high xs)
  (if (and (pair? xs) (%fx= (car xs) 0)) (%trim-high (cdr xs)) xs))
(define (%trim xs) (reverse (%trim-high (reverse xs))))
(define (%mag-cmp-equal a b)
  (if (null? a) 0
      (let ((rest (%mag-cmp-equal (cdr a) (cdr b))))
        (cond ((not (%fx= rest 0)) rest)
              ((%fx< (car a) (car b)) -1)
              ((%fx= (car a) (car b)) 0)
              (else 1)))))
(define (%mag-cmp a b)
  (let ((na (length a)) (nb (length b)))
    (cond ((%fx< na nb) -1) ((%fx< nb na) 1)
          (else (%mag-cmp-equal a b)))))
(define (%negative-acc digits acc)
  (if (null? digits) acc
      (%negative-acc (cdr digits) (%fx- (%fx* acc 16384) (car digits)))))
(define (%integer negative? limbs)
  (let ((digits (%trim limbs)))
    (cond ((null? digits) 0)
          ((%fx< (%mag-cmp digits (if negative? '(0 0 2) '(16383 16383 1))) 1)
           (let ((n (%negative-acc (reverse digits) 0)))
             (if negative? n (%fx- 0 n))))
          (else (vector %integer-tag negative? digits)))))
(define (%digit xs) (if (null? xs) 0 (car xs)))
(define (%rest xs) (if (null? xs) '() (cdr xs)))
(define (%mag-add a b carry)
  (if (and (null? a) (null? b)) (if (%fx= carry 0) '() (list carry))
      (let ((n (%fx+ (%fx+ (%digit a) (%digit b)) carry)))
        (cons (%fxrem n 16384) (%mag-add (%rest a) (%rest b) (%fxquot n 16384))))))
; Requires magnitude a >= b.
(define (%mag-sub a b borrow)
  (if (null? a) '()
      (let* ((n (%fx- (%fx- (car a) (%digit b)) borrow)) (negative? (%fx< n 0)))
        (cons (if negative? (%fx+ n 16384) n)
              (%mag-sub (cdr a) (%rest b) (if negative? 1 0))))))
(define (%signed-add a b)
  (let ((sa (%negative? a)) (sb (%negative? b)) (la (%limbs a)) (lb (%limbs b)))
    (if (eq? sa sb) (%integer sa (%mag-add la lb 0))
        (if (%fx< (%mag-cmp la lb) 0)
            (%integer sb (%mag-sub lb la 0))
            (%integer sa (%mag-sub la lb 0))))))
(define (%add a b)
  (%integer-check a) (%integer-check b)
  (if (and (%fx? a) (%fx? b)
           (if (%fx< b 0) (not (%fx< a (%fx- -536870912 b)))
               (not (%fx< (%fx- 536870911 b) a))))
      (%fx+ a b) (%signed-add a b)))
(define (%negate n)
  (%integer-check n)
  (if (and (%fx? n) (not (%fx= n -536870912))) (%fx- 0 n)
      (%integer (not (%negative? n)) (%limbs n))))
(define (%mag-scale xs digit carry)
  (if (null? xs) (if (%fx= carry 0) '() (list carry))
      (let ((n (%fx+ (%fx* (car xs) digit) carry)))
        (cons (%fxrem n 16384) (%mag-scale (cdr xs) digit (%fxquot n 16384))))))
(define (%mag-multiply a b result)
  (if (null? b) result
      (%mag-multiply (cons 0 a) (cdr b) (%mag-add result (%mag-scale a (car b) 0) 0))))
(define (%multiply a b)
  (%integer-check a) (%integer-check b)
  (cond ((or (eqv? a 0) (eqv? b 0)) 0)
        ((and (%fx? a) (%fx? b)
              (not (%fx= a -536870912)) (not (%fx= b -536870912))
              (not (%fx< (%fxquot 536870911 (%fx-abs b)) (%fx-abs a))))
         (%fx* a b))
        (else (%integer (not (eq? (%negative? a) (%negative? b)))
                        (%mag-multiply (%limbs a) (%limbs b) '())))))
(define (%fold-integers op acc xs)
  (if (null? xs) acc (%fold-integers op (op acc (car xs)) (cdr xs))))
(define (+ . xs) (%fold-integers %add 0 xs))
(define (* . xs) (%fold-integers %multiply 1 xs))
(define (- n . xs)
  (if (null? xs) (%negate n)
      (%fold-integers (lambda (a b) (%add a (%negate b))) n xs)))

; Unsigned binary long division. No machine-width intermediate is needed.
(define (%half-high xs carry acc)
  (if (null? xs) (%trim acc)
      (let ((n (%fx+ (%fx* carry 16384) (car xs))))
        (%half-high (cdr xs) (%fxrem n 2) (cons (%fxquot n 2) acc)))))
(define (%mag-half xs) (%half-high (reverse xs) 0 '()))
(define (%divide-bits a divisor bit q)
  (if (null? bit) (cons (%trim q) (%trim a))
      (if (%fx< (%mag-cmp a divisor) 0)
          (%divide-bits a (%mag-half divisor) (%mag-half bit) q)
          (%divide-bits (%trim (%mag-sub a divisor 0)) (%mag-half divisor)
                        (%mag-half bit) (%mag-add q bit 0)))))
(define (%scale-divisor a divisor bit)
  (if (%fx< (%mag-cmp a divisor) 0)
      (%divide-bits a divisor bit '())
      (%scale-divisor a (%mag-add divisor divisor 0) (%mag-add bit bit 0))))
(define (%division a b remainder?)
  (%integer-check a) (%integer-check b)
  (if (eqv? b 0) (error 'quotient "division by zero")
      (if (and (%fx? a) (%fx? b) (not (and (%fx= a -536870912) (%fx= b -1))))
          (if remainder? (%fxrem a b) (%fxquot a b))
          (let ((qr (%scale-divisor (%limbs a) (%limbs b) '(1))))
            (if remainder? (%integer (%negative? a) (cdr qr))
                (%integer (not (eq? (%negative? a) (%negative? b))) (car qr)))))))
(define (quotient a b) (%division a b #f))
(define (remainder a b) (%division a b #t))
(define (%compare a b)
  (%integer-check a) (%integer-check b)
  (if (and (%fx? a) (%fx? b))
      (cond ((%fx< a b) -1) ((%fx= a b) 0) (else 1))
      (let ((sa (%negative? a)) (sb (%negative? b)))
        (if (not (eq? sa sb)) (if sa -1 1)
            (let ((c (%mag-cmp (%limbs a) (%limbs b))))
              (if sa (%fx- 0 c) c))))))
(define (%compare-chain predicate a xs)
  (if (null? xs) #t
      (and (predicate (%compare a (car xs)))
           (%compare-chain predicate (car xs) (cdr xs)))))
(define (= a . xs) (%compare-chain (lambda (c) (%fx= c 0)) a xs))
(define (< a . xs) (%compare-chain (lambda (c) (%fx< c 0)) a xs))
(define (> a . xs) (%compare-chain (lambda (c) (%fx< 0 c)) a xs))
(define (<= a . xs) (%compare-chain (lambda (c) (not (%fx< 0 c))) a xs))
(define (>= a . xs) (%compare-chain (lambda (c) (not (%fx< c 0))) a xs))
(define (eqv? a b)
  (if (and (number? a) (number? b)) (%fx= (%compare a b) 0) (%raw-eqv? a b)))

; Infinite two's-complement operations, including negative operands.
(define (%low-bit n) (modulo n 2))
(define (%shift-right-one n) (quotient (- n (%low-bit n)) 2))
(define (%bitwise op a b)
  (let ((x (%low-bit a)) (y (%low-bit b)))
    (if (and (or (= a 0) (= a -1)) (or (= b 0) (= b -1)))
        (if (= (op x y) 0) 0 -1)
        (+ (* 2 (%bitwise op (%shift-right-one a) (%shift-right-one b))) (op x y)))))
(define (%and-bit x y) (if (and (= x 1) (= y 1)) 1 0))
(define (%or-bit x y) (if (or (= x 1) (= y 1)) 1 0))
(define (%xor-bit x y) (if (= x y) 0 1))
(define (logand . xs) (%fold-integers (lambda (a b) (%bitwise %and-bit a b)) -1 xs))
(define (logior . xs) (%fold-integers (lambda (a b) (%bitwise %or-bit a b)) 0 xs))
(define (logxor . xs) (%fold-integers (lambda (a b) (%bitwise %xor-bit a b)) 0 xs))
(define (lognot n) (- -1 n))
(define (ash n count)
  (cond ((= count 0) n)
        ((< count 0) (ash (%shift-right-one n) (+ count 1)))
        (else (ash (* n 2) (- count 1)))))
(define bitwise-and logand)
(define bitwise-ior logior)
(define bitwise-xor logxor)
(define bitwise-not lognot)
(define bitwise-arithmetic-shift ash)

(define (%digit-value c)
  (let ((n (char->integer (char-downcase c))))
    (cond ((and (>= n 48) (<= n 57)) (- n 48))
          ((and (>= n 97) (<= n 122)) (- n 87))
          (else #f))))
(define (%parse-digits s i radix acc negative?)
  (if (= i (string-length s)) (if negative? (- acc) acc)
      (let ((d (%digit-value (string-ref s i))))
        (if (and d (< d radix))
            (%parse-digits s (+ i 1) radix (+ (* acc radix) d) negative?) #f))))
(define (%parse-signed s start radix)
  (if (= start (string-length s)) #f
      (let* ((c (string-ref s start)) (sign? (or (eq? c #\-) (eq? c #\+)))
             (i (if sign? (+ start 1) start)))
        (if (= i (string-length s)) #f (%parse-digits s i radix 0 (eq? c #\-))))))
(define (string->number s . rest)
  (let ((radix (if (null? rest) 10 (car rest))))
    (if (or (< radix 2) (> radix 36)) #f
        (if (and (> (string-length s) 1) (eq? (string-ref s 0) #\#))
            (let ((r (case (char-downcase (string-ref s 1))
                       ((#\b) 2) ((#\o) 8) ((#\d) 10) ((#\x) 16) (else #f))))
              (if r (%parse-signed s 2 r) #f))
            (%parse-signed s 0 radix)))))
