; rsc standard-library prelude. This is a fixed block of Scheme source that is
; prepended (by the build/test harness) to every program rsc compiles, so a
; user program can rely on the R5RS library procedures below. It is a separate
; compilation unit rather than data embedded in rsc.scm: embedding it as a
; quoted literal bloated the self-hosted compiler's static data and its seed
; assembly time, so rsc stays lean and the prelude is prepended as text.
; Everything here is written in the sc1 core subset atop the runtime primitives.
(define (list . xs) xs)
(define (caar x) (car (car x)))
(define (cadr x) (car (cdr x)))
(define (cdar x) (cdr (car x)))
(define (cddr x) (cdr (cdr x)))
(define (caddr x) (car (cddr x)))
(define (cdddr x) (cdr (cddr x)))
(define (cadddr x) (car (cdddr x)))
(define (not x) (if x #f #t))
(define (append2* a b) (if (null? a) b (cons (car a) (append2* (cdr a) b))))
(define (append-list ls)
  (cond ((null? ls) '())
        ((null? (cdr ls)) (car ls))
        (else (append2* (car ls) (append-list (cdr ls))))))
(define (append . ls) (append-list ls))
(define (reverse-onto l acc) (if (null? l) acc (reverse-onto (cdr l) (cons (car l) acc))))
(define (reverse l) (reverse-onto l '()))
(define (length-acc l n) (if (null? l) n (length-acc (cdr l) (+ n 1))))
(define (length l) (length-acc l 0))
(define (list-tail l k) (if (= k 0) l (list-tail (cdr l) (- k 1))))
(define (list-ref l k) (car (list-tail l k)))
(define (%any-list-null? lists)
  (and (pair? lists) (or (null? (car lists)) (%any-list-null? (cdr lists)))))
(define (%list-heads lists)
  (if (null? lists) '() (cons (caar lists) (%list-heads (cdr lists)))))
(define (%list-tails lists)
  (if (null? lists) '() (cons (cdar lists) (%list-tails (cdr lists)))))
(define (%map-lists f lists)
  (if (%any-list-null? lists) '()
      (cons (apply f (%list-heads lists)) (%map-lists f (%list-tails lists)))))
(define (map f l . more) (%map-lists f (cons l more)))
(define (%for-each-lists f lists)
  (if (%any-list-null? lists) #f
      (begin (apply f (%list-heads lists)) (%for-each-lists f (%list-tails lists)))))
(define (for-each f l . more) (%for-each-lists f (cons l more)))
(define (equal? a b)
  (cond ((and (pair? a) (pair? b))
         (and (equal? (car a) (car b)) (equal? (cdr a) (cdr b))))
        ((and (string? a) (string? b)) (string=? a b))
        ((and (vector? a) (vector? b)) (equal? (vector->list a) (vector->list b)))
        (else (eqv? a b))))
(define (memq x l)
  (let ((result (%memq x l)))
    (if (eq? result -1) (error 'memq "malformed list") result)))
; Canonical bignums never equal a fixnum: only vector-backed values can be
; eqv? without raw identity in this runtime. Keep their numerical path.
(define (%memv-slow x l)
  (cond ((null? l) #f)
        ((not (pair? l)) (error 'memv "malformed list"))
        ((eqv? x (car l)) l) (else (%memv-slow x (cdr l)))))
(define (memv x l) (if (vector? x) (%memv-slow x l) (memq x l)))
(define (member x l) (cond ((null? l) #f) ((equal? x (car l)) l) (else (member x (cdr l)))))
(define (assq x l)
  (let ((result (%assq x l)))
    (if (eq? result -1) (error 'assq "malformed association list") result)))
(define (%assv-slow x l)
  (cond ((null? l) #f)
        ((or (not (pair? l)) (not (pair? (car l))))
         (error 'assv "malformed association list"))
        ((eqv? x (caar l)) (car l)) (else (%assv-slow x (cdr l)))))
(define (assv x l) (if (vector? x) (%assv-slow x l) (assq x l)))
(define (assoc x l) (cond ((null? l) #f) ((equal? x (caar l)) (car l)) (else (assoc x (cdr l)))))
(define (zero? n) (= n 0))
(define (positive? n) (> n 0))
(define (negative? n) (< n 0))
(define (abs n) (if (< n 0) (- 0 n) n))
(define (even? n) (= (remainder n 2) 0))
(define (odd? n) (not (even? n)))
(define (modulo a b)
  (let ((r (remainder a b)))
    (if (= r 0) 0 (if (eq? (< r 0) (< b 0)) r (+ r b)))))
(define (min a . r) (min-list a r))
(define (min-list a r) (if (null? r) a (min-list (if (< (car r) a) (car r) a) (cdr r))))
(define (max a . r) (max-list a r))
(define (max-list a r) (if (null? r) a (max-list (if (> (car r) a) (car r) a) (cdr r))))
(define (gcd a b) (if (= b 0) (abs a) (gcd b (remainder a b))))
; Negate only a single digit, not the minimum negative fixnum itself.
(define (number-digits n radix acc)
  (if (= n 0) acc
      (number-digits (quotient n radix) radix
        (cons (string-ref "0123456789abcdefghijklmnopqrstuvwxyz"
                          (abs (remainder n radix))) acc))))
(define (number->string n . rest)
  (let ((radix (if (null? rest) 10 (car rest))))
    (if (or (< radix 2) (> radix 36)) (error 'number->string "invalid radix")
        (let ((digits (if (= n 0) (list #\0) (number-digits n radix '()))))
          (list->string (if (< n 0) (cons #\- digits) digits))))))
(define (char=? a b) (= (char->integer a) (char->integer b)))
(define (char<? a b) (< (char->integer a) (char->integer b)))
(define (char>? a b) (< (char->integer b) (char->integer a)))
(define (char<=? a b) (not (< (char->integer b) (char->integer a))))
(define (char>=? a b) (not (< (char->integer a) (char->integer b))))
(define (char-upper? c) (let ((i (char->integer c))) (and (> i 64) (< i 91))))
(define (char-lower? c) (let ((i (char->integer c))) (and (> i 96) (< i 123))))
(define (char-alphabetic? c) (or (char-upper? c) (char-lower? c)))
(define (char-numeric? c) (let ((i (char->integer c))) (and (> i 47) (< i 58))))
(define (char-whitespace? c)
  (let ((i (char->integer c))) (or (= i 32) (= i 9) (= i 10) (= i 13))))
(define (char-upcase c) (if (char-lower? c) (integer->char (- (char->integer c) 32)) c))
(define (char-downcase c) (if (char-upper? c) (integer->char (+ (char->integer c) 32)) c))
(define (str->list-loop s i n) (if (= i n) '() (cons (string-ref s i) (str->list-loop s (+ i 1) n))))
(define (string->list s) (str->list-loop s 0 (string-length s)))
(define (string . cs) (list->string cs))
(define (string-append . ss) (list->string (append-list (map string->list ss))))
(define (sub-loop s a b) (if (< a b) (cons (string-ref s a) (sub-loop s (+ a 1) b)) '()))
(define (substring s a b) (list->string (sub-loop s a b)))
(define (string-copy s) (substring s 0 (string-length s)))
(define (str-eq a b i n)
  (if (= i n) #t (and (char=? (string-ref a i) (string-ref b i)) (str-eq a b (+ i 1) n))))
(define (string=? a b)
  (and (= (string-length a) (string-length b)) (str-eq a b 0 (string-length a))))
(define (str-lt a b i na nb)
  (cond ((= i na) (< na nb))
        ((= i nb) #f)
        ((char<? (string-ref a i) (string-ref b i)) #t)
        ((char>? (string-ref a i) (string-ref b i)) #f)
        (else (str-lt a b (+ i 1) na nb))))
(define (string<? a b) (str-lt a b 0 (string-length a) (string-length b)))
(define (vfill v x i n) (if (< i n) (begin (vector-set! v i x) (vfill v x (+ i 1) n)) #f))
(define (vector-fill! v x) (vfill v x 0 (vector-length v)))
