(define a (make-symbol "same"))
(define b (make-symbol "same"))
(write (list (symbol? a) (eq? a b) (eq? a 'same) (symbol->string a))) (newline)
(define text (string-copy "copied"))
(define copied (make-symbol text))
(string-set! text 0 #\X)
(write copied) (newline)
(write (map + '(1 2) '(10 20) '(100 200))) (newline)
(define total 0)
(for-each (lambda (x y) (set! total (+ total x y))) '(1 2) '(10 20))
(write total) (newline)
(define-syntax with-temp
  (lambda (form rename compare)
    (list (rename 'let) (list (list (rename 'temp) 5)) (cadr form))))
(write (let ((temp 99)) (with-temp temp))) (newline)
(define-syntax quote-word
  (lambda (form rename compare) (list (rename 'quote) (rename 'secret))))
(write (quote-word)) (newline)
(write (let-syntax ((constant (lambda (form rename compare) 17))) (constant))) (newline)
(define cyclic (list 1))
(set-cdr! cyclic cyclic)
(write (eq? cyclic (eval (list 'quote cyclic)))) (newline)
(gc)
(write (symbol->string a)) (newline)
(write (let ((lexical 4)) (eval 'lexical (current-environment)))) (newline)
(write (catch 'misc-error (lambda () (read (open-input-string "(. x)")))
         (lambda args 'dot-rejected))) (newline)
(write (catch 'misc-error (lambda () (if #t 1 2 3))
         (lambda args 'if-rejected))) (newline)
