(define* (options a #:optional (b (+ a 1)) #:key (c (+ b 1)) verbose?)
  (list a b c verbose?))
(write (options 1)) (newline)
(write (options 1 10 #:c 20 #:verbose? #t)) (newline)
(write (options 1 #:verbose? #f)) (newline)
(write ((lambda* (a #:rest rest) (cons a rest)) 1 2 3)) (newline)
(write ((lambda* (#:key (a 5) #:allow-other-keys) a) #:unknown 7)) (newline)
(write (catch 'misc-error (lambda () (options 1 #:unknown 0)) (lambda args 'keyword-caught))) (newline)
(write (do ((i 0 (+ i 1)) (sum 0 (+ sum i))) ((= i 10) sum))) (newline)
(define forced 0)
(define promise (delay (begin (set! forced (+ forced 1)) 42)))
(write (list (force promise) (force promise) forced)) (newline)
(defmacro increment (name) `(set! ,name (+ ,name 1)))
(increment forced)
(write forced) (newline)
(define choices (case-lambda (() 'zero) ((x) x) ((x y . rest) (list x y rest))))
(write (list (choices) (choices 7) (choices 1 2 3 4))) (newline)
(write (catch 'misc-error (lambda () ((case-lambda ((x) x)) 1 2))
         (lambda args 'case-arity-caught))) (newline)
(define fluid-a (make-fluid 'outer))
(define fluid-b (make-fluid 'initial))
(write (with-fluids ((fluid-a 'inner) (fluid-b (fluid-ref fluid-a)))
         (list (fluid-ref fluid-a) (fluid-ref fluid-b)))) (newline)
(write (list (fluid-ref fluid-a) (fluid-ref fluid-b))) (newline)
(write (catch 'stop
         (lambda () (with-fluids ((fluid-a 'temporary)) (throw 'stop)))
         (lambda args (fluid-ref fluid-a)))) (newline)
(write (with-fluids ((fluid-a 'first) (fluid-a 'last)) (fluid-ref fluid-a))) (newline)
(write (fluid-ref fluid-a)) (newline)
(let ((saved #f) (round 0) (out '()))
  (let ((value (with-fluids ((fluid-a 'inside))
                 (let ((answer (call/cc (lambda (k) (set! saved k) 'first))))
                   (list answer (fluid-ref fluid-a))))))
    (set! out (cons (list value (fluid-ref fluid-a)) out))
    (if (= round 0) (begin (set! round 1) (saved 'again)) #f)
    (write (reverse out)) (newline)))
