(use-modules (mescc info) (srfi srfi-9 gnu))
(define int-type (make-type 'builtin 4 #f))
(write (list (type? int-type) (type:size int-type))) (newline)
(define pointer (make-pointer int-type 2))
(define smaller (rank-- pointer))
(write (list (type? pointer) (pointer:rank pointer) (pointer:rank smaller))) (newline)
(define info (make <info> #:pushed 2))
(define changed (clone info #:pushed 3))
(write (list (.pushed info) (.pushed changed))) (newline)
(define changed-again (set-fields info ((.pushed) 7) ((.locals) '(local))))
(write (list (.pushed changed-again) (.locals changed-again) (.pushed info))) (newline)
