(use-modules ((example counter) #:prefix c:))
(c:twice (c:increment!))
(write c:count) (newline)
(write c:twice) (newline)
(use-modules ((example counter) #:select ((increment! . bump) count)))
(bump)
(write (list count c:count)) (newline)
(define count 99)
(write (list count c:count)) (newline)
(write ((@ (guile) iota) 3)) (newline)
(write (c:access-private 1)) (newline)
(c:define-created created)
(write created) (newline)
(define (counter-private x) 999)
(write (c:access-private 1)) (newline)
(write (catch 'misc-error
         (lambda () (use-modules ((example counter) #:select (private))))
         (lambda args 'private-rejected))) (newline)
(use-modules (example a))
(write (from-b)) (newline)
(write (defined? 'private)) (newline)
(define-record-type <first> (make-first value) first? (value first-value set-first-value!))
(define-record-type <second> (make-second value) second? (value second-value))
(define r (make-first 10))
(set-first-value! r 20)
(write (list (first? r) (second? r) (first-value r))) (newline)
(write (catch 'misc-error (lambda () (second-value r)) (lambda args 'type-rejected))) (newline)
