(write (iota 3 4 -2)) (newline)
(define left (list 1 2))
(define right (list 3 4))
(append! left right)
(write (list left (eq? (cddr left) right))) (newline)
(write (delete! 2 (list 2 1 2 3 2))) (newline)
(write (simple-format #f "~a ~s ~x ~~" 'item "q" 255)) (newline)
(write (catch 'misc-error (lambda () (simple-format #f "~z" 1))
         (lambda args 'unsupported-control))) (newline)
(write (vector-copy '#(1 2 3) 1)) (newline)
(write (reverse-list->string '(#\b #\a))) (newline)
(define chars (string->char-set "ab"))
(define copy (string->char-set "c" chars))
(write (list (char-set-contains? chars #\a) (char-set-contains? chars #\c)
             (char-set-contains? copy #\c) (char-set= (char-set #\b #\a) chars))) (newline)
(string->char-set! "z" chars)
(write (list (char-set-contains? chars #\z) (char-set-contains? copy #\z))) (newline)
(write (char-set-contains? chars (read (open-input-string "")))) (newline)
(write (map char->integer '(#\bel #\bs #\cr #\vt #\del #\nl #\np #\linefeed))) (newline)
(define (iota ignored) 'polluted)
(use-modules (example core))
(write answer) (newline)
(setenv "QFITZAH_TEST_LOCAL" "value")
(write (getenv "QFITZAH_TEST_LOCAL")) (newline)
(write (list (basename "/a/b.c/") (basename "/a/b.c" ".c") (basename "/"))) (newline)
(write (list (string-suffix? ".new" "file.new") (string-drop-right "file.new" 4))) (newline)
(define fluid (make-fluid 'outside))
(write (list (with-fluid* fluid 'inside (lambda () (fluid-ref fluid))) (fluid-ref fluid))) (newline)
(unsetenv "QFITZAH_TEST_LOCAL")
(write (getenv "QFITZAH_TEST_LOCAL")) (newline)
(write (list (/) (/ 7) (/ -7 2) (/ 64 2 4))) (newline)
(write (list (port-line (current-input-port)) (port-column (open-output-string)))) (newline)
(write (catch 'misc-error (lambda () (/ "bad")) (lambda args 'bad-number))) (newline)
(write (catch 'misc-error
         (lambda () (let ((p (open-input-string ""))) (unread-char (read-char p) p)))
         (lambda args 'strict-eof))) (newline)
(write (list ((negate =) 1 2) ((negate <) 1 2 3) ((negate (lambda () #f))))) (newline)
(write (list (string-index "abca" #\a) (string-index "abca" #\a 1)
             (string-index-right "abca" #\a) (string-index "abca" #\a 1 3)
             (string-index "a7z" char-numeric?)
             (string-index "a b" char-set:whitespace)
             (string-index-right "" #\x))) (newline)
(write (catch 'misc-error (lambda () (string-index "abc" #\a -1))
              (lambda args 'bad-bounds))) (newline)
(write (list (substring "abcd" 1) (substring "abcd" 1 3)
             (substring/shared "abcd" 4))) (newline)
(write (catch 'misc-error (lambda () (substring "abc" 3 1))
              (lambda args 'bad-substring))) (newline)
(write (map dirname '("" "file.c" "dir/file.c" "dir/file.c/" "/file.c" "/" "a//b"))) (newline)
(write (list (string-delete #\- "a-b-c")
             (string-filter char-numeric? "a1b2c")
             (string-delete char-set:whitespace "a b\tc")
             (string-filter #\a "baac" 1 3))) (newline)
(write (list (string-drop "abcd" 2) (string-take "abcd" 2)
             (string-take-right "abcd" 2) (string-drop-right "abcd" 2)
             (string-drop "abcd" 4) (string-take-right "abcd" 0))) (newline)
(write (list (last '(a b c)) (last '(a)) (last '(a b . tail)))) (newline)
(write (catch 'misc-error (lambda () (last '())) (lambda args 'empty-last))) (newline)
(write (list (string-fold cons '() "abc") (string-fold-right cons '() "abc")
             (string-fold-right cons '() "abcde" 1 4)
             (string-fold cons 'empty "abc" 2 2))) (newline)
(let ((seen '()))
  (write (string-fold-right (lambda (c n) (set! seen (cons c seen)) (+ n 1)) 0 "abc"))
  (write seen) (newline))
(write (catch 'misc-error (lambda () (string-fold cons '() "abc" -1))
         (lambda args 'fold-range))) (newline)
(write (catch 'misc-error (lambda () (string-fold-right #f '() "abc"))
         (lambda args 'fold-procedure))) (newline)
(define (selector-tree start width)
  (if (= width 1) start
      (let ((half (quotient width 2)))
        (cons (selector-tree start half) (selector-tree (+ start half) half)))))
(let ((tree (selector-tree 0 16)))
  (write (map (lambda (selector) (selector tree))
           (list caaaar caaadr caadar caaddr cadaar cadadr caddar cadddr
                 cdaaar cdaadr cdadar cdaddr cddaar cddadr cdddar cddddr))) (newline))
(write (catch 'misc-error (lambda () (cdadar '()))
         (lambda args 'selector-pair))) (newline)
