; Native unit tests for the generated-core analyzer, without external sources.
(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  (list (cons '+ +) (cons '- -) (cons '= =) (cons 'list list)
        (cons 'cons cons) (cons 'car car) (cons 'cdr cdr)
        (cons 'null? null?) (cons 'pair? pair?) (cons 'vector vector)))
(define (same expression arguments)
  (let ((fast (%analyze-generated-transformer expression %host-environment))
        (slow (%evaluate expression %host-environment)))
    (write (equal? (apply fast arguments) (apply slow arguments))) (newline)))
(same '(lambda (x)
         (let ((y x))
           (let* ((x (+ y 1)) (x (+ x 1)))
             (cond ((= x 0) 'zero) (else (list x y)))))) '(40))
(same '(lambda (items)
         (let loop ((rest items) (count 0))
           (if (null? rest) count (loop (cdr rest) (+ count 1))))) '((a b c)))
(same '(lambda (x) (((lambda (y) (lambda (z) (+ y z))) x) 1)) '(41))
(same '(lambda (x) (and x (or #f 42))) '(#t))
(same '(lambda (x) (cond (x) (else 99))) '(42))
; Unsupported set! and rest parameters use the reference evaluator, not stubs.
(same '(lambda (x) (set! x (+ x 1)) x) '(41))
(same '(lambda values (car values)) '(42 99))
(define effects '())
(%host-primitive! 'mark (lambda (x) (set! effects (cons x effects)) x))
(define expression '(lambda () (list (mark 1) (mark 2) (mark 3))))
(define analyzed (%analyze-generated-transformer expression %host-environment))
(define interpreted (%evaluate expression %host-environment))
(define first (analyzed))
(define first-effects effects)
(set! effects '())
(write (and (equal? first (interpreted)) (equal? first-effects effects))) (newline)
; A new owned binding can shadow an imported cell after analysis.
(define module (%environment %host-environment))
(%environment-alias! module '+ (%environment-find %host-environment '+))
(define global-reader (%analyze-generated-transformer '(lambda (x) (+ x 1)) module))
(%environment-define! module '+ (lambda (a b) 42))
(gc)
(write (= (global-reader 99) 42)) (newline)
; Native continuations work through the analyzed lexical frames.
(define escape (%analyze-generated-transformer '(lambda (k) (let ((x 42)) (k x)))
                                               %host-environment))
(write (= (call/cc escape) 42)) (newline)
(write (and (> %a-count 0) (>= %a-fallback-count 2))) (newline)
