(trans-unit
  (@ (comment "attribute comment"))
  (comment "plain comment")
  ((comment "head comment") (type-qual "const") (type-qual "volatile"))
  (kept . (comment "tail comment"))
  (unknown . dotted)
  #f 17 "unchanged" #(1 2)
  (decl-spec-list (@ (attributes "unused")) (type-spec (fixed-type "int")))
  (decl-spec-list (fctn-spec "inline") (type-spec (fixed-type "int")))
  (decl-spec-list (stor-spec (static)) (fctn-spec "inline") (type-spec (fixed-type "int")))
  (decl-spec-list (fctn-spec "other") (type-spec (fixed-type "int")))
  (type-qual "const") (type-qual (const)) (type-qual "volatile")
  (pointer (type-qual-list (type-qual "const")) (pointer (type-qual-list (type-qual "const"))))
  (pointer (type-qual-list (type-qual "volatile")) (type-qual "const"))
  (decl-spec-list (type-qual "const"))
  (decl-spec-list (type-qual "volatile"))
  (decl-spec-list (type-qual "const") (type-qual "const") (type-spec (fixed-type "int")))
  (decl-spec-list (type-qual "volatile") (type-qual "const") (type-spec (fixed-type "int")))
  (decl-spec-list (type-qual-list (type-qual (const))) (type-spec (fixed-type "int")))
  (decl-spec-list (type-qual-list (type-qual "volatile")) (type-qual "const"))
  (outer (decl-spec-list (fctn-spec "inline") (type-qual "const")))
  (decl-spec-list (@ (attributes "outer")) (decl-spec-list (@ (attributes "inner")) x)))
