; Run on a 64 KiB heap, far smaller than the allocation volume below.
(define keep (cons (make-string 37 #\k) (make-vector 3 #f)))
(vector-set! (cdr keep) 0 keep) ; cycle crossing cells and vector storage
(vector-set! (cdr keep) 1 (lambda (x) (cons (car keep) x)))
(vector-set! (cdr keep) 2 (list 7 8 9))
(define (churn n)
  (if (= n 0) #t
      (let ((s (make-string 2048 #\x))
            (v (make-vector 64 (list n))))
        (string-set! s 1024 #\y)
        (vector-set! v 1 v) ; unreachable cyclic garbage each iteration
        (churn (- n 1)))))
(churn 500)
(write (> (gc-count) 5)) (newline)
(gc)
(write (eq? (vector-ref (cdr keep) 0) keep)) (newline)
(write ((vector-ref (cdr keep) 1) 'end)) (newline)
(write (vector-ref (cdr keep) 2)) (newline)
; Raw vector buffer pointers remain roots while Cons allocates list cells.
(define big (make-vector 500 42))
(gc)
(define values (vector->list big))
(write (length values)) (newline)
(write (list (car values) (list-ref values 499))) (newline)
; Static quoted mutable structures must be scanned as roots too.
(define literal '(original))
(set-car! literal (make-string 3 #\z))
(gc)
(write literal) (newline)
; Nested lexical environments must survive while allocations trigger GC.
(define (capture x)
  (lambda (n) (churn n) (gc) x))
(define saved (capture (list 123 (make-string 4 #\s))))
(write (saved 500)) (newline)
; Interning remains stable after collections (oblist is an explicit root).
(define name (string->symbol (make-string 3 #\a)))
(gc)
(write (eq? name (string->symbol "aaa"))) (newline)
(write (list (make-string 0) (make-vector 0))) (newline)
; Identity indexes rely only on stability, never uniqueness or object contents.
(define hash-keys (list keep (car keep) (cdr keep) name (make-symbol "unique") -1 #f))
(define hashes (map %identity-hash hash-keys))
(string-set! (car keep) 0 #\j)
(churn 100)
(gc)
(write (equal? hashes (map %identity-hash hash-keys))) (newline)
(write (map (lambda (hash) (and (number? hash) (>= hash 0))) hashes)) (newline)
(define key-a (make-symbol "same"))
(define key-b (make-symbol "same"))
(define keys (list key-a key-b #f))
(define entries (list (cons key-a 'first) (cons key-b 'second)))
(gc)
(write (list (eq? (memq key-b keys) (cdr keys))
             (eq? (assq key-b entries) (cadr entries))
             (memq 'absent keys) (assq 'absent entries)
             (memq key-a '()) (assq key-a '()))) (newline)
(set-cdr! (assq key-b entries) 'changed)
(write (cdr (assq key-b entries))) (newline)
