; Private host-frame lookup: compare native search to the original definition.
(define (frame parent fallback) (vector '() '() parent fallback #f))
(define (bind! env name value slot)
  (let ((cell (cons value env)))
    (vector-set! env slot (cons (cons name cell) (vector-ref env slot)))
    cell))
(define (reference env name slot)
  (and env
    (let ((entry (assq name (vector-ref env slot))))
      (or (and entry (cdr entry))
          (reference (vector-ref env 2) name slot)
          (reference (vector-ref env 3) name slot)))))
(define parent (frame #f #f))
(define fallback (frame #f #f))
(define local (frame parent fallback))
(bind! parent 'shared 1 0)
(bind! fallback 'shared 2 0)
(bind! fallback 'private 3 0)
(bind! parent 'macro 4 1)
(bind! local 'shared 5 1)
(define (compare env)
  (for-each (lambda (name)
    (for-each (lambda (slot)
      (if (eq? (%env-find env name slot) (reference env name slot)) #t
          (error 'env-find "different cell" name slot))) '(0 1)))
    '(shared private macro absent)))
(compare local)
(define cell (%env-find local 'shared 0))
(set-car! cell 42)
(write (= (car (%env-find local 'shared 0)) 42)) (newline)
(define unique (make-symbol "shared"))
(bind! local unique 99 0)
(write (not (%env-find local (make-symbol "shared") 0))) (newline)
(write (= (car (%env-find local unique 0)) 99)) (newline)
(define (deepen n env)
  (if (= n 0) env (deepen (- n 1) (frame env #f))))
(define deep (deepen 200 local))
(gc)
(compare deep)
(write (eq? (%env-find deep 'shared 0) cell)) (newline)
(write (not (%env-find #f 'absent 1))) (newline)
