(define a (string->number "18446744073709551615"))
(define b (string->number "4294967296"))
(for-each (lambda (n) (display n) (newline))
          (list (+ 536870911 1) (- -536870912 1) (- -536870912)
                (* 536870911 536870911) (quotient -536870912 -1)
                (remainder -536870912 -1) a (+ a 1) (- a b)
                (* b b) (quotient a b) (remainder a b)
                (quotient (- a) b) (remainder (- a) b)))
(write (list (= a (+ (* (quotient a b) b) (remainder a b)))
             (= 1 1 2) (< 1 2 0) (< (- a) -536870912 0 536870911 a)
             (eqv? a (string->number "18446744073709551615")))) (newline)
(display (number->string a 16)) (newline)
(display (number->string (- a) 16)) (newline)
(write (map string->number '("#xff" "#b101" "#o77" "+42" "-0" "no" "12x" "+"))) (newline)
(display (logand a 4294967)) (newline)
(display (logior b 1)) (newline)
(display (logxor a b)) (newline)
(display (lognot b)) (newline)
(display (ash 1 100)) (newline)
(display (ash (ash 1 100) -99)) (newline)
(display (ash -5 -1)) (newline)
; Exercise identities with many signs and magnitudes, crossing the fixnum edge.
(define numbers (list 0 1 -1 16383 16384 536870911 -536870912 a (- a) b (- b)))
(define (assert x) (if x #t (error 'integers "identity failed")))
(for-each
  (lambda (x)
    (for-each
      (lambda (y)
        (assert (= (- (+ x y) y) x))
        (assert (= (* x y) (* y x)))
        (if (= y 0) #f
            (begin (assert (= (+ (* (quotient x y) y) (remainder x y)) x))
                   (assert (< (abs (remainder x y)) (abs y))))))
      numbers))
  numbers)
(display "integer identities ok") (newline)
(write (catch 'misc-error (lambda () (quotient a 0)) (lambda args 'caught))) (newline)
(gc)
(display a) (newline)
; Numeric equality must not become pointer equality for distinct bignums.
(define a-copy (string->number "18446744073709551615"))
(define values-list (list 1 a 2))
(define values-alist (list (cons 1 'small) (cons a 'large)))
(write (list (eq? (memv a-copy values-list) (cdr values-list))
             (eq? (assv a-copy values-alist) (cadr values-alist))
             (eq? (memv 1 values-list) values-list)
             (eq? (assv 1 values-alist) (car values-alist))
             (memv 3 values-list) (assv b values-alist))) (newline)
(write (catch 'misc-error (lambda () (memv a '(1 . bad)))
              (lambda args 'bad-list))) (newline)
(write (catch 'misc-error (lambda () (assv a '(bad)))
              (lambda args 'bad-alist))) (newline)
