; Full 30-bit fixnum range, in expression and quoted/static field positions.
(for-each (lambda (x) (display x) (newline))
          (list 134217728 536870911 -536870912 -134217729
                '134217728 '536870911 '-536870912 '-134217729))
(write '(134217728 536870911 -536870912 -134217729)) (newline)
(define outer 1)
(display ((lambda () (define outer 2) outer))) (newline)
(display outer) (newline)
(display ((lambda (x)
            (begin (define (even n) (if (= n 0) x (odd (- n 1))))
                   (define (odd n) (if (= n 0) #f (even (- n 1)))))
            (even 8)) 42)) (newline)
; Each activation must have independent local mutable state.
(define (counter n)
  (define value n)
  (lambda () (set! value (+ value 1)) value))
(define a (counter 10))
(define b (counter 20))
(write (list (a) (b) (a))) (newline)
(define calls 0)
(write (cond ((begin (set! calls (+ calls 1)) 7)) (else 9))) (newline)
(write calls) (newline)
(write (cond (#f) (else 9))) (newline)
; apply must not expose list pairs as parameter binding cells.
(define args (list 1 2 3))
(write (apply (lambda (x y z) (set! x 99) x) args)) (newline)
(write args) (newline)
(write (apply (lambda (x . rest) rest) args)) (newline)
(write args) (newline)
(write (apply (lambda (x y . rest) (list x y rest)) 0 args)) (newline)
(write args) (newline)
; Tail position through both short-circuit forms; depth exceeds normal stack.
(define (tail-and n) (and (> n 0) (tail-or (- n 1))))
(define (tail-or n) (or (= n 0) (tail-and (- n 1))))
(write (tail-or 100000)) (newline)
(write (list (and) (or) (and 1 2) (or #f 3))) (newline)
; Direct let frames preserve initializer scope, mutable captures, and restores.
(define outside 99)
(write (let ((outside 1) (copy outside)) (+ outside copy))) (newline)
(define shared-let
  (let ((value 1))
    (cons (lambda () value) (lambda (new) (set! value new)))))
((cdr shared-let) 42)
(write ((car shared-let))) (newline)
(write (let ((value 5))
         (+ (let ((value 7)) value) value))) (newline)
(write (let ((value 42))
         (define (local n) (if (= n 0) value (local (- n 1))))
         (local 100000))) (newline)
; Fast primitive entry must use the captured operator, not reload its binding.
(define original-car car)
(define captured-car
  (car (begin (set! car (lambda (ignored) 99)) (cons 42 '()))))
(define rebound-car (car '(1)))
(set! car original-car)
(write (list captured-car rebound-car)) (newline)
(write (let ((car (lambda (x) (+ x 1)))) (car 41))) (newline)
(define order '())
(write (cons (begin (set! order (cons 1 order)) 10)
             (begin (set! order (cons 2 order)) 20))) (newline)
(write order) (newline)
(write (list (car '(42) 'ignored) ; wrong arity keeps legacy slow-path behavior
             (vector-ref (vector 10 42) 1)
             (char->integer (integer->char 65)))) (newline)
