; Stage 4 corpus: vectors (object subtype 4) and mutable strings.
(define v (make-vector 3 0))
(vector-set! v 0 'a) (vector-set! v 1 'b) (vector-set! v 2 'c)
(display "vec: ") (write v) (newline)
(display "ref: ") (display (vector-ref v 1)) (newline)
(display "len: ") (display (vector-length v)) (newline)
(display "vector: ") (write (vector 1 2 3 4)) (newline)
(display "v->l: ") (write (vector->list (vector 'x 'y 'z))) (newline)
(display "l->v: ") (write (list->vector '(10 20 30))) (newline)
(display "vec?: ") (write (list (vector? v) (vector? '(1 2)) (vector? 5))) (newline)
(display "nested: ") (write (vector 1 (vector 2 3) '(4 5))) (newline)
(display "make0: ") (write (make-vector 0)) (newline)
(define w (make-vector 3 7))
(vector-fill! w 9)
(display "fill: ") (write w) (newline)
(display "equal?: ") (write (equal? (vector 1 2 3) (list->vector '(1 2 3)))) (newline)
; mutable strings
(define s (make-string 4 #\x))
(string-set! s 1 #\Y)
(string-set! s 3 #\Z)
(display "mstr: ") (write s) (newline)
