(write (cdr (command-line))) (newline)
(write (getenv "QFITZAH_IO_TEST")) (newline)
(write (getenv "QFITZAH_MISSING_ENV_4C568E")) (newline)
(define (assert x) (if x #t (error 'ports "assertion failed")))
(define (bytes n)
  (let ((s (make-string n)))
    (let loop ((i 0))
      (if (= i n) s
          (begin (string-set! s i (integer->char (remainder i 256)))
                 (loop (+ i 1)))))))
(define content (bytes 12345))
(call-with-output-file "roundtrip.bin" (lambda (p) (display content p)))
(define input (open-input-file "roundtrip.bin"))
(assert (eq? (peek-char input) (integer->char 0)))
(assert (eq? (peek-char input) (integer->char 0)))
(let loop ((i 0))
  (if (= i (string-length content)) #t
      (begin (assert (eq? (read-char input) (string-ref content i)))
             (if (= (remainder i 997) 0) (gc) #f)
             (loop (+ i 1)))))
(assert (eof-object? (read-char input)))
(assert (eof-object? (peek-char input)))
(close-port input)
(assert (port-closed? input))
(display "binary roundtrip ok") (newline)
(define s (open-input-string "ab"))
(assert (eq? (read-char s) #\a))
(unread-char #\a s)
(assert (eq? (peek-char s) #\a))
(assert (eq? (read-char s) #\a))
(assert (eq? (read-char s) #\b))
(assert (eof-object? (read-char s)))
(define out (open-output-string))
(display content out)
(gc)
(assert (string=? content (get-output-string out)))
(write (call-with-output-string
         (lambda (p) (write '("a\"b\\c" #\newline #t) p))))
(newline)
(display (with-output-to-string
           (lambda () (display "current-port restored"))))
(newline)
(display -536870912) (newline)
(display (number->string -536870912 16)) (newline)
; Test offset/count handling and lseek directly, without buffered input.
(define fd (%file-open "roundtrip.bin" 0 0))
(assert (>= fd 0))
(assert (= (%file-seek fd 255 0) 255))
(define buf (make-string 5 #\x))
(assert (= (%file-read fd buf 1 2) 2))
(assert (eq? (string-ref buf 0) #\x))
(assert (= (char->integer (string-ref buf 1)) 255))
(assert (= (char->integer (string-ref buf 2)) 0))
(assert (eq? (string-ref buf 3) #\x))
(assert (= (%file-close fd) 0))
(assert (< (%file-open "missing/absent" 0 0) 0))
(display "file syscall checks ok") (newline)
(display "stderr works\n" (current-error-port))
