(* 2 3)
(cons 1 2)
((lambda (a b) (+ a b)) 3 4)
(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))
(fact 10)
(quotient 17 5)
(remainder -17 5)
(< 1 2)
(define (loop i acc) (if (= i 0) acc (loop (- i 1) (+ acc 1))))
(loop 100000 0)
(let ((x 3) (y 4)) (* x y))
(cond ((= 1 2) 'a) ((= 3 3) 'b) (else 'c))
(and 1 2 3)
(or #f #f 7)
(begin 1 2 3)
(define s "hi")
(string-length s)
(string-ref s 1)
(string->symbol s)
(symbol->string 'abc)
(list->string (cons #\a (cons #\b '())))
(define p (cons 1 2))
(set-car! p 99)
p
(define v 5)
(set! v (+ v 1))
v
((lambda args args) 1 2 3)
(eq? 'x 'x)
(eqv? 1 1)
(not #f)
(define (map1 f l) (if (null? l) '() (cons (f (car l)) (map1 f (cdr l)))))
(map1 (lambda (x) (* x x)) '(1 2 3 4))
(define (append2 a b) (if (null? a) b (cons (car a) (append2 (cdr a) b))))
(append2 '(1 2) '(3 4))
(char->integer #\a)
(integer->char 98)
(pair? '(1))
(pair? 1)
(null? '())
(symbol? 'x)
(number? 3)
(string? "x")
(char? #\x)
(boolean? #f)
(procedure? car)
(procedure? (lambda (x) x))
(display "display works")
(newline)
(display 42)
(newline)
(write "quoted")
(newline)
'(dotted . pair)
(quote (a b (c d)))
(if #f #f)
(exit 0)
