(define-module (example counter) #:export (count increment! twice access-private define-created))
(define count 0)
(define private 'hidden)
(define (increment!) (set! count (+ count 1)) count)
(define-macro (twice expression) `(begin ,expression ,expression))
; Mes keeps the macro even if its value namespace is rebound.
(define twice #f)
(define (counter-private x) (+ 100 x))
(define-macro (access-private x) `(counter-private ,x))
(define-macro (define-created name) `(define ,name (counter-private 2)))
