; Assemble annotated hexadecimal source, using only the source-built runtime.
; This is a strict subset of hex0: hex digits, ASCII whitespace, #/; comments.
; Validate the entire input before opening output. No executable seed is read.
(define (hex0-digit c)
  (let ((n (char->integer c)))
    (cond ((and (>= n 48) (<= n 57)) (- n 48))
          ((and (>= n 65) (<= n 70)) (+ 10 (- n 65)))
          ((and (>= n 97) (<= n 102)) (+ 10 (- n 97)))
          (else #f))))
(define (hex0-space? c)
  (let ((n (char->integer c)))
    (or (= n 32) (and (>= n 9) (<= n 13)))))
(define (hex0-comment port)
  (let ((c (read-char port)))
    (if (or (eof-object? c) (char=? c #\newline)) #f
        (hex0-comment port))))
(define (hex0-read port)
  (let loop ((high #f) (bytes '()))
    (let ((c (read-char port)))
      (cond ((eof-object? c)
             (if high (error 'hex0 "unpaired hexadecimal digit") (reverse bytes)))
            ((or (char=? c #\#) (char=? c #\;))
             (hex0-comment port) (loop high bytes))
            ((hex0-space? c) (loop high bytes))
            (else
             (let ((digit (hex0-digit c)))
               (if (not digit) (error 'hex0 "invalid source character" c)
                   (if high (loop #f (cons (+ (* high 16) digit) bytes))
                       (loop digit bytes)))))))))
(define (hex0-write bytes port)
  (if (null? bytes) #f
      (begin (write-char (integer->char (car bytes)) port)
             (hex0-write (cdr bytes) port))))
(let ((args (cdr (command-line))))
  (if (not (= (length args) 2)) (error 'hex0 "usage: hex0 INPUT OUTPUT") #f)
  (let* ((input (open-input-file (car args)))
         (bytes (hex0-read input)))
    (close-input-port input)
    (let ((output (open-output-file (cadr args))))
      (hex0-write bytes output)
      (close-output-port output))))
