; Reader for the pinned singularity language: lowercase names, application,
; multi-argument lambdas/definitions, parentheses, @primitive, #byte, --comments.
(define sg-port #f)
(define sg-line 1)
(define sg-token #f)
(define (sg-error message) (error 'singularity message sg-line sg-token))
(define (sg-read-char)
  (let ((c (read-char sg-port)))
    (if (and (char? c) (char=? c #\newline)) (set! sg-line (+ sg-line 1)) #f)
    c))
(define (sg-letter? c)
  (and (char? c) (>= (char->integer c) 97) (<= (char->integer c) 122)))
(define (sg-space? c)
  (and (char? c) (or (char=? c #\space)
                    (and (>= (char->integer c) 9) (<= (char->integer c) 13)))))
(define (sg-comment)
  (let ((c (sg-read-char)))
    (if (or (eof-object? c) (char=? c #\newline)) #f (sg-comment))))
(define (sg-name first)
  (let loop ((chars (list first)))
    (if (sg-letter? (peek-char sg-port))
        (loop (cons (sg-read-char) chars))
        (cons 'name (string->symbol (list->string (reverse chars)))))))
(define (sg-prefixed prefix)
  (let ((c (sg-read-char)))
    (if (eof-object? c) (sg-error "missing primitive/character byte") #f)
    (cons 'raw (if (char=? prefix #\@) (string c) (string #\# c)))))
(define (sg-next-token)
  (let ((c (sg-read-char)))
    (cond ((eof-object? c) (cons 'end #f))
          ((sg-space? c) (sg-next-token))
          ((sg-letter? c) (sg-name c))
          ((or (char=? c #\@) (char=? c #\#)) (sg-prefixed c))
          ((char=? c #\-)
           (let ((next (sg-read-char)))
             (cond ((eqv? next #\-) (sg-comment) (sg-next-token))
                   ((eqv? next #\>) (cons 'arrow #f))
                   (else (sg-error "expected comment or lambda arrow")))))
          ((char=? c #\() (cons 'left #f))
          ((char=? c #\)) (cons 'right #f))
          ((char=? c #\\) (cons 'lambda #f))
          ((char=? c #\=) (cons 'equals #f))
          ((char=? c #\;) (cons 'semi #f))
          (else (sg-error "unexpected input character")))))
(define (sg-advance) (set! sg-token (sg-next-token)))
(define (sg-kind? kind) (eq? (car sg-token) kind))
(define (sg-expect kind)
  (if (not (sg-kind? kind)) (sg-error (list 'expected kind)) #f)
  (let ((value (cdr sg-token))) (sg-advance) value))
(define (sg-parameters)
  (if (sg-kind? 'name)
      (let ((name (sg-expect 'name))) (cons name (sg-parameters))) '()))
(define (sg-lambdas names body)
  (if (null? names) body (vector 'lam (car names) (sg-lambdas (cdr names) body))))
(define (sg-parse-lambda)
  (sg-expect 'lambda)
  (let ((names (sg-parameters)))
    (if (null? names) (sg-error "lambda needs a parameter") #f)
    (sg-expect 'arrow)
    (sg-lambdas names (sg-expression))))
(define (sg-atom)
  (cond ((sg-kind? 'name) (vector 'var (sg-expect 'name)))
        ((sg-kind? 'raw) (vector 'raw (sg-expect 'raw)))
        ((sg-kind? 'lambda) (sg-parse-lambda))
        ((sg-kind? 'left)
         (sg-advance)
         (let ((expr (sg-expression))) (sg-expect 'right) expr))
        (else (sg-error "expected expression"))))
(define (sg-expression)
  (let loop ((expr (sg-atom)))
    (if (memq (car sg-token) '(name raw lambda left))
        (loop (vector 'app expr (sg-atom))) expr)))
(define (sg-definition)
  (let* ((name (sg-expect 'name)) (params (sg-parameters)))
    (sg-expect 'equals)
    (let ((expr (sg-expression)))
      (sg-expect 'semi)
      (cons name (sg-lambdas params expr)))))
(define (sg-program)
  (sg-advance)
  (let loop ((defs '()))
    (if (sg-kind? 'end)
        (if (null? defs) (sg-error "empty program") (reverse defs))
        (let ((def (sg-definition)))
          (if (assq (car def) defs) (sg-error "duplicate definition") #f)
          (loop (cons def defs))))))
