; Direct SKI bracket abstraction, matching singularity's unlam/babs algorithm.
; K t when x is not free; I for x; S ([x]a) ([x]b) for an application.
(define (sg-free? name expr)
  (case (vector-ref expr 0)
    ((raw) #f)
    ((var) (eq? name (vector-ref expr 1)))
    ((app) (or (sg-free? name (vector-ref expr 1))
               (sg-free? name (vector-ref expr 2))))
    (else (sg-error "unexpected lambda during abstraction"))))
(define (sg-abstract name expr)
  (cond ((not (sg-free? name expr)) (vector 'app (vector 'raw "K") expr))
        ((eq? (vector-ref expr 0) 'var) (vector 'raw "I"))
        (else (vector 'app
                (vector 'app (vector 'raw "S") (sg-abstract name (vector-ref expr 1)))
                (sg-abstract name (vector-ref expr 2))))))
(define (sg-lower expr)
  (case (vector-ref expr 0)
    ((raw var) expr)
    ((app) (vector 'app (sg-lower (vector-ref expr 1)) (sg-lower (vector-ref expr 2))))
    ((lam) (sg-abstract (vector-ref expr 1) (sg-lower (vector-ref expr 2))))
    (else (sg-error "invalid expression node"))))
(define (sg-symbols defs)
  (let loop ((defs defs) (index 0) (out '()))
    (if (null? defs) out
        (if (>= index 224) (sg-error "ION byte-index table exhausted")
            (loop (cdr defs) (+ index 1) (cons (cons (caar defs) index) out))))))
(define (sg-index name symbols)
  (let ((entry (assq name symbols)))
    (if entry (cdr entry) (sg-error (list 'unbound-variable name)))))
(define (sg-validate expr symbols limit)
  (case (vector-ref expr 0)
    ((var) (let ((name (vector-ref expr 1)))
             (if (>= (sg-index name symbols) limit)
                 (sg-error (list 'unsupported-forward-reference name)) #t)))
    ((app) (sg-validate (vector-ref expr 1) symbols limit)
           (sg-validate (vector-ref expr 2) symbols limit))
    ((raw) #t)
    (else (sg-error "unlowered node"))))
(define (sg-emit expr symbols)
  (case (vector-ref expr 0)
    ((raw) (display (vector-ref expr 1)))
    ((var) (display "@")
           (write-char (integer->char (+ 32 (sg-index (vector-ref expr 1) symbols)))))
    ((app) (display "`") (sg-emit (vector-ref expr 1) symbols)
           (sg-emit (vector-ref expr 2) symbols))
    (else (sg-error "unlowered output node"))))
