; One raw C AST on stdin -> the original four Mes normalization passes -> stdout.
(define (native-normalize-event event)
  (if (getenv "QFITZAH_MESCC_TRACE")
      (let ((port (current-error-port)))
        (display "mescc: native-normalize " port) (display event port)
        (if (getenv "QFITZAH_MESCC_HEAP_TRACE")
            (begin (display "; retained-8-byte-units=" port)
                   (write (%gc-live-units) port)) #f)
        (display "; gc=" port) (write (gc-count) port) (newline port)) #f))
(let ((ast (read)))
  (if (eof-object? ast) (error 'native-normalizer "missing AST") #f)
  (if (not (eof-object? (read))) (error 'native-normalizer "trailing input") #f)
  (native-normalize-event "begin")
  (let ((result (ast-strip-inline (ast-strip-attributes
                  (ast-strip-const (ast-strip-comment ast))))))
    (native-normalize-event "done")
    (write result) (newline)))
