; Analyze the core expressions emitted by Mes's source syntax-rules compiler.
; This does NOT cache expansions: transformers still run on every invocation,
; with fresh rename/compare callbacks and current definition-module values.
; Unsupported syntax falls back to the ordinary evaluator for the whole
; transformer. Native closures execute the supported code without repeatedly
; classifying source forms, searching lexical names or checking syntax arity.
;
; Analysis-time scopes are lists of identifier lists. Execution frames are
; (value-vector . parent-frame); these private frames never escape to eval.
(define (%a-location name scopes depth)
  (if (null? scopes) #f
      (let find ((names (car scopes)) (index 0))
        (cond ((null? names) (%a-location name (cdr scopes) (+ depth 1)))
              ((eq? name (car names)) (cons depth index))
              (else (find (cdr names) (+ index 1)))))))
(define (%a-frame frame depth)
  (if (= depth 0) (car frame) (%a-frame (cdr frame) (- depth 1))))
(define (%a-reference name scopes globals)
  (let ((location (%a-location name scopes 0)))
    (if location
        (lambda (frame)
          (let ((value (vector-ref (%a-frame frame (car location)) (cdr location))))
            (if (eq? value %undefined) (error 'eval "uninitialized variable" name) value)))
        (lambda (frame) (%environment-ref globals name)))))
(define (%a-constant value) (lambda (frame) value))
(define (%a-codes expressions scopes globals)
  (if (null? expressions) '()
      (and (pair? expressions)
           (let ((head (%a-expression (car expressions) scopes globals)))
             (and head
                  (let ((tail (%a-codes (cdr expressions) scopes globals)))
                    (and tail (cons head tail))))))))
(define (%a-values codes frame)
  (if (null? codes) '()
      (let ((head ((car codes) frame)))
        (cons head (%a-values (cdr codes) frame)))))
(define (%a-run-sequence codes frame)
  (cond ((null? codes) #f)
        ((null? (cdr codes)) ((car codes) frame))
        (else ((car codes) frame) (%a-run-sequence (cdr codes) frame))))
(define (%a-sequence expressions scopes globals)
  (let ((codes (%a-codes expressions scopes globals)))
    (and codes (lambda (frame) (%a-run-sequence codes frame)))))
(define (%a-procedure value)
  (if (procedure? value) value (error 'eval "not a procedure or syntax" value)))
; Fixed small arities avoid building/reversing an interpreted argument list
; and then copying it again in apply. Evaluation remains operator-first, LTR.
(define (%a-application operator operands scopes globals)
  (let ((op (%a-expression operator scopes globals))
        (args (%a-codes operands scopes globals)))
    (and op args
      (cond ((null? args) (lambda (frame) ((%a-procedure (op frame)))))
            ((null? (cdr args))
             (let ((a (car args)))
               (lambda (frame) ((%a-procedure (op frame)) (a frame)))))
            ((null? (cddr args))
             (let ((a (car args)) (b (cadr args)))
               (lambda (frame) ((%a-procedure (op frame)) (a frame) (b frame)))))
            ((null? (cdddr args))
             (let ((a (car args)) (b (cadr args)) (c (caddr args)))
               (lambda (frame) ((%a-procedure (op frame)) (a frame) (b frame) (c frame)))))
            (else
             (lambda (frame)
               (let ((proc (%a-procedure (op frame))))
                 (apply proc (%a-values args frame)))))))))
(define (%a-quote args scopes globals)
  (and (= (length args) 1)
       (let ((datum (car args)))
         (if (or (pair? datum) (vector? datum))
             (lambda (frame) (%strip-identifiers datum))
             (%a-constant datum)))))
(define (%a-if args scopes globals)
  (and (or (= (length args) 2) (= (length args) 3))
       (let ((test (%a-expression (car args) scopes globals))
             (yes (%a-expression (cadr args) scopes globals))
             (no (if (null? (cddr args)) (%a-constant #f)
                     (%a-expression (caddr args) scopes globals))))
         (and test yes no (lambda (frame) (if (test frame) (yes frame) (no frame)))))))
(define (%a-lambda args scopes globals)
  (and (pair? args) (pair? (cdr args)) (%reader-proper? (car args))
       (let* ((params (car args)) (arity (length params))
              (body (%a-sequence (cdr args) (cons params scopes) globals)))
         (and body
           (lambda (frame)
             (lambda values
               (let ((count (length values)))
                 (cond ((< count arity) (error 'apply "too few arguments"))
                       ((> count arity) (error 'apply "too many arguments"))
                       (else (body (cons (list->vector values) frame)))))))))))
(define (%a-let args scopes globals)
  (if (%identifier? (car args)) (%a-named-let args scopes globals)
      (let* ((bindings (car args)) (names (map car bindings))
             (values (%a-codes (map cadr bindings) scopes globals))
             (body (%a-sequence (cdr args) (cons names scopes) globals)))
        (and values body
          (lambda (frame)
            (body (cons (list->vector (%a-values values frame)) frame)))))))
(define (%a-named-let args scopes globals)
  (let* ((name (car args)) (bindings (cadr args))
         (values (%a-codes (map cadr bindings) scopes globals))
         (proc (%a-lambda (cons (map car bindings) (cddr args))
                         (cons (list name) scopes) globals)))
    (and values proc
      (lambda (frame)
        (let* ((local (cons (vector %undefined) frame)) (function (proc local)))
          (vector-set! (car local) 0 function)
          (apply function (%a-values values frame)))))))
(define (%a-let-star-bindings bindings body scopes globals)
  (if (null? bindings) (%a-sequence body scopes globals)
      (let* ((binding (car bindings))
             (value (%a-expression (cadr binding) scopes globals))
             (next (%a-let-star-bindings (cdr bindings) body
                     (cons (list (car binding)) scopes) globals)))
        (and value next
          (lambda (frame) (next (cons (vector (value frame)) frame)))))))
(define (%a-let-star args scopes globals)
  (%a-let-star-bindings (car args) (cdr args) scopes globals))
(define (%a-run-and codes frame)
  (cond ((null? codes) #t) ((null? (cdr codes)) ((car codes) frame))
        (else (and ((car codes) frame) (%a-run-and (cdr codes) frame)))))
(define (%a-run-or codes frame)
  (cond ((null? codes) #f) ((null? (cdr codes)) ((car codes) frame))
        (else (or ((car codes) frame) (%a-run-or (cdr codes) frame)))))
(define (%a-and args scopes globals)
  (let ((codes (%a-codes args scopes globals)))
    (and codes (lambda (frame) (%a-run-and codes frame)))))
(define (%a-or args scopes globals)
  (let ((codes (%a-codes args scopes globals)))
    (and codes (lambda (frame) (%a-run-or codes frame)))))
(define (%a-cond clauses scopes globals)
  (if (null? clauses) (%a-constant #f)
      (let ((clause (car clauses)))
        (cond ((eq? (%identifier-name (car clause)) 'else)
               (%a-sequence (cdr clause) scopes globals))
              ; The source compiler never emits =>. Keep unsupported code on
              ; the reference evaluator rather than broadening this compiler.
              ((and (pair? (cdr clause)) (eq? (%identifier-name (cadr clause)) '=>)) #f)
              (else
               (let ((test (%a-expression (car clause) scopes globals))
                     (yes (%a-sequence (cdr clause) scopes globals))
                     (no (%a-cond (cdr clauses) scopes globals)))
                 (and test yes no
                   (lambda (frame)
                     (let ((value (test frame)))
                       (if value (if (null? (cdr clause)) value (yes frame)) (no frame)))))))))))
(define %a-syntax
  (list (cons %syntax-quote %a-quote) (cons %syntax-if %a-if)
        (cons %syntax-lambda %a-lambda) (cons %evaluate-sequence %a-sequence)
        (cons %syntax-let %a-let) (cons %syntax-let* %a-let-star)
        (cons %syntax-and %a-and) (cons %syntax-or %a-or)
        (cons %syntax-cond %a-cond)))
(define (%a-expression expression scopes globals)
  (cond ((keyword? expression) (%a-constant expression))
        ((%identifier? expression) (%a-reference expression scopes globals))
        ((not (pair? expression)) (%a-constant expression))
        (else
         (let* ((operator (car expression))
                (cell (and (%identifier? operator)
                           (%environment-find-slot globals operator 1)))
                (syntax (and cell (not (eq? (car cell) %undefined)) (car cell))))
           (if syntax
               (and (%tagged-procedure? syntax %syntax-tag)
                    (let ((entry (assq (vector-ref syntax 1) %a-syntax)))
                      (and entry ((cdr entry) (cdr expression) scopes globals))))
               (%a-application operator (cdr expression) scopes globals))))))
(define %a-count 0)
(define %a-fallback-count 0)
(define (%analyze-generated-transformer expression globals)
  (let ((code (and (not (getenv "QFITZAH_DISABLE_ANALYSIS"))
                   (%a-expression expression '() globals))))
    (if code
        (begin (set! %a-count (+ %a-count 1)) (code #f))
        (begin (set! %a-fallback-count (+ %a-fallback-count 1))
               (%evaluate expression globals)))))
; Private observability for differential/performance fixtures.
(%host-primitive! '%analyzer-counts (lambda () (list %a-count %a-fallback-count)))
