; Mes's character-set ABI is (*char-set* . characters). Preserve that shape:
; its source SRFI-14 module directly uses the tail for list-set operations.
; Native helpers avoid interpreted per-character membership scans in Nyacc.
(define (char-set? x) (and (pair? x) (eq? (car x) '*char-set*)))
(define (%char-set-members cs)
  (if (char-set? cs) (cdr cs) (error 'char-set "not a character set")))
(define (char-set-contains? cs char)
  (and (char? char) (memv char (%char-set-members cs)) #t))
(define (char-set-copy cs) (cons '*char-set* (map identity (%char-set-members cs))))
(define (char-set-adjoin! cs . chars)
  (%char-set-members cs)
  (for-each (lambda (char)
              (if (not (char? char)) (error 'char-set "not a character") #f)
              (if (char-set-contains? cs char) #f (set-cdr! cs (cons char (cdr cs))))) chars)
  cs)
(define (char-set . chars) (apply char-set-adjoin! (cons '*char-set* '()) chars))
(define (char-set-adjoin cs . chars) (apply char-set-adjoin! (char-set-copy cs) chars))
(define (list->char-set chars . base)
  (apply char-set-adjoin! (if (null? base) (char-set) (char-set-copy (car base))) chars))
(define (string->char-set text . base) (apply list->char-set (string->list text) base))
(define (string->char-set! text base) (apply char-set-adjoin! base (string->list text)))
(define (char-set-complement cs)
  (list->char-set (filter (lambda (char) (not (char-set-contains? cs char)))
                         (map integer->char (iota 128)))))
(define (char-set= . sets)
  (if (or (null? sets) (null? (cdr sets))) #t
      (let* ((left (%char-set-members (car sets))) (right (%char-set-members (cadr sets))))
        (and (= (length left) (length right))
             (let loop ((left left))
               (or (null? left) (and (memv (car left) right) (loop (cdr left)))))
             (apply char-set= (cdr sets))))))
(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  (list (cons 'char-set char-set) (cons 'char-set? char-set?) (cons 'char-set= char-set=)
        (cons 'char-set-copy char-set-copy) (cons 'char-set-adjoin char-set-adjoin)
        (cons 'char-set-adjoin! char-set-adjoin!) (cons 'list->char-set list->char-set)
        (cons 'string->char-set string->char-set) (cons 'string->char-set! string->char-set!)
        (cons 'char-set-contains? char-set-contains?) (cons 'char-set-complement char-set-complement)
        (cons 'char-set:whitespace (list->char-set (map integer->char '(9 10 11 12 13 32))))
        (cons 'char-set:digit (string->char-set "0123456789"))
        (cons 'char-set:lower-case (string->char-set "abcdefghijklmnopqrstuvwxyz"))
        (cons 'char-set:upper-case (string->char-set "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))))
