; Additional source forms required by MesCC/Nyacc, kept out of core dispatch.
(define (%do-step spec) (if (null? (cddr spec)) (car spec) (caddr spec)))
(define (%do-loop names values exit commands steps outer)
  (let ((local (%environment outer)))
    (%bind-values! local names values)
    (if (%evaluate (car exit) local) (%evaluate-sequence (cdr exit) local)
        (begin (%evaluate-sequence commands local)
               (%do-loop names (%evaluate-arguments steps local '()) exit commands steps outer)))))
(define (%syntax-do args env)
  (let ((specs (car args)))
    (%do-loop (%binding-names specs) (%binding-values specs env)
              (cadr args) (cddr args) (map %do-step specs) env)))
(define (%fluid-binding spec env)
  (if (not (and (%reader-proper? spec) (= (length spec) 2)))
      (error 'with-fluids "expected a fluid/value binding") #f)
  (let* ((fluid (%evaluate (car spec) env)) (value (%evaluate (cadr spec) env)))
    (if (not (fluid? fluid)) (error 'with-fluids "not a fluid") #f)
    (cons fluid value)))
(define (%syntax-with-fluids args env)
  (%syntax-arity 'with-fluids args 1 #f)
  (if (not (%reader-proper? (car args))) (error 'with-fluids "expected a binding list") #f)
  (let ((bindings (map (lambda (spec) (%fluid-binding spec env)) (car args))))
    (%with-fluids bindings (lambda () (%evaluate-body (cdr args) (%environment env))))))
(define %promise-tag (list 'promise))
(define (%syntax-delay args env)
  (%syntax-arity 'delay args 1 1)
  (vector %promise-tag #f (lambda () (%evaluate (car args) env)) #f))
(define (force promise)
  (if (not (and (vector? promise) (= (vector-length promise) 4)
                (eq? (vector-ref promise 0) %promise-tag)))
      (error 'force "not a promise")
      (if (vector-ref promise 1) (vector-ref promise 3)
          (let ((value ((vector-ref promise 2))))
            ; A recursive force or continuation can finish this promise first.
            (if (vector-ref promise 1) (vector-ref promise 3)
                (begin (vector-set! promise 3 value)
                       (vector-set! promise 1 #t)
                       (vector-set! promise 2 #f)
                       value))))))

; Guile/Mes lambda* parameters: required, #:optional, #:key, #:rest and
; #:allow-other-keys. Defaults are evaluated in the new lexical frame, in
; declaration order, and can reference preceding parameters.
(define (%star-name spec) (if (pair? spec) (car spec) spec))
(define (%star-default spec env)
  (if (pair? spec) (%evaluate (cadr spec) env) #f))
(define (%keyword-find args key)
  (cond ((null? args) #f)
        ((or (not (keyword? (car args))) (null? (cdr args)))
         (error 'lambda* "malformed keyword arguments" args))
        ((eq? (car args) key) (cdr args))
        (else (%keyword-find (cddr args) key))))
(define (%check-keywords args allowed allow-other?)
  (if (null? args) #t
      (if (and (keyword? (car args)) (pair? (cdr args))
               (or allow-other? (memq (car args) allowed)))
          (%check-keywords (cddr args) allowed allow-other?)
          (error 'lambda* "unknown or malformed keyword" args))))
(define (%bind-star-end args mode keys allow-other? rest?)
  (cond ((eq? mode 'key) (%check-keywords args keys allow-other?))
        ((or rest? (null? args)) #t)
        (else (error 'lambda* "too many positional arguments"))))
(define (%bind-star-marker marker params args env mode keys allow-other? rest?)
  (case (keyword->symbol marker)
    ((optional key)
     (%bind-star params args env (keyword->symbol marker) keys allow-other? rest?))
    ((allow-other-keys) (%bind-star params args env mode keys #t rest?))
    ((rest)
     (if (or (null? params) (not (%identifier? (car params))))
         (error 'lambda* "missing rest parameter")
         (begin (%environment-define! env (car params) args)
                (%bind-star (cdr params) args env mode keys allow-other? #t))))
    (else (error 'lambda* "unknown parameter marker" marker))))
(define (%bind-star-key spec params args env keys allow-other? rest?)
  (let* ((name (%star-name spec)) (key (symbol->keyword (%identifier-name name)))
         (found (%keyword-find args key)))
    (%environment-define! env name (if found (car found) (%star-default spec env)))
    (%bind-star params args env 'key (cons key keys) allow-other? rest?)))
(define (%bind-star-positional spec params args env mode keys allow-other? rest?)
  (let ((take? (and (pair? args) (or (eq? mode 'required) (not (keyword? (car args)))))))
    (if (and (eq? mode 'required) (not take?)) (error 'lambda* "missing required argument")
        (begin
          (%environment-define! env (%star-name spec)
                                (if take? (car args) (%star-default spec env)))
          (%bind-star params (if take? (cdr args) args) env mode keys allow-other? rest?)))))
(define (%bind-star params args env mode keys allow-other? rest?)
  (cond ((null? params) (%bind-star-end args mode keys allow-other? rest?))
        ((%identifier? params) (%environment-define! env params args))
        ((keyword? (car params))
         (%bind-star-marker (car params) (cdr params) args env mode keys allow-other? rest?))
        ((eq? mode 'key)
         (%bind-star-key (car params) (cdr params) args env keys allow-other? rest?))
        (else (%bind-star-positional (car params) (cdr params) args env mode keys allow-other? rest?))))
(define (%star-closure params body env)
  (lambda args
    (let ((local (%environment env)))
      (%bind-star params args local 'required '() #f #f)
      (%evaluate-body body local))))
(define (%syntax-lambda* args env) (%star-closure (car args) (cdr args) env))
(define (%syntax-define* args env)
  (%environment-define! env (caar args) (%star-closure (cdar args) (cdr args) env)))
(define (%syntax-defmacro args env)
  (%syntax-define-macro (cons (cons (car args) (cadr args)) (cddr args)) env))
(define (%syntax-define-syntax-rule args env)
  (%syntax-arity 'define-syntax-rule args 2 2)
  (%evaluate (list 'define-syntax (caar args)
                   (list 'syntax-rules '() (list (car args) (cadr args)))) env))
(define (%parameters-accept? params count)
  (cond ((%identifier? params) #t)
        ((null? params) (= count 0))
        ((and (pair? params) (> count 0)) (%parameters-accept? (cdr params) (- count 1)))
        (else #f)))
(define (%case-lambda-apply clauses args count env)
  (cond ((null? clauses) (error 'case-lambda "no matching arity" count))
        ((%parameters-accept? (caar clauses) count)
         (let ((local (%environment env)))
           (%bind-parameters! local (caar clauses) args)
           (%evaluate-body (cdar clauses) local)))
        (else (%case-lambda-apply (cdr clauses) args count env))))
(define (%syntax-case-lambda clauses env)
  (lambda args (%case-lambda-apply clauses args (length args) env)))
(%host-syntax! 'case-lambda %syntax-case-lambda)
(define (%syntax-current-environment args env)
  (%syntax-arity 'current-environment args 0 0) env)
(define (%syntax-procedure-property args env)
  ; Mes's guile.mes intentionally discards Guile procedure metadata.
  (%syntax-arity 'set-procedure-property! args 3 3) (%evaluate (car args) env))
(%host-syntax! 'current-environment %syntax-current-environment)
(%host-syntax! 'set-procedure-property! %syntax-procedure-property)
(%host-syntax! 'define-syntax %syntax-define-syntax)
(%host-syntax! 'let-syntax %syntax-let-syntax)
(%host-syntax! 'letrec-syntax %syntax-letrec-syntax)
(%host-syntax! 'define-syntax-rule %syntax-define-syntax-rule)
(%host-syntax! 'do %syntax-do)
(%host-syntax! 'with-fluids %syntax-with-fluids)
(%host-syntax! 'delay %syntax-delay)
(%host-syntax! 'lambda* %syntax-lambda*)
(%host-syntax! 'define* %syntax-define*)
(%host-syntax! 'defmacro %syntax-defmacro)
(%host-primitive! 'force force)
