; Lexical environments for the source-built Mes host.
; Frame = #(value-alist syntax-alist parent fallback definition-target).
; Cell = (value . owner-frame). Procedural macro overlays fall back to their
; definition module for private helpers, but definitions still affect the user.
; Mes has separate macro/value namespaces (its SRFI adapters rely on this).
; Imports share cells rather than copying values. No external host eval.
(define %undefined (list 'undefined))
(define (%environment parent) (vector '() '() parent #f #f))
(define (%environment-reaches? start target)
  (let ((seen '()))
    (define (visit env)
      (cond ((not env) #f) ((eq? env target) #t) ((%memq env seen) #f)
            (else (set! seen (cons env seen))
                  (or (visit (vector-ref env 2)) (visit (vector-ref env 3))))))
    (visit start)))
(define (%environment-overlay use-env definition-env)
  ; Repeated recursive macro expansion must not accumulate duplicate fallback
  ; branches. They change no bindings but make failed lookups grow explosively.
  (if (or (eq? use-env definition-env) (%environment-reaches? use-env definition-env)) use-env
      (vector '() '() use-env definition-env use-env)))
(define (%environment-definition-target env)
  (if (vector-ref env 4) (%environment-definition-target (vector-ref env 4)) env))
(define (%environment-local-slot env name slot)
  (let ((entry (%assq name (vector-ref env slot)))) (if entry (cdr entry) #f)))
(define (%environment-find-raw env name slot)
  (%env-find env name slot))
(define (%environment-find-slot env name slot)
  (or (%environment-find-raw env name slot)
      (and (%renamed-identifier? name)
           (%environment-find-raw (%identifier-environment name) (%identifier-name name) slot))))
(define (%environment-local env name) (%environment-local-slot env name 0))
(define (%environment-find env name) (%environment-find-slot env name 0))
(define (%environment-ref env name)
  (let ((cell (%environment-find env name)))
    (cond ((not cell) (error 'eval "unbound variable" (%identifier-name name)))
          ((eq? (car cell) %undefined) (error 'eval "uninitialized variable" (%identifier-name name)))
          (else (car cell)))))
(define (%environment-define-slot! environment name value slot)
  (let* ((env (%environment-definition-target environment))
         (cell (%environment-local-slot env name slot)))
    (if (and cell (eq? (cdr cell) env)) (set-car! cell value)
        ; define shadows an imported cell; set! still writes through aliases.
        (%environment-alias-slot! env name (cons value env) slot))))
(define (%environment-define! env name value) (%environment-define-slot! env name value 0))
(define (%environment-syntax! env name value) (%environment-define-slot! env name value 1))
(define (%environment-alias-slot! environment name cell slot)
  (let* ((env (%environment-definition-target environment))
         (entry (%assq name (vector-ref env slot))))
    (if entry (set-cdr! entry cell)
        (vector-set! env slot (cons (cons name cell) (vector-ref env slot))))))
(define (%environment-alias! env name cell) (%environment-alias-slot! env name cell 0))
(define (%environment-set! env name value)
  (let ((cell (%environment-find env name)))
    (if cell (set-car! cell value) (error 'set! "unbound variable" (%identifier-name name)))))
(define (%bind-parameters! env params args)
  (cond ((%identifier? params) (%environment-define! env params args))
        ((null? params) (if (null? args) #t (error 'apply "too many arguments")))
        ((not (pair? args)) (error 'apply "too few arguments"))
        (else (%environment-define! env (car params) (car args))
              (%bind-parameters! env (cdr params) (cdr args)))))
(define %host-environment (%environment #f))
(define %evaluation-environment (make-fluid %host-environment))
(define (interaction-environment) %host-environment)
(define (current-module) (fluid-ref %evaluation-environment))
(define (defined? name . rest)
  (let* ((env (if (null? rest) (current-module) (car rest)))
         (cell (or (%environment-find env name) (%environment-find-slot env name 1))))
    (and cell (not (eq? (car cell) %undefined)))))
(define %syntax-tag (list 'syntax))
(define %macro-tag (list 'macro))
(define (%tagged-procedure? value tag)
  (and (vector? value) (= (vector-length value) 2) (eq? (vector-ref value 0) tag)))
(define (%host-syntax! name handler)
  (%environment-syntax! %host-environment name (vector %syntax-tag handler)))
(define (%host-primitive! name procedure)
  (%environment-define! %host-environment name procedure))
