; Evaluation is decomposed by syntax handler, not a growing opcode switch.
; Interpreted closures are native Scheme closures, so apply, continuations,
; ports and the exact-integer library work without a second value ABI.
(define (%evaluate expr env)
  (cond ((keyword? expr) expr)
        ((%identifier? expr) (%environment-ref env expr))
        ((pair? expr) (%evaluate-call expr env))
        (else expr)))
(define (%evaluate-operator expression env)
  (let ((syntax (and (%identifier? expression) (%environment-find-slot env expression 1))))
    (if (and syntax (not (eq? (car syntax) %undefined))) (car syntax)
        (%evaluate expression env))))
(define (%evaluate-call expr env)
  (let ((operator (%evaluate-operator (car expr) env)))
    (cond ((%tagged-procedure? operator %syntax-tag)
           ((vector-ref operator 1) (cdr expr) env))
          ((%tagged-procedure? operator %macro-tag)
           (let ((parts (vector-ref operator 1)))
             (%evaluate (apply (car parts) (cdr expr)) (%environment-overlay env (cdr parts)))))
          ((%tagged-procedure? operator %er-macro-tag)
           (%evaluate (%expand-er operator expr env) env))
          ((procedure? operator) (apply operator (%evaluate-arguments (cdr expr) env '())))
          (else (error 'eval "not a procedure or syntax" (%identifier-name (car expr)))))))
(define (%evaluate-arguments args env acc)
  (cond ((null? args) (reverse acc))
        ((pair? args)
         (%evaluate-arguments (cdr args) env (cons (%evaluate (car args) env) acc)))
        (else (error 'eval "improper application"))))
(define (%evaluate-sequence body env)
  (cond ((null? body) #f)
        ((null? (cdr body)) (%evaluate (car body) env))
        (else (%evaluate (car body) env) (%evaluate-sequence (cdr body) env))))
(define (%definition-name form)
  (if (pair? (cadr form)) (car (cadr form)) (cadr form)))
(define (%body-splice body)
  (cond ((null? body) '())
        ((and (pair? (car body)) (eq? (%identifier-name (caar body)) 'begin))
         (%body-splice (append (cdar body) (cdr body))))
        (else (cons (car body) (%body-splice (cdr body))))))
(define (%prebind-definitions body env)
  (if (and (pair? body) (pair? (car body)) (eq? (%identifier-name (caar body)) 'define))
      (begin (%environment-define! env (%definition-name (car body)) %undefined)
             (%prebind-definitions (cdr body) env)) #f))
(define (%evaluate-body body env)
  (let ((forms (%body-splice body)))
    (%prebind-definitions forms env)
    (%evaluate-sequence forms env)))
(define (%closure params body env)
  (lambda args
    (let ((local (%environment env)))
      (%bind-parameters! local params args)
      (%evaluate-body body local))))
(define (eval expr . rest)
  (%evaluate expr (if (null? rest) %host-environment (car rest))))
(define (primitive-eval expr) (%evaluate expr (current-module)))
(define (%load-port port env)
  (let ((datum (read port)))
    (if (eof-object? datum) #t
        (begin (%evaluate datum env) (%load-port port env)))))
(define (%load-file path env)
  (%with-fluids (list (cons %evaluation-environment env))
    (lambda () (call-with-input-file path (lambda (p) (%load-port p env))))))
(define (load path) (%load-file path (current-module)))
