; Source-built, port-aware formatting. Unsupported controls fail explicitly.
; Covers Mes/simple-format plus integer radix controls used by compiler output.
(define (%format-control code args port)
  (cond ((eqv? code #\%) (newline port) args)
        ((eqv? code #\~) (write-char #\~ port) args)
        ((null? args) (error 'format "missing argument" code))
        (else
          (case (char-downcase code)
            ((#\a) (display (car args) port))
            ((#\s) (write (car args) port))
            ((#\c) (write-char (car args) port))
            ((#\d) (display (number->string (car args) 10) port))
            ((#\x) (display (number->string (car args) 16) port))
            ((#\o) (display (number->string (car args) 8) port))
            ((#\b) (display (number->string (car args) 2) port))
            (else (error 'format "unsupported control" code)))
          (cdr args))))
(define (%format-next-control text start)
  (let loop ((i start))
    (if (or (= i (string-length text)) (eqv? (string-ref text i) #\~)) i (loop (+ i 1)))))
(define (%format-to-port port text args)
  (let loop ((i 0) (args args))
    (let ((next (%format-next-control text i)))
      (display (substring text i next) port)
      (cond ((= next (string-length text))
             (if (null? args) #t (error 'format "unused arguments")))
            ((= (+ next 1) (string-length text)) (error 'format "trailing tilde"))
            (else (loop (+ next 2) (%format-control (string-ref text (+ next 1)) args port)))))))
(define (simple-format destination text . args)
  (cond ((not destination) (call-with-output-string (lambda (port) (%format-to-port port text args))))
        ((eq? destination #t) (%format-to-port (current-output-port) text args))
        (else (%format-to-port destination text args))))
(%host-primitive! 'simple-format simple-format)
(%host-primitive! 'format simple-format)
