; Explicit-renaming identifiers for Mes's source syntax-rules compiler.
; An introduced identifier carries its definition environment, not a guessed
; global name. Lexically bound introduced identifiers match by object identity;
; free ones resolve to the original definition-site cell. quote removes syntax
; wrappers without copying unchanged data (record descriptors retain identity).
(define %identifier-tag (list 'identifier))
(define (%renamed-identifier? x)
  (and (vector? x) (= (vector-length x) 3) (eq? (vector-ref x 0) %identifier-tag)))
(define (%identifier? x)
  (or (%renamed-identifier? x) (and (symbol? x) (not (keyword? x)))))
(define (%identifier-name x) (if (%renamed-identifier? x) (vector-ref x 1) x))
(define (%identifier-environment x) (vector-ref x 2))
(define (%strip-remember! old copy state)
  (let ((entry (cons old copy)))
    (vector-set! state 0 (cons entry (vector-ref state 0))) entry))
(define (%strip-pair-identifiers x state)
  (let* ((copy (cons #f #f)) (entry (%strip-remember! x copy state))
         (head (%strip-identifier-node (car x) state))
         (tail (%strip-identifier-node (cdr x) state)))
    (if (and (eq? head (car x)) (eq? tail (cdr x))) (set-cdr! entry x)
        (begin (set-car! copy head) (set-cdr! copy tail)))
    (cdr entry)))
(define (%strip-vector-identifiers x state)
  (let* ((copy (make-vector (vector-length x))) (entry (%strip-remember! x copy state)))
    (let loop ((i 0) (changed? #f))
      (if (= i (vector-length x))
          (begin (if changed? #f (set-cdr! entry x)) (cdr entry))
          (let* ((old (vector-ref x i)) (new (%strip-identifier-node old state)))
            (vector-set! copy i new)
            (loop (+ i 1) (or changed? (not (eq? old new)))))))))
(define (%strip-identifier-node x state)
  (cond ((%renamed-identifier? x) (vector-set! state 1 #t) (%identifier-name x))
        ((number? x) x)
        ((or (pair? x) (vector? x))
         (let ((known (assq x (vector-ref state 0))))
           (cond (known (cdr known))
                 ((pair? x) (%strip-pair-identifiers x state))
                 (else (%strip-vector-identifiers x state)))))
        (else x)))
(define (%strip-identifiers x)
  (let* ((state (vector '() #f)) (result (%strip-identifier-node x state)))
    ; Unchanged cyclic quotations retain their original identity, too.
    (if (vector-ref state 1) result x)))
(define %er-macro-tag (list 'explicit-renaming-macro))
(define %source-syntax-rules #f)
(define (%syntax-source-syntax-rules args env)
  ; The pinned compiler emits an ER transformer expression. Its implementation
  ; helpers belong to the compiler phase, not to the caller's value namespace.
  (let ((parts (vector-ref %source-syntax-rules 1)))
    (%analyze-generated-transformer (apply (car parts) args) (cdr parts))))
(define (%identifier-cell identifier env)
  (or (%environment-find-slot env identifier 1) (%environment-find-slot env identifier 0)))
(define (%identifier-equal? a b use-env)
  (and (%identifier? a) (%identifier? b)
       (let ((left (%identifier-cell a use-env)) (right (%identifier-cell b use-env)))
         (if (or left right) (eq? left right)
             (eq? (%identifier-name a) (%identifier-name b))))))
(define (%expand-er descriptor form use-env)
  (let* ((parts (vector-ref descriptor 1)) (transformer (car parts)) (definition-env (cdr parts))
         (renamed '()))
    (define (rename name)
      (cond ((keyword? name) name)
            ((%renamed-identifier? name) name)
            (else
              (let ((entry (assq name renamed)))
                (if entry (cdr entry)
                    (let ((identifier (vector %identifier-tag name definition-env)))
                      (set! renamed (cons (cons name identifier) renamed)) identifier))))))
    (transformer form rename (lambda (a b) (%identifier-equal? a b use-env)))))
(define (%bind-er-syntax! name expression definition-env target)
  (let ((transformer (%evaluate expression definition-env)))
    (if (procedure? transformer)
        (%environment-syntax! target name (vector %er-macro-tag (cons transformer definition-env)))
        (error 'define-syntax "transformer is not a procedure"))))
(define (%syntax-define-syntax args env)
  (%syntax-arity 'define-syntax args 2 2)
  (%bind-er-syntax! (car args) (cadr args) env env))
(define (%local-syntax args env recursive?)
  (let ((local (%environment env)) (bindings (car args)))
    (if recursive?
        (for-each (lambda (binding) (%environment-syntax! local (car binding) %undefined)) bindings) #f)
    (for-each (lambda (binding)
                (%bind-er-syntax! (car binding) (cadr binding) (if recursive? local env) local)) bindings)
    (%evaluate-body (cdr args) local)))
(define (%syntax-let-syntax args env) (%local-syntax args env #f))
(define (%syntax-letrec-syntax args env) (%local-syntax args env #t))
