; Small compatibility helpers needed by the pinned Mes library sources.
; Larger libraries (syntax-rules, SRFIs, pmatch, formatting) load from Mes.
(define %gensym-count 0)
(define (gensym . rest)
  (set! %gensym-count (+ %gensym-count 1))
  (make-symbol (string-append (if (null? rest) "g" (car rest)) (number->string %gensym-count))))
(define (%mes-divide . args)
  (if (null? args) 1
      (let loop ((value (%integer-check (car args))) (rest (cdr args)))
        (if (null? rest) value (loop (quotient value (car rest)) (cdr rest))))))
(define (%mes-port-position port)
  ; Mes boot-03.scm exposes zero when source coordinates are unavailable.
  (if (port? port) 0 (error 'port-position "not a port")))
(define (%host-unread-char char . rest)
  (if (and %mes-source-mode (eof-object? char))
      (begin (%input-port rest) char)
      (apply unread-char char rest)))
(define (identity x) x)
(define (const value) (lambda args value))
(define (negate predicate) (lambda args (not (apply predicate args))))
(define (acons key value rest) (cons (cons key value) rest))
(define (cons* first . rest)
  (if (null? rest) first (cons first (apply cons* rest))))
(define (append-reverse xs tail) (reverse-onto xs tail))
(define (reverse! xs . rest)
  (let loop ((xs xs) (tail (if (null? rest) '() (car rest))))
    (if (null? xs) tail
        (let ((next (cdr xs))) (set-cdr! xs tail) (loop next xs)))))
(define (make-list n . rest)
  (let ((fill (if (null? rest) #f (car rest))))
    (let loop ((n n) (result '()))
      (if (= n 0) result (loop (- n 1) (cons fill result))))))
(define (list-head xs n)
  (if (= n 0) '() (cons (car xs) (list-head (cdr xs) (- n 1)))))
(define (compose procedure . rest)
  (if (null? rest) procedure
      (let ((inner (apply compose rest)))
        (lambda args (procedure (apply inner args))))))
(define (and=> value proc) (and value (proc value)))
(define (vector-copy vec . rest)
  (let ((start (if (null? rest) 0 (car rest)))
        (end (if (or (null? rest) (null? (cdr rest))) (vector-length vec) (cadr rest))))
    (if (not (<= 0 start end (vector-length vec))) (error 'vector-copy "invalid range") #f)
    (let ((copy (make-vector (- end start))))
      (let loop ((i start))
        (if (= i end) copy
            (begin (vector-set! copy (- i start) (vector-ref vec i)) (loop (+ i 1))))))))
(define (assq-ref alist key) (let ((p (assq key alist))) (and p (cdr p))))
(define (assoc-ref alist key) (let ((p (assoc key alist))) (and p (cdr p))))
(define (assq-set! alist key value)
  (let ((p (assq key alist)))
    (if p (begin (set-cdr! p value) alist) (acons key value alist))))
(define (assoc-set! alist key value)
  (let ((p (assoc key alist)))
    (if p (begin (set-cdr! p value) alist) (acons key value alist))))
(define (%file-readable? path)
  (let ((fd (%file-open path 0 0)))
    (if (< fd 0) #f (begin (%file-close fd) #t))))
(define (access? path mode)
  (if (or (= mode 0) (= mode 4)) (%file-readable? path)
      (error 'access? "unsupported access mode" mode)))
(define (%core-type x)
  (cond ((char? x) 0) ((keyword? x) 4) ((number? x) 6) ((pair? x) 7)
        ((string? x) 10) ((symbol? x) 11) ((vector? x) 15) (else #f)))
(define (%macro-expand expression)
  (if (and (pair? expression) (%identifier? (car expression)))
      (let ((cell (%environment-find-slot (current-module) (car expression) 1)))
        (cond ((not cell) expression)
              ((%tagged-procedure? (car cell) %macro-tag)
               (%macro-expand (apply (car (vector-ref (car cell) 1)) (cdr expression))))
              ((%tagged-procedure? (car cell) %er-macro-tag)
               (%macro-expand (%expand-er (car cell) expression (current-module))))
              (else expression)))
      expression))

(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  (list (cons 'gensym gensym) (cons 'make-symbol make-symbol)
        (cons '/ %mes-divide)
        (cons 'bitwise-arithmetic-shift-left ash)
        (cons 'bitwise-arithmetic-shift-right (lambda (n count) (ash n (- count))))
        (cons 'port-line %mes-port-position) (cons 'port-column %mes-port-position)
        (cons 'unread-char %host-unread-char)
        (cons 'symbol? %identifier?)
        (cons 'symbol->string (lambda (x) (symbol->string (%identifier-name x))))
        (cons 'symbol->keyword (lambda (x) (symbol->keyword (%identifier-name x))))
        (cons 'identity identity) (cons 'const const) (cons 'acons acons) (cons 'cons* cons*)
        (cons 'append2 append) (cons 'append-reverse append-reverse)
        (cons 'reverse! reverse!) (cons 'core:reverse! reverse!)
        (cons 'make-list make-list) (cons 'list-head list-head) (cons 'take list-head)
        (cons 'compose compose) (cons 'negate negate) (cons 'and=> and=>)
        (cons 'vector-copy vector-copy)
        (cons 'with-input-from-string (lambda (s thunk)
                                      (call-with-input-string s (lambda (p) (with-input-from-port p thunk)))))
        (cons 'assq-ref assq-ref) (cons 'assoc-ref assoc-ref)
        (cons 'assq-set! assq-set!) (cons 'assoc-set! assoc-set!)
        (cons (string->symbol "1+") (lambda (x) (+ x 1)))
        (cons (string->symbol "1-") (lambda (x) (- x 1)))
        (cons (string->symbol "2-") (lambda (x) (- x 2)))
        (cons (string->symbol "3-") (lambda (x) (- x 3)))
        (cons 'cadar (lambda (x) (car (cdr (car x)))))
        (cons 'cddar (lambda (x) (cdr (cdr (car x)))))
        (cons 'caadr (lambda (x) (car (car (cdr x)))))
        (cons 'cdadr (lambda (x) (cdr (car (cdr x)))))
        (cons 'caaar (lambda (x) (car (car (car x)))))
        (cons 'cdaar (lambda (x) (cdr (car (car x)))))
        (cons 'syntax-error error) (cons 'silent-syntax-error error)
        (cons 'with-fluid* (lambda (fluid value thunk) (%with-fluids (list (cons fluid value)) thunk)))
        (cons 'with-fluids* (lambda (fluids values thunk) (%with-fluids (map cons fluids values) thunk)))
        (cons 'cond-expand-provide (lambda (env names) (set! %features (append names %features))))
        (cons 'core:apply (lambda (proc args . ignored) (apply proc args)))
        (cons 'core:car (lambda (x) (if (string? x) (string->list x) (car x))))
        (cons 'core:cdr (lambda (x) (if (char? x) (char->integer x) (cdr x))))
        (cons 'core:display display) (cons 'core:display-port display)
        (cons 'core:write write) (cons 'core:write-port write) (cons 'core:exit exit)
        (cons 'core:display-error (lambda (x) (display x (current-error-port))))
        (cons 'core:write-error (lambda (x) (write x (current-error-port))))
        (cons 'core:type %core-type) (cons 'core:macro-expand %macro-expand)
        (cons 'pmatch-car car) (cons 'pmatch-cdr cdr) (cons 'equal2? equal?)
        (cons 'keyword->string (compose symbol->string keyword->symbol))
        (cons 'access? access?) (cons 'file-exists? %file-readable?)
        (cons 'effective-version (lambda () "qfitzah-mes-host"))
        (cons 'object->string (lambda (x . rest)
                               (call-with-output-string
                                 (lambda (p) ((if (null? rest) write (car rest)) x p)))))))
(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  '((<cell:char> . 0) (<cell:keyword> . 4) (<cell:number> . 6) (<cell:pair> . 7)
    (<cell:string> . 10) (<cell:symbol> . 11) (<cell:vector> . 15)
    (R_OK . 4) (F_OK . 0) (%compiler . "qfitzah") (%program . #f)))
