; Native core list helpers expected by Mes's source SRFI-1 adapter.
(define (%pair-selector name path)
  (lambda (object)
    (let loop ((index (- (string-length path) 1)) (value object))
      (if (< index 0) value
          (if (pair? value)
              (loop (- index 1) (if (char=? (string-ref path index) #\a) (car value) (cdr value)))
              (error name "expected pair"))))))
(for-each
  (lambda (path)
    (let ((name (string->symbol (string-append "c" path "r"))))
      (%host-primitive! name (%pair-selector name path))))
  '("aaaa" "aaad" "aada" "aadd" "adaa" "adad" "adda" "addd"
    "daaa" "daad" "dada" "dadd" "ddaa" "ddad" "ddda" "dddd"))
(define (iota count . rest)
  (if (or (not (integer? count)) (< count 0)) (error 'iota "invalid count") #f)
  (let ((start (if (null? rest) 0 (car rest)))
        (step (if (or (null? rest) (null? (cdr rest))) 1 (cadr rest))))
    (let loop ((n count) (value start) (out '()))
      (if (= n 0) (reverse out) (loop (- n 1) (+ value step) (cons value out))))))
(define (last-pair xs)
  (if (not (pair? xs)) (error 'last-pair "expected nonempty list")
      (if (pair? (cdr xs)) (last-pair (cdr xs)) xs)))
(define (last xs) (car (last-pair xs)))
(define (append! . lists)
  (cond ((null? lists) '()) ((null? (cdr lists)) (car lists))
        ((null? (car lists)) (apply append! (cdr lists)))
        (else
          (let ((last (last-pair (car lists))))
            (if (not (null? (cdr last))) (error 'append! "improper non-final list") #f)
            (set-cdr! last (apply append! (cdr lists))) (car lists)))))
(define (filter predicate xs)
  (let loop ((xs xs) (out '()))
    (cond ((null? xs) (reverse out))
          ((predicate (car xs)) (loop (cdr xs) (cons (car xs) out)))
          (else (loop (cdr xs) out)))))
(define (remove predicate xs) (filter (lambda (x) (not (predicate x))) xs))
(define (%delete-list! same? value xs)
  (let ((head (cons #f xs)))
    (let loop ((previous head) (xs xs))
      (cond ((null? xs) (cdr head))
            ((same? value (car xs)) (set-cdr! previous (cdr xs)) (loop previous (cdr xs)))
            (else (loop xs (cdr xs)))))))
(define (delq value xs) (remove (lambda (x) (eq? value x)) xs))
(define (delv value xs) (remove (lambda (x) (eqv? value x)) xs))
(define (delete value xs . rest)
  (let ((same? (if (null? rest) equal? (car rest))))
    (remove (lambda (x) (same? value x)) xs)))
(define (delq! value xs) (%delete-list! eq? value xs))
(define (delv! value xs) (%delete-list! eqv? value xs))
(define (delete! value xs . rest)
  (%delete-list! (if (null? rest) equal? (car rest)) value xs))
(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  (list (cons 'iota iota) (cons 'last-pair last-pair) (cons 'last last) (cons 'append! append!)
        (cons 'filter filter) (cons 'remove remove)
        (cons 'delq delq) (cons 'delv delv) (cons 'delete delete)
        (cons 'delq! delq!) (cons 'delv! delv!) (cons 'delete! delete!)))
