; Mes-style script entry point. Compilation is never delegated to a host tool.
(define %script-argv (command-line))
(define %environment-overrides '())
(define (%host-getenv name)
  (let ((override (assoc name %environment-overrides)))
    (if override (cdr override) (getenv name))))
(define (%host-setenv name value)
  (set! %environment-overrides (assoc-set! %environment-overrides name value)) #t)
(%host-primitive! 'getenv %host-getenv)
(%host-primitive! 'setenv %host-setenv)
(%host-primitive! 'unsetenv (lambda (name) (%host-setenv name #f)))
(%host-primitive! 'command-line (lambda () %script-argv))
(define (%host-add-path path)
  (%environment-define! %host-environment '%load-path (cons path (%module-paths))))
(define (%host-mes-root root)
  (set! %mes-source-mode #t)
  (%environment-define! %host-environment '%load-path
    ; Prefer Mes's adapters over the Guile versions of the same modules.
    (append (list (string-append root "/mes/module") (string-append root "/module")) (%module-paths)))
  (%host-primitive! '%datadir (string-append root "/mes"))
  (%host-primitive! '%moduledir (string-append root "/mes/module/"))
  ; Bootstrap Mes's own procedural syntax-rules implementation from source.
  (let ((syntax-env (%environment %core-module-environment)))
    (%load-file (string-append root "/mes/module/mes/syntax.scm") syntax-env)
    (set! %source-syntax-rules (car (%environment-find-slot syntax-env 'syntax-rules 1))))
  (%host-syntax! 'syntax-rules %syntax-source-syntax-rules)
  ; Give the upstream explicit-renaming compiler definition-site identifiers,
  ; rather than Mes's bootstrap identity renamer.
  (%host-syntax! 'define-syntax %syntax-define-syntax))
(define (%host-run files entry arguments)
  ; Freeze the core parent before executing user code. Modules must not inherit
  ; accidental bindings from the interaction environment.
  (%refresh-core-module!)
  (set! %script-argv (cons (if (null? files) "mes-host" (car (reverse files))) arguments))
  (for-each (lambda (path) (%load-file path %host-environment)) files)
  (if entry
      ((%environment-ref %host-environment entry) %script-argv)
      (if (null? files) (%load-port (current-input-port) %host-environment) #t)))
(define (%host-options args files entry)
  (cond ((null? args) (%host-run (reverse files) entry '()))
        ((string=? (car args) "--") (%host-run (reverse files) entry (cdr args)))
        ((string=? (car args) "--help")
         (display "usage: mes-host [--mes MES_SOURCE] [-L DIRECTORY] [-e ENTRY] [FILE ...] [-- ARG ...]\n"))
        ((string=? (car args) "--no-auto-compile") (%host-options (cdr args) files entry))
        ((member (car args) '("--mes" "-L" "-e"))
         (if (null? (cdr args)) (error 'command-line "missing option operand" (car args))
             (cond ((string=? (car args) "--mes")
                    (%host-mes-root (cadr args)) (%host-options (cddr args) files entry))
                   ((string=? (car args) "-L")
                    (%host-add-path (cadr args)) (%host-options (cddr args) files entry))
                   (else (%host-options (cddr args) files (string->symbol (cadr args)))))))
        ((and (> (string-length (car args)) 0) (eqv? (string-ref (car args) 0) #\-))
         (error 'command-line "unknown option" (car args)))
        (else (%host-options (cdr args) (cons (car args) files) entry))))
(%host-options (cdr (command-line)) '() #f)
