; Source module loader. Modules own lexical environments and import cells;
; macro and value namespaces are both preserved. Unknown imports/options fail
; explicitly. No host Guile, compiled .go files, or implicit external search.
; Module = #(name environment exports-or-#f status).
(define %modules '())
(define %active-module (make-fluid #f))
(%host-primitive! '%load-path '())
(define (%module-paths) (%environment-ref %host-environment '%load-path))
(define (%module-name-path name)
  (string-join (map symbol->string name) "/"))
(define (%search-path paths file)
  (if (null? paths) #f
      (let ((candidate (string-append (car paths) "/" file)))
        (if (%file-readable? candidate) candidate (%search-path (cdr paths) file)))))
(define (%module-source name)
  (let ((base (%module-name-path name)) (paths (%module-paths)))
    (or (%search-path paths (string-append base ".scm"))
        (%search-path paths (string-append base ".mes"))
        (error 'use-modules "source module not found" name paths))))
(define (%module-export-names module)
  (or (vector-ref module 2)
      (append (map car (vector-ref (vector-ref module 1) 0))
              (map car (vector-ref (vector-ref module 1) 1)))))
(define (%module-predeclare! module names)
  (let ((env (vector-ref module 1)))
    (for-each
      (lambda (name)
        (if (not (symbol? name)) (error 'export "unsupported export specification" name) #f)
        (if (%environment-local env name) #f
            (let ((inherited (%environment-find (vector-ref env 2) name)))
              (%environment-define! env name (if inherited (car inherited) %undefined)))))
      names)
    (vector-set! module 2 (append (or (vector-ref module 2) '()) names))))
(define (%module-load name)
  (let ((existing (assoc name %modules)))
    (if existing
        (let ((module (cdr existing)))
          (if (eq? (vector-ref module 3) 'failed) (error 'use-modules "previous load failed" name)
              module))
        (let* ((path (%module-source name))
               (module (vector name (%environment %core-module-environment) #f 'loading)))
          (set! %modules (acons name module %modules))
          (if (getenv "QFITZAH_TRACE_IMPORTS")
              (begin (display "loading " (current-error-port))
                     (display path (current-error-port)) (newline (current-error-port))) #f)
          (catch #t
            (lambda ()
              (%with-fluids (list (cons %active-module module))
                (lambda () (%load-file path (vector-ref module 1))))
              (vector-set! module 3 'ready)
              module)
            (lambda (key . args)
              (vector-set! module 3 'failed)
              (display "while loading " (current-error-port))
              (display path (current-error-port)) (newline (current-error-port))
              (apply throw key args)))))))

(define (%import-options spec)
  (if (and (pair? spec) (pair? (car spec))) (cdr spec) '()))
(define (%import-name spec)
  (if (and (pair? spec) (pair? (car spec))) (car spec) spec))
(define (%module-option-name key)
  (cond ((keyword? key) (keyword->symbol key))
        ((and (symbol? key) (> (string-length (symbol->string key)) 1)
              (eqv? (string-ref (symbol->string key) 0) #\:))
         (let ((name (symbol->string key))) (string->symbol (substring name 1 (string-length name)))))
        (else (error 'define-module "expected keyword option" key))))
(define (%option options name default)
  (if (null? options) default
      (if (eq? (%module-option-name (car options)) name) (cadr options)
          (%option (cddr options) name default))))
(define (%check-import-options options)
  (if (null? options) #t
      (if (and (pair? (cdr options))
               (memq (%module-option-name (car options)) '(select prefix renamer)))
          (%check-import-options (cddr options))
          (error 'use-modules "unsupported import option" options))))
(define (%prefix-renamer prefix)
  (let ((text (if (symbol? prefix) (symbol->string prefix) prefix)))
    (lambda (name) (string->symbol (string-append text (symbol->string name))))))
(define (%selected-original selection) (if (pair? selection) (car selection) selection))
(define (%selected-local selection)
  (if (pair? selection)
      (if (pair? (cdr selection)) (cadr selection) (cdr selection)) selection))
(define (%import-cell! module original local target slot)
  (let ((cell (%environment-find-slot (vector-ref module 1) original slot)))
    (if cell (%environment-alias-slot! target local cell slot) #f)))
(define (%import-module! specification target)
  (let* ((module (%module-load (%import-name specification)))
         (options (%import-options specification))
         (exports (%module-export-names module)))
    (%check-import-options options)
    (let* ((selected (%option options 'select exports))
           (prefix (%option options 'prefix #f))
           (renamer (%option options 'renamer #f))
           (rename (cond (renamer (%evaluate renamer target))
                         (prefix (%prefix-renamer prefix)) (else identity))))
      (for-each
        (lambda (selection)
          (let ((original (%selected-original selection))
                (local (rename (%selected-local selection))))
            (if (not (memq original exports))
                (error 'use-modules "binding is not exported" (vector-ref module 0) original) #f)
            (%import-cell! module original local target 0)
            (%import-cell! module original local target 1))) selected))))
(define (%syntax-use-modules args env)
  (for-each (lambda (spec) (%import-module! spec env)) args))
(define (%syntax-mes-use-module args env) (%import-module! (car args) env))

(define (%declaration-exports options module)
  (if (null? options) #t
      (let ((key (%module-option-name (car options))))
        (if (memq key '(export export-syntax re-export replace))
            (%module-predeclare! module (cadr options)) #f)
        (%declaration-exports (cddr options) module))))
(define (%declaration-imports options env)
  (if (null? options) #t
      (let ((key (%module-option-name (car options))) (value (cadr options)))
        (cond ((memq key '(use-module use-syntax)) (%import-module! value env))
              ((memq key '(export export-syntax re-export replace version)) #t)
              (else (error 'define-module "unsupported module option" key)))
        (%declaration-imports (cddr options) env))))
(define (%syntax-define-module args env)
  (let ((module (fluid-ref %active-module)))
    (if (not module)
        (begin (set! module (vector (car args) env #f 'ready))
               (set! %modules (acons (car args) module %modules))) #f)
    (if (not (equal? (car args) (vector-ref module 0)))
        (error 'define-module "source declares a different module" (car args)) #f)
    (%declaration-exports (cdr args) module)
    (%declaration-imports (cdr args) env)))
(define (%syntax-export args env)
  (let ((module (fluid-ref %active-module)))
    (if module (%module-predeclare! module args) (error 'export "not in a module"))))
(define (%syntax-include args env)
  (for-each
    (lambda (expression)
      (let ((name (%evaluate expression env)))
        (%load-file (or (%search-path (%module-paths) name)
                        (and (%file-readable? name) name)
                        (error 'include "source not found" name)) env))) args))

(define (%module-reference args private?)
  (let* ((module (%module-load (car args))) (name (cadr args)) (env (vector-ref module 1)))
    (if (or private? (memq name (%module-export-names module)))
        (let ((value (%environment-find env name)) (syntax (%environment-find-slot env name 1)))
          (cond ((and value (not (eq? (car value) %undefined))) (car value))
                (syntax (car syntax))
                (else (error '@ "unbound module variable" name))))
        (error '@ "binding is not exported" name))))
(define (%syntax-module-reference args env) (%module-reference args #f))
(define (%syntax-private-reference args env) (%module-reference args #t))
(%host-syntax! '@ %syntax-module-reference)
(%host-syntax! '@@ %syntax-private-reference)
(%host-syntax! 'define-module %syntax-define-module)
(%host-syntax! 'use-modules %syntax-use-modules)
(%host-syntax! 'mes-use-module %syntax-mes-use-module)
(%host-syntax! 'export %syntax-export)
(%host-syntax! 'include %syntax-include)
(%host-syntax! 'include-from-path %syntax-include)
(%host-primitive! 'resolve-module (lambda (name) (vector-ref (%module-load name) 1)))
(%host-primitive! 'module-ref %environment-ref)
(%host-primitive! 'module-define! %environment-define!)
(%host-primitive! 'symbol-prefix-proc %prefix-renamer)
(%host-primitive! 'search-path %search-path)

; Mes uses (@ (guile) member), etc. to retain original core procedures before
; wrapping them in its SRFI adapters. This is a source-built snapshot, not a
; dependency on Guile, and user module definitions cannot mutate its cells.
(define %core-module-environment (%environment #f))
(define (%refresh-core-module!)
  (for-each
    (lambda (slot)
      (for-each (lambda (binding)
                  (%environment-define-slot! %core-module-environment (car binding) (cadr binding) slot)
                  ; Interaction and module primitives denote the same binding
                  ; for syntax-rules literals. Later user defines shadow these
                  ; imported cells instead of modifying the core snapshot.
                  (%environment-alias-slot! %host-environment (car binding)
                    (%environment-local-slot %core-module-environment (car binding) slot) slot))
                (vector-ref %host-environment slot))) '(0 1)))
(%refresh-core-module!)
(set! %modules (acons '(guile) (vector '(guile) %core-module-environment #f 'ready) %modules))

; Mes's display.mes inspects its VM's raw cell layout. Our VM has a different
; representation, so provide only its public writer interface from the
; source-built port layer, rather than pretending to expose Mes core:car/cdr.
(define (%core-interface-module! name exports)
  (let ((env (%environment #f)))
    (for-each (lambda (key)
                (%environment-define! env key (%environment-ref %core-module-environment key))) exports)
    (set! %modules (acons name (vector name env exports 'ready) %modules))))
(%core-interface-module! '(mes display) '(display write write-char newline))
