; Explicit native boundary. Every entry is compiled earlier in this source
; bootstrap, never supplied by a host Scheme or dynamically linked library.
(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  (list
    (cons 'cons cons) (cons 'car car) (cons 'cdr cdr)
    (cons 'caar caar) (cons 'cadr cadr) (cons 'cdar cdar) (cons 'cddr cddr)
    (cons 'caddr caddr) (cons 'cdddr cdddr) (cons 'cadddr cadddr)
    (cons 'set-car! set-car!) (cons 'set-cdr! set-cdr!)
    (cons 'pair? pair?) (cons 'null? null?) (cons 'list list)
    (cons 'list? %reader-proper?) (cons 'length length)
    (cons 'list-ref list-ref) (cons 'list-tail list-tail)
    (cons 'append append) (cons 'reverse reverse) (cons 'map map) (cons 'for-each for-each)
    (cons 'memq memq) (cons 'memv memv) (cons 'member member)
    (cons 'assq assq) (cons 'assv assv) (cons 'assoc assoc)
    (cons 'eq? eq?) (cons 'eqv? eqv?) (cons 'equal? equal?) (cons 'not not)
    (cons 'symbol? symbol?) (cons 'string? string?) (cons 'char? char?)
    (cons 'boolean? boolean?) (cons 'number? number?) (cons 'integer? integer?)
    (cons 'exact? exact?) (cons 'real? real?) (cons 'rational? rational?)
    (cons 'complex? complex?) (cons 'procedure? procedure?)
    (cons '+ +) (cons '- -) (cons '* *) (cons 'quotient quotient) (cons 'remainder remainder)
    (cons '= =) (cons '< <) (cons '> >) (cons '<= <=) (cons '>= >=)
    (cons 'zero? zero?) (cons 'positive? positive?) (cons 'negative? negative?)
    (cons 'abs abs) (cons 'min min) (cons 'max max) (cons 'gcd gcd)
    (cons 'modulo modulo) (cons 'even? even?) (cons 'odd? odd?)
    (cons 'number->string number->string) (cons 'string->number string->number)
    (cons 'logand logand) (cons 'logior logior) (cons 'logxor logxor)
    (cons 'lognot lognot) (cons 'ash ash)
    (cons 'bitwise-and bitwise-and) (cons 'bitwise-ior bitwise-ior)
    (cons 'bitwise-xor bitwise-xor) (cons 'bitwise-not bitwise-not)
    (cons 'bitwise-arithmetic-shift bitwise-arithmetic-shift)
    (cons 'string string) (cons 'make-string make-string)
    (cons 'string-ref string-ref) (cons 'string-set! string-set!)
    (cons 'string-length string-length) (cons 'substring substring)
    (cons 'string-copy string-copy) (cons 'string-append string-append)
    (cons 'string=? string=?) (cons 'string<? string<?)
    (cons 'string->list string->list) (cons 'list->string list->string)
    (cons 'string->symbol string->symbol) (cons 'symbol->string symbol->string)
    (cons 'keyword? keyword?) (cons 'keyword->symbol keyword->symbol)
    (cons 'symbol->keyword symbol->keyword)
    (cons 'char->integer char->integer) (cons 'integer->char integer->char)
    (cons 'char=? char=?) (cons 'char<? char<?) (cons 'char>? char>?)
    (cons 'char<=? char<=?) (cons 'char>=? char>=?)
    (cons 'char-alphabetic? char-alphabetic?) (cons 'char-numeric? char-numeric?)
    (cons 'char-whitespace? char-whitespace?) (cons 'char-upcase char-upcase)
    (cons 'char-downcase char-downcase)
    (cons 'vector vector) (cons 'make-vector make-vector) (cons 'vector? vector?)
    (cons 'vector-ref vector-ref) (cons 'vector-set! vector-set!)
    (cons 'vector-length vector-length) (cons 'vector-fill! vector-fill!)
    (cons 'vector->list vector->list) (cons 'list->vector list->vector)
    (cons 'read read) (cons 'read-char read-char) (cons 'peek-char peek-char)
    (cons 'unread-char unread-char) (cons 'eof-object? eof-object?)
    (cons 'write write) (cons 'display display) (cons 'newline newline)
    (cons 'write-char write-char) (cons 'force-output force-output)
    (cons 'port? port?) (cons 'input-port? input-port?) (cons 'output-port? output-port?)
    (cons 'current-input-port current-input-port) (cons 'current-output-port current-output-port)
    (cons 'current-error-port current-error-port)
    (cons 'set-current-input-port set-current-input-port)
    (cons 'set-current-output-port set-current-output-port)
    (cons 'set-current-error-port set-current-error-port)
    (cons 'port-filename port-filename) (cons 'set-port-filename! set-port-filename!)
    (cons 'port-closed? port-closed?) (cons 'fileno fileno)
    (cons 'open-input-file open-input-file) (cons 'open-output-file open-output-file)
    (cons 'open-file open-file) (cons 'close-port close-port)
    (cons 'close-input-port close-input-port) (cons 'close-output-port close-output-port)
    (cons 'open-input-string open-input-string) (cons 'open-output-string open-output-string)
    (cons 'get-output-string get-output-string)
    (cons 'call-with-input-file call-with-input-file) (cons 'call-with-output-file call-with-output-file)
    (cons 'call-with-input-string call-with-input-string)
    (cons 'call-with-output-string call-with-output-string)
    (cons 'with-input-from-file with-input-from-file) (cons 'with-output-to-file with-output-to-file)
    (cons 'with-output-to-string with-output-to-string)
    (cons 'with-input-from-port with-input-from-port) (cons 'with-output-to-port with-output-to-port)
    (cons 'apply apply) (cons 'call/cc call/cc)
    (cons 'call-with-current-continuation call-with-current-continuation)
    (cons 'dynamic-wind dynamic-wind) (cons 'values values) (cons 'call-with-values call-with-values)
    (cons 'catch catch) (cons 'throw throw) (cons 'with-throw-handler with-throw-handler)
    (cons 'error error) (cons 'exit exit) (cons 'gc gc) (cons 'gc-count gc-count)
    (cons '%gc-live-units %gc-live-units)
    (cons '%gc-largest-free-units %gc-largest-free-units)
    (cons 'getenv getenv) (cons 'command-line command-line)
    (cons 'make-fluid make-fluid) (cons 'fluid? fluid?)
    (cons 'fluid-ref fluid-ref) (cons 'fluid-set! fluid-set!)
    (cons 'eval eval) (cons 'primitive-eval primitive-eval)
    (cons 'interaction-environment interaction-environment) (cons 'current-module current-module)
    (cons 'defined? defined?) (cons 'load load) (cons 'primitive-load load)
    (cons 'variable-ref car) (cons 'variable-set! set-car!)))
(%host-primitive! 'mes #t)
(%host-primitive! 'mes? #t)
(%host-primitive! 'guile? #f)
(%host-primitive! '%arch "x86")
(%host-primitive! '%kernel "linux")
(%host-primitive! '%scheme "qfitzah")
(%host-primitive! '%version "qfitzah-mes-host-in-progress")
(%host-primitive! '*undefined* %undefined)
