; SRFI-9 and Mes record reflection, represented entirely as Scheme vectors.
; Types carry field names; constructors/accessors close over the type object.
(define %record-type-tag (list 'record-type))
(define (make-record-type name fields) (vector %record-type-tag name fields))
(define (record-type? x)
  (and (vector? x) (= (vector-length x) 3) (eq? (vector-ref x 0) %record-type-tag)))
(define (record? x)
  (and (vector? x) (> (vector-length x) 0) (record-type? (vector-ref x 0))))
(define (record-type-descriptor x)
  (if (record? x) (vector-ref x 0) (error 'record-type-descriptor "not a record")))
(define (%record-type x)
  (if (record-type? x) x (record-type-descriptor x)))
(define (record-type-name x) (vector-ref (%record-type x) 1))
(define (record-type-fields x) (vector-ref (%record-type x) 2))
(define (record-field-index type field)
  (let loop ((fields (record-type-fields type)) (index 1))
    (cond ((null? fields) (error 'record "unknown field" field))
          ((eq? field (car fields)) index)
          (else (loop (cdr fields) (+ index 1))))))
(define (%check-record type object)
  (if (and (record? object) (eq? (vector-ref object 0) type)) object
      (error 'record "record of different type" (record-type-name type))))
(define (record-constructor type . rest)
  (let ((fields (if (null? rest) (record-type-fields type) (car rest))))
    (lambda args
      (if (not (= (length fields) (length args))) (error 'record-constructor "wrong arity") #f)
      (let ((record (make-vector (+ 1 (length (record-type-fields type))) #f)))
        (vector-set! record 0 type)
        (for-each (lambda (field value) (vector-set! record (record-field-index type field) value)) fields args)
        record))))
(define (record-predicate type)
  (lambda (object) (and (record? object) (eq? (vector-ref object 0) type))))
(define (record-accessor type field)
  (let ((index (record-field-index type field)))
    (lambda (object . field?)
      (%check-record type object)
      (if (pair? field?) field (vector-ref object index)))))
(define (record-modifier type field)
  (let ((index (record-field-index type field)))
    (lambda (object value)
      (%check-record type object) (vector-set! object index value))))
(define (%syntax-record-type args env)
  (let* ((name (car args)) (constructor (cadr args)) (predicate (caddr args))
         (fields (cdddr args))
         (type (make-record-type (%identifier-name name) (map (compose %identifier-name car) fields))))
    (%environment-define! env name type)
    (%environment-define! env (car constructor) (record-constructor type (map %identifier-name (cdr constructor))))
    (%environment-define! env predicate (record-predicate type))
    (for-each
      (lambda (field)
        (%environment-define! env (cadr field) (record-accessor type (%identifier-name (car field))))
        (if (pair? (cddr field))
            (%environment-define! env (caddr field) (record-modifier type (%identifier-name (car field)))) #f)) fields)))
(%host-syntax! 'define-record-type %syntax-record-type)
(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  (list (cons 'make-record-type make-record-type) (cons 'record-type? record-type?)
        (cons 'record? record?) (cons 'record-type-descriptor record-type-descriptor)
        (cons 'struct-vtable record-type-descriptor) (cons 'record-type-name record-type-name)
        (cons 'record-type-fields record-type-fields) (cons 'record-constructor record-constructor)
        (cons 'record-predicate record-predicate) (cons 'record-accessor record-accessor)
        (cons 'record-modifier record-modifier) (cons 'record-field-index record-field-index)))
