; String/path operations used by source-module loading and Nyacc's emitters.
(define (string-split s delimiter)
  (let loop ((start 0) (i 0) (parts '()))
    (cond ((= i (string-length s)) (reverse (cons (substring s start i) parts)))
          ((eqv? (string-ref s i) delimiter)
           (loop (+ i 1) (+ i 1) (cons (substring s start i) parts)))
          (else (loop start (+ i 1) parts)))))
(define (string-join strings . rest)
  (let ((separator (if (null? rest) " " (car rest))))
    (if (null? strings) ""
        (let loop ((xs (cdr strings)) (out (car strings)))
          (if (null? xs) out (loop (cdr xs) (string-append out separator (car xs))))))))
(define (string-prefix? prefix text)
  (and (<= (string-length prefix) (string-length text))
       (string=? prefix (substring text 0 (string-length prefix)))))
(define (string-suffix? suffix text)
  (let ((start (- (string-length text) (string-length suffix))))
    (and (>= start 0) (string=? suffix (substring text start (string-length text))))))
(define (string-drop text count) (%host-substring text count))
(define (string-take text count) (%host-substring text 0 count))
(define (string-take-right text count)
  (if (and (integer? count) (<= 0 count (string-length text)))
      (%host-substring text (- (string-length text) count))
      (error 'string-take-right "invalid count")))
(define (string-drop-right text count)
  (if (and (integer? count) (<= 0 count (string-length text)))
      (substring text 0 (- (string-length text) count))
      (error 'string-drop-right "invalid count")))
(define (%string-range who text bounds)
  (if (not (string? text)) (error who "not a string") #f)
  (if (> (length bounds) 2) (error who "too many bounds") #f)
  (let ((start (if (pair? bounds) (car bounds) 0))
        (end (if (and (pair? bounds) (pair? (cdr bounds))) (cadr bounds) (string-length text))))
    (if (and (integer? start) (integer? end) (<= 0 start end (string-length text)))
        (cons start end) (error who "invalid bounds" start end))))
(define (%host-substring . args)
  (if (not (<= 2 (length args) 3)) (error 'substring "expected two or three arguments") #f)
  (let* ((text (car args)) (range (%string-range 'substring text (cdr args))))
    (substring text (car range) (cdr range))))
(define (%string-matcher who matcher)
  (cond ((char? matcher) (lambda (char) (char=? char matcher)))
        ((procedure? matcher) matcher)
        ((char-set? matcher) (lambda (char) (char-set-contains? matcher char)))
        (else (error who "invalid character predicate"))))
(define (%string-index text matcher bounds backwards?)
  (let* ((range (%string-range 'string-index text bounds)) (predicate (%string-matcher 'string-index matcher))
         (start (car range)) (end (cdr range)))
    (let loop ((i (if backwards? (- end 1) start)))
      (cond ((or (< i start) (>= i end)) #f)
            ((predicate (string-ref text i)) i)
            (else (loop (+ i (if backwards? -1 1))))))))
(define (string-index text matcher . bounds) (%string-index text matcher bounds #f))
(define (string-index-right text matcher . bounds) (%string-index text matcher bounds #t))
(define (%string-filter who matcher text bounds keep?)
  (let* ((range (%string-range who text bounds)) (predicate (%string-matcher who matcher)))
    (let loop ((i (car range)) (out '()))
      (if (= i (cdr range)) (list->string (reverse out))
          (let ((char (string-ref text i)))
            (loop (+ i 1)
                  (if (if (predicate char) keep? (not keep?)) (cons char out) out)))))))
(define (string-filter matcher text . bounds)
  (%string-filter 'string-filter matcher text bounds #t))
(define (string-delete matcher text . bounds)
  (%string-filter 'string-delete matcher text bounds #f))
(define (%string-fold who procedure seed text bounds backwards?)
  (if (not (procedure? procedure)) (error who "not a procedure") #f)
  (let* ((range (%string-range who text bounds)) (start (car range)) (end (cdr range)))
    (let loop ((i (if backwards? (- end 1) start)) (value seed))
      (if (or (< i start) (>= i end)) value
          (loop (+ i (if backwards? -1 1)) (procedure (string-ref text i) value))))))
(define (string-fold procedure seed text . bounds)
  (%string-fold 'string-fold procedure seed text bounds #f))
(define (string-fold-right procedure seed text . bounds)
  (%string-fold 'string-fold-right procedure seed text bounds #t))
(define (%path-end path)
  (let loop ((end (string-length path)))
    (if (and (> end 1) (eqv? (string-ref path (- end 1)) #\/)) (loop (- end 1)) end)))
(define (%path-base path)
  (let ((end (%path-end path)))
    (if (and (= end 1) (eqv? (string-ref path 0) #\/)) "/"
        (let loop ((start end))
          (if (or (= start 0) (eqv? (string-ref path (- start 1)) #\/))
              (substring path start end) (loop (- start 1)))))))
(define (dirname path)
  (let loop ((i (- (%path-end path) 1)))
    (cond ((< i 0) ".")
          ((eqv? (string-ref path i) #\/)
           (let trim ((end i))
             (cond ((= end 0) "/")
                   ((eqv? (string-ref path (- end 1)) #\/) (trim (- end 1)))
                   (else (substring path 0 end)))))
          (else (loop (- i 1))))))
(define (basename path . rest)
  (let ((base (%path-base path)))
    (if (and (pair? rest) (< (string-length (car rest)) (string-length base))
             (string-suffix? (car rest) base))
        (string-drop-right base (string-length (car rest))) base)))
(for-each (lambda (entry) (%host-primitive! (car entry) (cdr entry)))
  (list (cons 'string-split string-split) (cons 'string-join string-join)
        (cons 'string-prefix? string-prefix?) (cons 'string-suffix? string-suffix?)
        (cons 'string-drop-right string-drop-right) (cons 'basename basename)
        (cons 'string-drop string-drop) (cons 'string-take string-take)
        (cons 'string-take-right string-take-right)
        (cons 'dirname dirname)
        (cons 'string-index string-index) (cons 'string-index-right string-index-right)
        (cons 'string-filter string-filter) (cons 'string-delete string-delete)
        (cons 'string-fold string-fold) (cons 'string-fold-right string-fold-right)
        ; Nyacc only reads this slice; our byte-string ABI returns a copy.
        (cons 'substring %host-substring) (cons 'substring/shared %host-substring)
        (cons 'reverse-list->string (lambda (chars) (list->string (reverse chars))))
        (cons 'string-null? (lambda (s) (= (string-length s) 0)))))
