; Core syntactic forms for the Mes host. Each handler receives operands/env.
(define (%syntax-arity name args minimum maximum)
  (let ((n (length args)))
    (if (or (< n minimum) (and maximum (> n maximum)))
        (error name "wrong syntax arity") #t)))
(define (%syntax-quote args env)
  (%syntax-arity 'quote args 1 1)
  (%strip-identifiers (car args)))
(define (%syntax-if args env)
  ; Mes eval-apply.c ignores operands after the first alternative. Its shipped
  ; SRFI-1 folds contain such forms. Keep strict checking outside --mes mode.
  (%syntax-arity 'if args 2 (if %mes-source-mode #f 3))
  (if (%evaluate (car args) env) (%evaluate (cadr args) env)
      (if (null? (cddr args)) #f (%evaluate (caddr args) env))))
(define (%syntax-lambda args env)
  (%syntax-arity 'lambda args 2 #f)
  (%closure (car args) (cdr args) env))
(define (%syntax-define args env)
  (let ((target (car args)))
    (if (pair? target)
        (%environment-define! env (car target) (%closure (cdr target) (cdr args) env))
        (%environment-define! env target
          (if (null? (cdr args)) #f (%evaluate (cadr args) env))))))
(define (%syntax-set! args env)
  (%syntax-arity 'set! args 2 2)
  (%environment-set! env (car args) (%evaluate (cadr args) env)))
(define (%syntax-define-macro args env)
  (let* ((target (car args))
         (name (if (pair? target) (car target) target))
         (procedure (if (pair? target) (%closure (cdr target) (cdr args) env)
                        (%evaluate (cadr args) env))))
    (if (not (procedure? procedure)) (error 'define-macro "not a procedure" name)
        (%environment-syntax! env name (vector %macro-tag (cons procedure env))))))
(define (%syntax-and args env)
  (cond ((null? args) #t)
        ((null? (cdr args)) (%evaluate (car args) env))
        (else (and (%evaluate (car args) env) (%syntax-and (cdr args) env)))))
(define (%syntax-or args env)
  (cond ((null? args) #f)
        ((null? (cdr args)) (%evaluate (car args) env))
        (else (or (%evaluate (car args) env) (%syntax-or (cdr args) env)))))
(define (%syntax-cond clauses env)
  (if (null? clauses) #f
      (let* ((clause (car clauses)) (test (car clause))
             (value (if (eq? (%identifier-name test) 'else) #t (%evaluate test env))))
        (cond ((not value) (%syntax-cond (cdr clauses) env))
              ((null? (cdr clause)) value)
              ((eq? (%identifier-name (cadr clause)) '=>)
               (let ((proc (%evaluate (caddr clause) env)))
                 (if (procedure? proc) (proc value) (error 'cond "not a procedure"))))
              (else (%evaluate-sequence (cdr clause) env))))))
(define (%case-clauses value clauses env)
  (if (null? clauses) #f
      (let ((clause (car clauses)))
        (if (or (eq? (%identifier-name (car clause)) 'else)
                (memv value (%strip-identifiers (car clause))))
            (%evaluate-sequence (cdr clause) env)
            (%case-clauses value (cdr clauses) env)))))
(define (%syntax-case args env)
  (%case-clauses (%evaluate (car args) env) (cdr args) env))

(define (%binding-names bindings) (map car bindings))
(define (%binding-values bindings env)
  (%evaluate-arguments (map cadr bindings) env '()))
(define (%bind-values! env names values)
  (if (null? names) #t
      (begin (%environment-define! env (car names) (car values))
             (%bind-values! env (cdr names) (cdr values)))))
(define (%syntax-let args env)
  (if (%identifier? (car args))
      (%syntax-named-let (car args) (cadr args) (cddr args) env)
      (let* ((bindings (car args)) (local (%environment env)))
        (%bind-values! local (%binding-names bindings) (%binding-values bindings env))
        (%evaluate-body (cdr args) local))))
(define (%syntax-named-let name bindings body env)
  (let* ((local (%environment env)) (proc (%closure (%binding-names bindings) body local)))
    (%environment-define! local name proc)
    (apply proc (%binding-values bindings env))))
(define (%let-star bindings body env)
  (if (null? bindings) (%evaluate-body body (%environment env))
      (let ((local (%environment env)))
        (%environment-define! local (caar bindings) (%evaluate (cadr (car bindings)) env))
        (%let-star (cdr bindings) body local))))
(define (%syntax-let* args env) (%let-star (car args) (cdr args) env))
(define (%prebind-letrec bindings env)
  (for-each (lambda (binding) (%environment-define! env (car binding) %undefined)) bindings))
(define (%syntax-letrec args env)
  (let ((local (%environment env)) (bindings (car args)))
    (%prebind-letrec bindings local)
    (%bind-values! local (%binding-names bindings) (%binding-values bindings local))
    (%evaluate-body (cdr args) local)))
(define (%syntax-letrec* args env)
  (let ((local (%environment env)) (bindings (car args)))
    (%prebind-letrec bindings local)
    (for-each (lambda (binding)
                (%environment-define! local (car binding) (%evaluate (cadr binding) local))) bindings)
    (%evaluate-body (cdr args) local)))
(define (%syntax-when args env)
  (if (%evaluate (car args) env) (%evaluate-sequence (cdr args) env) #f))
(define (%syntax-unless args env)
  (if (%evaluate (car args) env) #f (%evaluate-sequence (cdr args) env)))

; Quasiquote evaluates splices only at the correct depth and sequence position.
(define (%qq-tag? x tag) (and (pair? x) (eq? (%identifier-name (car x)) tag)))
(define (%quasiquote x env depth)
  (cond ((%renamed-identifier? x) (%identifier-name x))
        ((number? x) x)
        ((vector? x) (list->vector (%quasiquote (vector->list x) env depth)))
        ((not (pair? x)) x)
        ((%qq-tag? x 'unquote)
         (if (= depth 1) (%evaluate (cadr x) env)
             (list 'unquote (%quasiquote (cadr x) env (- depth 1)))))
        ((%qq-tag? x 'unquote-splicing)
         (if (= depth 1) (error 'quasiquote "splice outside sequence")
             (list 'unquote-splicing (%quasiquote (cadr x) env (- depth 1)))))
        ((%qq-tag? x 'quasiquote)
         (list 'quasiquote (%quasiquote (cadr x) env (+ depth 1))))
        ((and (= depth 1) (%qq-tag? (car x) 'unquote-splicing))
         (append (%evaluate (cadr (car x)) env) (%quasiquote (cdr x) env depth)))
        (else (cons (%quasiquote (car x) env depth) (%quasiquote (cdr x) env depth)))))
(define (%syntax-quasiquote args env) (%quasiquote (car args) env 1))
(define %features '(mes qfitzah))
(define (%feature? requirement)
  (if (symbol? requirement) (or (eq? requirement 'else) (memq requirement %features))
      (case (car requirement)
        ((and) (%features-all? (cdr requirement)))
        ((or) (%features-any? (cdr requirement)))
        ((not) (not (%feature? (cadr requirement))))
        (else #f))))
(define (%features-all? xs) (or (null? xs) (and (%feature? (car xs)) (%features-all? (cdr xs)))))
(define (%features-any? xs) (and (pair? xs) (or (%feature? (car xs)) (%features-any? (cdr xs)))))
(define (%syntax-cond-expand clauses env)
  (cond ((null? clauses) (error 'cond-expand "no matching feature"))
        ((%feature? (caar clauses)) (%evaluate-sequence (cdar clauses) env))
        (else (%syntax-cond-expand (cdr clauses) env))))

(for-each (lambda (entry) (%host-syntax! (car entry) (cdr entry)))
  (list (cons 'quote %syntax-quote) (cons 'if %syntax-if)
        (cons 'lambda %syntax-lambda) (cons 'define %syntax-define)
        (cons 'set! %syntax-set!) (cons 'begin %evaluate-sequence)
        (cons 'define-macro %syntax-define-macro)
        (cons 'and %syntax-and) (cons 'or %syntax-or) (cons 'cond %syntax-cond)
        (cons 'case %syntax-case) (cons 'let %syntax-let) (cons 'let* %syntax-let*)
        (cons 'letrec %syntax-letrec) (cons 'letrec* %syntax-letrec*)
        (cons 'when %syntax-when) (cons 'unless %syntax-unless)
        (cons 'quasiquote %syntax-quasiquote) (cons 'cond-expand %syntax-cond-expand)))
